type Fetcher = typeof fetch;
export type ChecklistScope = { operatingLocationId: string; lifecycleStage: string; missionId?: string; aircraftId?: string; maintainableAssetId?: string; assetSystemId?: string; componentPositionId?: string; configurationCode?: string };
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const invalid=():never=>{throw new Error('Checklist response was invalid.');};
const object=(v:unknown):Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:invalid();
const id=(v:unknown)=>typeof v==='string'&&UUID.test(v)?v:invalid();
const text=(v:unknown,max=500)=>typeof v==='string'&&v.length<=max&&!Array.from(v).some(character=>{const code=character.codePointAt(0)??0;return code<=31||code===127;})?v:invalid();
const positiveInteger=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>0?v:invalid();
const oneOf=<T extends string>(value:unknown,values:readonly T[])=>typeof value==='string'&&values.includes(value as T)?value as T:invalid();
const digest=(value:unknown)=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value)?value:invalid();
const enforceAuthorityBudget=(value:unknown)=>{let nodes=0,bytes=0;const visit=(entry:unknown,depth:number):void=>{nodes+=1;if(nodes>10000||depth>8)invalid();if(typeof entry==='string'){bytes+=entry.length;if(bytes>262144)invalid();return;}if(entry===null||typeof entry==='boolean'||typeof entry==='number')return;if(Array.isArray(entry)){if(entry.length>500)invalid();entry.forEach(child=>visit(child,depth+1));return;}const record=object(entry),entries=Object.entries(record);if(entries.length>100)invalid();for(const[key,child]of entries){bytes+=key.length;if(bytes>262144)invalid();visit(child,depth+1);}};visit(value,0);};
const boundedJson=(value:unknown,depth=0):any=>{if(depth>5)invalid();if(value===null||typeof value==='boolean')return value;if(typeof value==='string')return text(value,2000);if(typeof value==='number'&&Number.isFinite(value))return value;if(Array.isArray(value)){if(value.length>100)invalid();return value.map(entry=>boundedJson(entry,depth+1));}const record=object(value),entries=Object.entries(record);if(entries.length>50)invalid();return Object.fromEntries(entries.map(([key,entry])=>[text(key,100),boundedJson(entry,depth+1)]));};
const sourceReferences=(value:unknown)=>{if(value===undefined)return[];const references=Array.isArray(value)&&value.length<=20?value:invalid();return references.map(raw=>{const reference=object(raw);return{authorityClass:oneOf(reference.authorityClass,['DJI_MANUFACTURER','CASA_REGULATORY','SPRAY_COMMAND_WORKFLOW','ORGANISATION_STANDARD']as const),sourceIdentity:text(reference.sourceIdentity,200),sourceLocator:text(reference.sourceLocator,500),sourceOutcome:text(reference.sourceOutcome,1000)};});};
const sections=(value:unknown)=>{
  const list=Array.isArray(value)?value:invalid();if(list.length>100)invalid();
  return list.map(raw=>{const section=object(raw),items=Array.isArray(section.items)?section.items:invalid();if(items.length>300)invalid();return{id:text(section.id,100),title:text(section.title,300),items:items.map(rawItem=>{const item=object(rawItem),responseType=oneOf(item.responseType,['CHECK','PASS_DEFECT_NA','YES_NO_NA','NUMERIC','TEXT','SELECTION']as const),required=item.required!==false,rawOptions=item.options===undefined?[]:item.options,options=Array.isArray(rawOptions)&&rawOptions.length<=50?rawOptions.map(x=>text(x,200)):invalid();return{id:text(item.id,100),prompt:text(item.prompt,2000),responseType,type:responseType,required,mandatory:required,allowNA:item.allowNA===true,evidenceRequired:item.evidenceRequired===true,authorityClass:oneOf(item.authorityClass,['DJI_MANUFACTURER','CASA_REGULATORY','SPRAY_COMMAND_WORKFLOW','ORGANISATION_STANDARD']as const),sourceItemId:item.sourceItemId===null||item.sourceItemId===undefined?null:text(item.sourceItemId,100),sourceReferences:sourceReferences(item.sourceReferences),options,conditionalState:item.conditionalState===undefined?null:boundedJson(item.conditionalState)};})};});
};
function applicable(data:unknown){const root=object(data),records=Array.isArray(root.records)?root.records:invalid();if(records.length>500)invalid();return records.map(raw=>{const row=object(raw),template=object(row.template),version=object(row.version),application=object(row.applicability);const templateId=id(template.id),versionId=id(version.id);return{id:templateId,name:text(template.name,300),category:text(template.category,100),authority_scope:text(template.authority_scope,30),applicability:{id:id(application.id),operatingLocationId:application.operating_location_id===null?null:id(application.operating_location_id),lifecycleStage:text(application.lifecycle_stage,50),readinessRequired:application.readiness_required===true},checklist_template_versions:[{id:versionId,template_id:templateId,version_number:positiveInteger(version.version_number),status:text(version.status,30),authority_scope:text(version.authority_scope,30),source_system_template_version_id:version.source_system_template_version_id===null?null:id(version.source_system_template_version_id),sections:sections(version.sections)}]};});}
function missionRecords(data:unknown){const records=Array.isArray(data)?data:invalid();if(records.length>500)invalid();return records.map(raw=>{const row=object(raw);return{id:id(row.id),template_id:id(row.template_id),template_version_id:id(row.template_version_id),status:text(row.status,30),row_version:positiveInteger(row.row_version),responses:object(row.responses),failure_summary:[],completed_at:row.completed_at===null?null:text(row.completed_at,50)};});}
const nullableId=(value:unknown)=>value===null||value===undefined?null:id(value);
function composition(data:unknown){enforceAuthorityBudget(data);const root=object(data),asset=object(root.assetContext),rawEvidence=Array.isArray(root.resolvedEvidence)?root.resolvedEvidence:invalid(),rawModules=Array.isArray(root.modules)?root.modules:invalid(),rawSections=Array.isArray(root.sections)?root.sections:invalid();if(rawEvidence.length>100||rawModules.length>50||rawSections.length>100)invalid();return{schemaVersion:positiveInteger(root.schemaVersion),compositionDigest:digest(root.compositionDigest),profileId:id(root.profileId),profileVersionId:id(root.profileVersionId),profileVersionNumber:positiveInteger(root.profileVersionNumber),authorityScope:oneOf(root.authorityScope,['PLATFORM_SYSTEM','ORGANISATION']as const),sourceSystemProfileId:nullableId(root.sourceSystemProfileId),sourceSystemProfileVersionId:nullableId(root.sourceSystemProfileVersionId),sourceProvenance:boundedJson(root.sourceProvenance),applicability:boundedJson(root.applicability),assetContext:{organisationId:id(asset.organisationId),operatingLocationId:id(asset.operatingLocationId),missionId:nullableId(asset.missionId),aircraftId:nullableId(asset.aircraftId),maintainableAssetId:nullableId(asset.maintainableAssetId),configurationCode:asset.configurationCode===null?null:oneOf(asset.configurationCode,['SPRAY','SPREAD']as const),equipmentKitId:nullableId(asset.equipmentKitId)},resolvedEvidence:rawEvidence.map(raw=>{const row=object(raw);return{code:text(row.code,80),status:oneOf(row.status,['RESOLVED','UNRESOLVED','AMBIGUOUS']as const),recordId:nullableId(row.recordId),value:row.value===undefined?null:boundedJson(row.value)};}),modules:rawModules.map(raw=>{const row=object(raw);return{ordinal:positiveInteger(row.ordinal),stableSectionCode:text(row.stableSectionCode,100),required:row.required===true,templateVersionId:id(row.templateVersionId),templateId:id(row.templateId),versionNumber:positiveInteger(row.versionNumber),authorityScope:oneOf(row.authorityScope,['PLATFORM_SYSTEM','ORGANISATION']as const),sourceProvenance:boundedJson(row.sourceProvenance),applicability:boundedJson(row.applicability===undefined?[]:row.applicability)};}),sections:rawSections.map(raw=>{const row=object(raw),module=object(row.module);return{id:text(row.id,100),title:text(row.title,300),module:{stableSectionCode:text(module.stableSectionCode,100),ordinal:positiveInteger(module.ordinal),templateVersionId:id(module.templateVersionId),templateId:id(module.templateId),versionNumber:positiveInteger(module.versionNumber),authorityScope:oneOf(module.authorityScope,['PLATFORM_SYSTEM','ORGANISATION']as const),sourceSystemTemplateVersionId:nullableId(module.sourceSystemTemplateVersionId),sourceProvenance:boundedJson(module.sourceProvenance)},items:sections([{id:row.id,title:row.title,items:row.items}])[0].items};})};}
function composedExecution(data:unknown){const root=object(data),record=object(root.record),decodedComposition=composition(root.composition),frozen=composition(record.frozen_composition_snapshot);if(frozen.compositionDigest!==decodedComposition.compositionDigest||frozen.profileVersionId!==decodedComposition.profileVersionId)invalid();return{record:{id:id(record.id),organisation_id:id(record.organisation_id),operating_location_id:id(record.operating_location_id),mission_id:nullableId(record.mission_id),template_id:id(record.template_id),template_version_id:id(record.template_version_id),lifecycle_stage:oneOf(record.lifecycle_stage,['PRE_FLIGHT','POST_FLIGHT','MAINTENANCE','GENERAL']as const),completing_personnel_id:id(record.completing_personnel_id),status:oneOf(record.status,['DRAFT']as const),row_version:positiveInteger(record.row_version),aircraft_id:nullableId(record.aircraft_id),maintainable_asset_id:nullableId(record.maintainable_asset_id),composition_profile_version_id:id(record.composition_profile_version_id),frozen_composition_snapshot:frozen,created_at:text(record.created_at,50)},composition:decodedComposition};}
const publicationModules=(value:unknown)=>{const list=Array.isArray(value)&&value.length<=50?value:invalid();return list.map(raw=>{const row=object(raw);return{ordinal:positiveInteger(row.ordinal),templateVersionId:id(row.templateVersionId),stableSectionCode:text(row.stableSectionCode,100),required:typeof row.required==='boolean'?row.required:invalid()};});};
function compositionLibrary(data:unknown){enforceAuthorityBudget(data);const root=object(data),records=Array.isArray(root.records)&&root.records.length<=100?root.records:invalid();return records.map(raw=>{const row=object(raw);return{profileId:id(row.profileId),profileVersionId:id(row.profileVersionId),stableCode:text(row.stableCode,100),name:text(row.name,300),lifecycleStage:oneOf(row.lifecycleStage,['PRE_FLIGHT','POST_FLIGHT','MAINTENANCE','GENERAL']as const),versionNumber:positiveInteger(row.versionNumber),compositionDigest:digest(row.compositionDigest),sourceSystemProfileId:nullableId(row.sourceSystemProfileId),sourceSystemProfileVersionId:nullableId(row.sourceSystemProfileVersionId),proposedModules:publicationModules(row.proposedModules),updateAvailable:row.updateAvailable===true};});}
function adoptedComposition(data:unknown){enforceAuthorityBudget(data);const root=object(data),row=object(root.record);return{record:{profileId:id(row.profileId),profileVersionId:id(row.profileVersionId),sourceSystemProfileVersionId:id(row.sourceSystemProfileVersionId),sourceCompositionDigest:digest(row.sourceCompositionDigest),proposedModules:publicationModules(row.proposedModules),status:oneOf(row.status,['DRAFT']as const),rowVersion:positiveInteger(row.rowVersion)}};}
const asDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});
async function call(fetcher:Fetcher,action:string,init:RequestInit={}){const r=await fetcher(`/api/v1/checklists?action=${action}`,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...init});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error('Checklist request failed.');return p.data;}
const query=(scope:ChecklistScope)=>{const q=new URLSearchParams({operatingLocationId:scope.operatingLocationId,lifecycleStage:scope.lifecycleStage});for(const[k,v]of Object.entries(scope))if(k!=='operatingLocationId'&&k!=='lifecycleStage'&&v)q.set(k,String(v));return q.toString();};
export const createChecklistsApi=(fetcher:Fetcher=fetch)=>({
 templates:async(scope:ChecklistScope)=>applicable(await call(fetcher,`templates&${query(scope)}`)),
 compositionLibrary:async()=>compositionLibrary(await call(fetcher,'composition-library')),
 adoptSystemComposition:async(body:any)=>adoptedComposition(await call(fetcher,'composition-adopt',{method:'POST',body:JSON.stringify(body)})),
 previewComposition:async(profileVersionId:string,scope:ChecklistScope)=>composition(await call(fetcher,`composition-preview&profileVersionId=${encodeURIComponent(profileVersionId)}&${query(scope)}`)),
 startComposition:async(body:any)=>composedExecution(await call(fetcher,'composition-start',{method:'POST',body:JSON.stringify(body)})),
 createTemplate:(body:any)=>call(fetcher,'template',{method:'POST',body:JSON.stringify({operation:'CREATE',...body})}),
 publish:(body:any)=>call(fetcher,'publish',{method:'POST',body:JSON.stringify(body)}),
 mission:async(missionId:string)=>missionRecords(await call(fetcher,`mission&missionId=${encodeURIComponent(missionId)}`)),
 readiness:(missionId:string,stage:string)=>call(fetcher,`readiness&missionId=${encodeURIComponent(missionId)}&lifecycleStage=${encodeURIComponent(stage)}`),
 start:(body:any)=>call(fetcher,'start',{method:'POST',body:JSON.stringify(body)}),save:(body:any)=>call(fetcher,'save',{method:'POST',body:JSON.stringify(body)}),submit:(body:any)=>call(fetcher,'submit',{method:'POST',body:JSON.stringify(body)}),
 uploadEvidence:async(executionId:string,itemId:string,evidenceKind:string,file:File)=>call(fetcher,'evidence',{method:'POST',body:JSON.stringify({executionId,itemId,evidenceKind,fileName:file.name,sizeBytes:file.size,dataUrl:await asDataUrl(file)})}),
 correctiveAction:(body:any)=>call(fetcher,'corrective-action',{method:'POST',body:JSON.stringify(body)})
});
