import React from 'react';
import { PERSISTENCE_KEYS, readSharedValue, writeSharedValue } from '../services/persistence';
import { MaintenanceAsset, MaintenanceRecord, MaintenanceRecordInput, MaintenanceSchedule, MaintenanceScheduleInput, MaintenanceStore, MaintenanceWorkflowStatus } from '../types/maintenance';
import { useAuth } from './AuthContext';
import { useAircraft } from './AircraftContext';
import { useWorkPacks } from './WorkPackContext';

const EMPTY:MaintenanceStore={assets:[],schedules:[],records:[],auditEvents:[]};
const id=(prefix:string)=>`${prefix}-${typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
interface Value extends MaintenanceStore{isLoading:boolean;loadError?:string;saveError?:string;upsertAsset:(asset:MaintenanceAsset)=>void;addSchedule:(input:MaintenanceScheduleInput)=>Promise<string>;submitRecord:(input:MaintenanceRecordInput)=>Promise<string>;transitionRecord:(recordId:string,status:MaintenanceWorkflowStatus,certification?:MaintenanceRecord['certification'])=>Promise<void>;amendRecord:(recordId:string,reason:string,changes:Partial<MaintenanceRecordInput>)=>Promise<string>;}
const Context=React.createContext<Value|undefined>(undefined);

export function MaintenanceProvider({children}:{children:React.ReactNode}){
 const {user}=useAuth(); const {aircraft,equipmentKits}=useAircraft(); const {assets:deploymentAssets}=useWorkPacks();
 const [store,setStore]=React.useState<MaintenanceStore>(EMPTY);const [isLoading,setLoading]=React.useState(true);const [loadError,setLoadError]=React.useState<string>();const [saveError,setSaveError]=React.useState<string>();const loaded=React.useRef(false);
 React.useEffect(()=>{let active=true;readSharedValue<MaintenanceStore>(PERSISTENCE_KEYS.maintenance,EMPTY).then(v=>{if(active)setStore(v&&Array.isArray(v.records)?v:EMPTY);}).catch(e=>active&&setLoadError(e instanceof Error?e.message:'Unable to load maintenance records.')).finally(()=>{if(active){loaded.current=true;setLoading(false);}});return()=>{active=false};},[]);
 React.useEffect(()=>{if(!loaded.current)return;const timer=window.setTimeout(()=>writeSharedValue(PERSISTENCE_KEYS.maintenance,store).then(()=>setSaveError(undefined)).catch(e=>setSaveError(e instanceof Error?e.message:'Unable to save maintenance records.')),50);return()=>window.clearTimeout(timer);},[store]);
 const tenantId=user?.tenantId||user?.id||'local';const now=()=>new Date().toISOString();
 const upsertAsset=React.useCallback((asset:MaintenanceAsset)=>setStore(s=>({...s,assets:[...s.assets.filter(a=>a.id!==asset.id),asset]})),[]);
 React.useEffect(()=>{if(!loaded.current)return;setStore(s=>{const existing=new Map(s.assets.map(a=>[a.sourceId,a]));const stamp=now();const synced:MaintenanceAsset[]=[...aircraft.map(a=>({...existing.get(a.id),id:existing.get(a.id)?.id||`aircraft-${a.id}`,tenantId,sourceId:a.id,scope:'rpas' as const,assetClass:'aircraft' as const,name:a.registration,manufacturer:a.manufacturer,model:a.model,serialNumber:a.serialNumber,uniqueMark:a.registration,maximumGrossWeightKg:a.mtow,status:a.status==='operational'?'serviceable' as const:a.status==='retired'?'retired' as const:'maintenance' as const,readings:{...(existing.get(a.id)?.readings||{}),flightHours:a.maintenanceDates.totalFlightHours},createdAt:existing.get(a.id)?.createdAt||stamp,updatedAt:stamp})),...equipmentKits.map(k=>({...existing.get(k.id),id:existing.get(k.id)?.id||`kit-${k.id}`,tenantId,sourceId:k.id,scope:'rpas' as const,assetClass:'spray-kit' as const,name:k.name,status:k.operationalData.status==='available'?'serviceable' as const:'maintenance' as const,readings:{...(existing.get(k.id)?.readings||{}),operatingHours:k.operationalData.totalOperatingHours},createdAt:existing.get(k.id)?.createdAt||stamp,updatedAt:stamp})),...deploymentAssets.map(a=>({...existing.get(a.id),id:existing.get(a.id)?.id||`fleet-${a.id}`,tenantId,sourceId:a.id,scope:'fleet' as const,assetClass:a.assetType as MaintenanceAsset['assetClass'],name:a.name,manufacturer:a.manufacturer,model:a.model,serialNumber:a.vin,status:a.status==='available'?'serviceable' as const:a.status==='retired'?'retired' as const:'maintenance' as const,readings:{...(existing.get(a.id)?.readings||{}),kilometres:a.meter?.odometerKm,operatingHours:a.meter?.operatingHours??a.meter?.engineHours},createdAt:existing.get(a.id)?.createdAt||stamp,updatedAt:stamp}))];const sourceIds=new Set(synced.map(a=>a.sourceId));return{...s,assets:[...s.assets.filter(a=>!sourceIds.has(a.sourceId)),...synced]};});},[aircraft,equipmentKits,deploymentAssets,tenantId,isLoading]);
 const audit=(assetId:string,recordId:string|undefined,action:MaintenanceStore['auditEvents'][number]['action'],detail:string)=>({id:id('audit'),tenantId,assetId,recordId,action,actorId:user?.id||'unknown',actorName:user?.name||'Unknown',occurredAt:now(),detail});
 const addSchedule=async(input:MaintenanceScheduleInput)=>{const stamp=now(),schedule:MaintenanceSchedule={...input,id:id('schedule'),tenantId,createdAt:stamp,updatedAt:stamp};setStore(s=>({...s,schedules:[...s.schedules,schedule],auditEvents:[audit(input.assetId,undefined,'schedule-created',input.title),...s.auditEvents]}));return schedule.id;};
 const submitRecord=async(input:MaintenanceRecordInput)=>{const record:MaintenanceRecord={...input,id:id('record'),tenantId,createdAt:now(),createdBy:user?.id||'unknown',createdByName:user?.name||'Unknown',createdByRole:user?.role||'unknown'};setStore(s=>({...s,records:[record,...s.records],assets:s.assets.map(a=>a.id===record.assetId&&record.resultingServiceability==='unserviceable'?{...a,status:'unserviceable',updatedAt:now()}:a),auditEvents:[audit(record.assetId,record.id,'record-created',record.title),...s.auditEvents]}));return record.id;};
 const transitionRecord=async(recordId:string,status:MaintenanceWorkflowStatus,certification?:MaintenanceRecord['certification'])=>{if(status==='serviceable'&&(user?.role!=='admin'||!certification))throw new Error('An authorised company administrator must certify return to service.');setStore(s=>{const record=s.records.find(r=>r.id===recordId);if(!record)return s;return{...s,records:s.records.map(r=>r.id===recordId?{...r,status,certification}:r),assets:s.assets.map(a=>a.id===record.assetId&&status==='serviceable'?{...a,status:'serviceable',updatedAt:now()}:a),auditEvents:[audit(record.assetId,recordId,'status-changed',status),...s.auditEvents]};});};
 const amendRecord=async(recordId:string,reason:string,changes:Partial<MaintenanceRecordInput>)=>{const original=store.records.find(r=>r.id===recordId);if(!original)throw new Error('Maintenance record not found.');const {id:_id,tenantId:_tenant,createdAt:_created,createdBy:_by,createdByName:_byName,createdByRole:_byRole,...originalInput}=original;return submitRecord({...originalInput,...changes,amendmentOf:recordId,amendmentReason:reason});};
 return <Context.Provider value={{...store,isLoading,loadError,saveError,upsertAsset,addSchedule,submitRecord,transitionRecord,amendRecord}}>{children}</Context.Provider>;
}
export function useMaintenance(){const value=React.useContext(Context);if(!value)throw new Error('useMaintenance must be used within MaintenanceProvider');return value;}
