import { expect, test } from '@playwright/test';
const user='11111111-1111-4111-8111-111111111111',org='22222222-2222-4222-8222-222222222222',base='33333333-3333-4333-8333-333333333333',actual='44444444-4444-4444-8444-444444444444';
test('renders only the development-gated authoritative Financial list responsively',async({page})=>{
  await page.route('**/api/v1/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:[],pagination:{page:1,pageSize:100,total:0}})}));
  await page.route('**/api/v1/financial-actuals*',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:{schemaVersion:'FINANCIAL_ACTUAL_LIST_V1',rows:[{id:actual,reference:'FA-000001',operatingLocation:{id:base,label:'Fly The Farm Base'},client:{id:user,label:'Controlled Client'},job:{id:org,label:'JOB-001'},mission:null,lifecycle:'FINAL',correctionDraftInProgress:true,activeDraft:{id:user,revisionNumber:2,rowVersion:1},currentFinalRevisionNumber:1,finalCalculation:{revenue:'300.0000',totalCost:'1.0000',grossProfit:'299.0000',grossMarginPercentage:'99.6667'},sourceDrift:'UNCHANGED',archived:false}],nextCursor:null}})}));
  await page.route('**/api/v1/session',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:{user:{id:user},organisation:{id:org,name:'Fly The Farm'},roles:['organisation_admin'],permissions:['financial_actuals.read'],operatingLocationIds:[base]}})}));
  await page.route('**/api/auth',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({user:{id:user,email:'founder@example.test',name:'Founder',role:'admin',identityPlane:'organisation',permissions:['financial_actuals.read','financial_actuals.export'],entitlements:[]}})}));
  await page.goto('/financials');
  await expect(page.getByRole('heading',{name:'Financial Actuals'})).toBeVisible();
  await expect(page.getByText('FA-000001')).toBeVisible();
  await expect(page.getByText('$299.00')).toBeVisible();
  await expect(page.getByText('Correction in progress',{exact:true})).toBeVisible();
  await expect(page.getByText(/Current FINAL remains authoritative/)).toBeVisible();
  await expect(page.locator('body')).not.toHaveCSS('overflow-x','scroll');
});

test('exports exact current and historical FINAL revisions without browser calculation',async({page})=>{
  const revision1='55555555-5555-4555-8555-555555555551',revision2='55555555-5555-4555-8555-555555555552';
  const frozen=(id:string,revisionNumber:number,revenue:string)=>({id,revisionNumber,status:'FINAL',rowVersion:revisionNumber+2,currencyCode:'AUD',formulaVersion:'FINANCIAL_ACTUAL_V1',startDate:'2026-08-20',endDate:'2026-08-21',input:{formulaVersion:'FINANCIAL_ACTUAL_V1',currencyCode:'AUD',revenue:{mode:'HOURLY',hourlyRate:'100.000000'},workEntries:[],costLines:[],workEntryEvidence:[],costLineEvidence:[]},provenance:{rows:[]},calculation:{formulaVersion:'FINANCIAL_ACTUAL_V1',currencyCode:'AUD',operationalDays:1,totalHours:'3.0000',revenue,lineAmounts:{},categoryTotals:{LABOUR:'0.0000',PRODUCT:'0.0000',TRAVEL:'0.0000',AIRCRAFT_EQUIPMENT:'0.0000',OTHER:'0.0000'},totalCost:'0.0000',grossProfit:revenue,grossMarginPercentage:'100.0000',effectiveHourlyRevenue:'100.0000'},sourceManifest:{schemaVersion:'FINANCIAL_ACTUAL_SOURCE_MANIFEST_V1',financialActualId:actual,revisionId:id,formulaVersion:'FINANCIAL_ACTUAL_V1',revenueMode:'HOURLY',workEntryIds:[],costLineIds:[],provenanceIds:[]},inputDigest:(revisionNumber===1?'a':'b').repeat(64),finalisedAt:'2026-08-22T01:00:00.000Z',finalisedByInternalUserId:user});
  const detail={schemaVersion:'FINANCIAL_ACTUAL_AUTHORITY_DETAIL_V1',record:{id:actual,reference:'FA-000184',organisationId:org,operatingLocationId:base,clientId:user,propertyId:org,fieldId:base,jobId:user,missionId:null,rowVersion:4,archivedAt:null,currentFinalRevisionId:revision2,activeDraftRevisionId:null},hierarchy:{operatingLocation:{id:base,label:'Fly The Farm Base'},client:{id:user,label:'Controlled Client'},property:{id:org,label:'Controlled Property'},field:{id:base,label:'Controlled Field'},job:{id:user,label:'JOB-184'},mission:null},draft:null,final:frozen(revision2,2,'400.0000'),sourceDrift:{status:'NO_ACCEPTED_OPERATIONAL_SOURCE'}};
  const history={schemaVersion:'FINANCIAL_ACTUAL_REVISION_HISTORY_V1',financialActualId:actual,reference:'FA-000184',archivedAt:null,currentFinalRevisionId:revision2,activeDraftRevisionId:null,rows:[{id:revision2,revisionNumber:2,status:'FINAL',rowVersion:4,predecessorRevisionId:revision1,correctionReason:'Correct cost',formulaVersion:'FINANCIAL_ACTUAL_V1',finalisedAt:'2026-08-22T01:00:00.000Z',finalisedByInternalUserId:user,current:true,activeDraft:false},{id:revision1,revisionNumber:1,status:'FINAL',rowVersion:3,predecessorRevisionId:null,correctionReason:null,formulaVersion:'FINANCIAL_ACTUAL_V1',finalisedAt:'2026-08-21T01:00:00.000Z',finalisedByInternalUserId:user,current:false,activeDraft:false}],nextBeforeRevisionNumber:null};
  const requested:string[]=[];
  await page.route('**/api/v1/financial-actuals*',async route=>{const url=new URL(route.request().url()),action=url.searchParams.get('action');if(action==='read')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:detail})});if(action==='revision-history')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:history})});if(action==='historical-revision')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:{schemaVersion:'FINANCIAL_ACTUAL_HISTORICAL_REVISION_V1',financialActualId:actual,reference:'FA-000184',archivedAt:null,current:false,revision:{...frozen(revision1,1,'300.0000'),predecessorRevisionId:null,correctionReason:null}}})});if(action==='export'){const body=JSON.parse(route.request().postData()||'{}');requested.push(body.revisionId);return route.fulfill({status:200,headers:{'content-type':'application/pdf','content-disposition':`attachment; filename="FA-000184-revision-${body.revisionId===revision1?1:2}.pdf"`},body:Buffer.from('%PDF exact revision')})}return route.fulfill({status:400,contentType:'application/json',body:'{}'})});
  await page.route('**/api/v1/session',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:{user:{id:user},organisation:{id:org,name:'Fly The Farm'},roles:['organisation_admin'],permissions:['financial_actuals.read','financial_actuals.export'],operatingLocationIds:[base]}})}));
  await page.route('**/api/auth',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({user:{id:user,email:'founder@example.test',name:'Founder',role:'admin',identityPlane:'organisation',permissions:['financial_actuals.read','financial_actuals.export'],entitlements:[]}})}));
  await page.goto(`/financials/${actual}`);await expect(page.getByRole('heading',{name:'Frozen FINAL result'})).toBeVisible();
  const currentDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export current FINAL'}).click();expect((await currentDownload).suggestedFilename()).toBe('FA-000184-revision-2.pdf');
  await page.getByRole('button',{name:'Revision 1'}).click();await expect(page.getByText('Historical frozen authority')).toBeVisible();const historicalDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export revision 1'}).click();expect((await historicalDownload).suggestedFilename()).toBe('FA-000184-revision-1.pdf');expect(requested).toEqual([revision2,revision1]);await expect(page.locator('body')).not.toHaveCSS('overflow-x','scroll');
});
