export type Configuration='SPRAY'|'SPREAD';
export type Resolution='ENABLED'|'DISABLED'|'UNKNOWN';
export type ChecklistContext={aircraft:{id:string;manufacturer:string;model:string};mission:{id:string}|null;operatingLocation:{id:string}|null;fleetReady:boolean|null;configuration:Configuration|null;rtk:Resolution;compassCalibrationRequired:boolean|null;flowCalibrationRequired:boolean|null};
export type ChecklistItem={id:string;label:string;outcome:string;provenance:'DJI_MANUFACTURER'|'SPRAY_COMMAND_WORKFLOW'|'ORGANISATION_STANDARD';when?:'SPRAY'|'SPREAD'|'COMPASS_REQUIRED'|'FLOW_REQUIRED'};
type Profile={id:string;version:number;model:string;manufacturer:string;items:ChecklistItem[];takeOffConfirmation:ChecklistItem[];sourceProvenance:{kind:'DEVELOPMENT_FIXTURE';published:false}};

const item=(outcome:string,label:string,when?:ChecklistItem['when'],provenance:ChecklistItem['provenance']='DJI_MANUFACTURER'):ChecklistItem=>({id:outcome.toLowerCase().replaceAll('_','-'),label,outcome,provenance,when});
const common=[
 item('AIRCRAFT_PHYSICAL_CONDITION','Inspect aircraft structure, arms and fasteners'),item('PROPULSION_CONDITION','Inspect motors and propellers'),item('BATTERY_POWER_CONDITION','Inspect batteries, power connections and locking'),item('LANDING_GEAR_CONDITION','Inspect landing gear'),item('PAYLOAD_SECURITY','Confirm installed payload is secure'),item('CONTROL_LINK','Confirm controller link and controls'),item('GNSS_STATUS','Assess current positioning status'),item('WEATHER_CURRENT','Assess current weather and wind',undefined,'SPRAY_COMMAND_WORKFLOW'),item('SITE_CURRENT','Inspect current operating area and hazards',undefined,'SPRAY_COMMAND_WORKFLOW'),item('PEOPLE_CLEAR','Confirm people are clear',undefined,'SPRAY_COMMAND_WORKFLOW'),item('OBSTACLES_CLEAR','Confirm obstacles and exclusion zones',undefined,'SPRAY_COMMAND_WORKFLOW'),item('EMERGENCY_PLAN','Confirm current emergency response readiness',undefined,'ORGANISATION_STANDARD'),item('HOME_POINT','Confirm appropriate home point',undefined,'SPRAY_COMMAND_WORKFLOW'),item('ROUTE_CURRENT','Review route against current conditions',undefined,'SPRAY_COMMAND_WORKFLOW'),
];
const spray=[item('SPRAY_SYSTEM_CONDITION','Inspect spray tank, hoses and fittings','SPRAY'),item('PUMP_NOZZLE_CONDITION','Inspect pumps, nozzles and atomisers','SPRAY'),item('SPRAY_PAYLOAD_SECURE','Confirm spray payload is secure','SPRAY'),item('SPRAY_LEAK_CHECK','Check for leaks','SPRAY')];
const spread=[item('SPREAD_SYSTEM_CONDITION','Inspect spreader body and drive','SPREAD'),item('SPREADER_DISC_CONDITION','Inspect spreading disc','SPREAD'),item('SPREAD_PAYLOAD_SECURE','Confirm spread payload is secure','SPREAD'),item('SPREAD_GATE_MOVEMENT','Confirm gate movement','SPREAD'),item('SPREAD_CLEARANCE','Confirm spread system clearance','SPREAD')];
const calibration=[item('COMPASS_CALIBRATION','Perform compass calibration','COMPASS_REQUIRED'),item('FLOW_CALIBRATION','Perform flow calibration','FLOW_REQUIRED')];
const make=(model:string,extra:ChecklistItem[]=[]):Profile=>({id:`dev-dji-${model.toLowerCase()}-preflight`,version:1,model,manufacturer:'DJI',items:[...common,...spray,...spread,...extra,...calibration],takeOffConfirmation:model==='T100'?[item('FLIGHT_CONTROL_RESPONSE','Confirm flight-control response during take-off')]:[],sourceProvenance:{kind:'DEVELOPMENT_FIXTURE',published:false}});
export const developmentProfiles={T100_PRE_FLIGHT:make('T100',[item('LIDAR_CONDITION','Inspect LiDAR sensors and keep them unobstructed')]),T50_PRE_FLIGHT:make('T50'),T25P_PRE_FLIGHT:make('T25P'),T25_PRE_FLIGHT:make('T25')} as const;

export function composeDevelopmentChecklist(profile:Profile,context:ChecklistContext){
 const unresolved:string[]=[];
 if(!context.mission)unresolved.push('MISSION');if(!context.operatingLocation)unresolved.push('BASE');if(context.fleetReady===null)unresolved.push('FLEET_READINESS');if(!context.configuration)unresolved.push('CONFIGURATION');if(context.rtk==='UNKNOWN')unresolved.push('RTK_CONFIGURATION');if(context.compassCalibrationRequired===null)unresolved.push('COMPASS_CALIBRATION_REQUIREMENT');if(context.flowCalibrationRequired===null)unresolved.push('FLOW_CALIBRATION_REQUIREMENT');
 if(context.aircraft.manufacturer.toUpperCase()!==profile.manufacturer||context.aircraft.model.toUpperCase()!==profile.model)return{status:'NOT_APPLICABLE' as const,unresolved:[],operatorItems:[],takeOffConfirmation:[],resolvedEvidence:[]};
 const applicable=(candidate:ChecklistItem)=>!candidate.when||candidate.when===context.configuration||(candidate.when==='COMPASS_REQUIRED'&&context.compassCalibrationRequired===true)||(candidate.when==='FLOW_REQUIRED'&&context.flowCalibrationRequired===true);
 const resolvedEvidence=[{code:'MISSION',recordId:context.mission?.id},{code:'AIRCRAFT',recordId:context.aircraft.id},{code:'BASE',recordId:context.operatingLocation?.id},{code:'FLEET_READINESS',value:context.fleetReady},{code:'RTK_CONFIGURATION',value:context.rtk},{code:'PAYLOAD_CONFIGURATION',value:context.configuration}];
 return{status:unresolved.length?'REVIEW_REQUIRED' as const:'READY' as const,unresolved,operatorItems:profile.items.filter(applicable),takeOffConfirmation:profile.takeOffConfirmation,resolvedEvidence,profile:{id:profile.id,version:profile.version,sourceProvenance:profile.sourceProvenance}};
}

export function getOrganisationUpdateState(inherited:{sourceVersion:number;frozenSections:unknown[]},latestSourceVersion:number){return{updateAvailable:latestSourceVersion>inherited.sourceVersion,currentSourceVersion:inherited.sourceVersion,availableSourceVersion:latestSourceVersion};}
