const {createCustomerAcceptanceHandler,createCustomerAcceptancePublicHandler}=require('../../server/operational-api');
const org='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',location='33333333-3333-4333-8333-333333333333',mission='44444444-4444-4444-8444-444444444444';
const response=()=>({statusCode:200,setHeader(){},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}});
const request=(method,body={},query={})=>({method,body,query:{missionId:mission,...query},headers:{origin:'http://localhost:3000',host:'localhost:3000','user-agent':'test'}});
const context=permissions=>({organisation:{id:org},internalUser:{id:actor},permissions,operatingLocationIds:[location]});
const repository={get:jest.fn(),readCustomerAcceptance:jest.fn(),createCustomerAcceptance:jest.fn(),issueCustomerAcceptanceLink:jest.fn(),revokeCustomerAcceptanceLink:jest.fn(),resolveCustomerAcceptanceLink:jest.fn(),stageCustomerAcceptanceFile:jest.fn(),submitCustomerAcceptanceLink:jest.fn()};
beforeEach(()=>{jest.clearAllMocks();repository.get.mockResolvedValue({id:mission,operating_location_id:location});repository.readCustomerAcceptance.mockResolvedValue({records:[]});repository.createCustomerAcceptance.mockResolvedValue({record:{id:'a'}});repository.issueCustomerAcceptanceLink.mockResolvedValue({record:{id:'l'},token:'secret'});repository.resolveCustomerAcceptanceLink.mockResolvedValue({missionReference:'M-1'});repository.stageCustomerAcceptanceFile.mockResolvedValue({record:{internal_file_id:'f'}});repository.submitCustomerAcceptanceLink.mockResolvedValue({record:{id:'a'}});});

test('records operator evidence and issues a secure link through permissions',async()=>{const handler=createCustomerAcceptanceHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.customer_acceptance.record','mission.customer_acceptance.link.issue']))});let res=response();await handler(request('POST',{stateCode:'ACCEPTED',methodCode:'PHONE',customerContactName:'Customer',acknowledgedAt:new Date().toISOString(),comments:'Accepted by phone.'},{action:'record'}),res);expect(res.statusCode).toBe(201);res=response();await handler(request('POST',{contactName:'Customer',expiresInHours:48},{action:'link-issue'}),res);expect(res.statusCode).toBe(201);expect(res.body.data.token).toBe('secret');});

test('public handler exposes safe summary and requires consent plus signature',async()=>{const handler=createCustomerAcceptancePublicHandler({repository});let res=response();await handler({method:'GET',query:{token:'secret'},headers:{'user-agent':'test'}},res);expect(res.body.data).toEqual(expect.objectContaining({missionReference:'M-1'}));expect(res.body.data).not.toHaveProperty('organisationId');expect(res.body.data).not.toHaveProperty('missionId');res=response();await handler({method:'POST',query:{token:'secret',action:'submit'},headers:{origin:'http://localhost:3000',host:'localhost:3000','user-agent':'test'},body:{stateCode:'ACCEPTED',customerContactName:'Customer',consent:true,consentDeclaration:'I confirm this acknowledgement.',signatureFileId:'55555555-5555-4555-8555-555555555555'}},res);expect(res.statusCode).toBe(201);});

test('rejects unsupported actions and missing permissions',async()=>{const handler=createCustomerAcceptanceHandler({repository,resolveContext:jest.fn().mockResolvedValue(context([]))});let res=response();await handler(request('GET'),res);expect(res.statusCode).toBe(403);res=response();await handler(request('POST',{}, {action:'delete'}),res);expect(res.body.error.code).toBe('UNSUPPORTED_ACTION');});
