const {createFinancialActualsHandler}=require('../../server/financial-actuals-api');
const actual='11111111-1111-4111-8111-111111111111',revision='22222222-2222-4222-8222-222222222222';
const context=permissions=>({organisation:{id:'33333333-3333-4333-8333-333333333333'},internalUser:{id:'44444444-4444-4444-8444-444444444444'},permissions});
const request=()=>({method:'POST',query:{action:'export'},body:{actualId:actual,revisionId:revision},headers:{origin:'https://example.test',host:'example.test','x-forwarded-proto':'https'}});
const response=()=>{const r={headers:{},statusCode:200,body:null,ended:null};r.setHeader=(k,v)=>r.headers[k]=v;r.status=n=>(r.statusCode=n,r);r.json=v=>(r.body=v,r);r.end=v=>(r.ended=v,r);return r};
const authority={final:{id:revision}};
const model={reportVersion:'FINANCIAL_ACTUAL_PNL_V1',generatedAt:'2026-08-22T02:00:00.000Z',financialActual:{id:actual,reference:'FA-000184'},revision:{id:revision,revisionNumber:1,inputDigest:'a'.repeat(64),formulaVersion:'FINANCIAL_ACTUAL_V1'}};
function repository(){return{read:jest.fn().mockResolvedValue(authority),historicalRevision:jest.fn(),recordExportEvidence:jest.fn().mockResolvedValue({schemaVersion:'FINANCIAL_ACTUAL_EXPORT_EVIDENCE_V1',financialActualId:actual,revisionId:revision,revisionNumber:1,inputDigest:'a'.repeat(64),formulaVersion:'FINANCIAL_ACTUAL_V1',reportVersion:'FINANCIAL_ACTUAL_PNL_V1',generatedAt:model.generatedAt})}}
test.each([['read only',['financial_actuals.read']],['export only',['financial_actuals.export']],['neither',[]]])('requires both permissions: %s',async(_name,permissions)=>{const repo=repository(),handler=createFinancialActualsHandler({repository:repo,resolveContext:async()=>context(permissions),decodeExport:jest.fn(),renderExport:jest.fn()}),res=response();await handler(request(),res);expect(res.statusCode).toBe(403);expect(repo.read).not.toHaveBeenCalled();expect(res.ended).toBeNull()});
test('releases one exact current PDF only after bounded evidence succeeds',async()=>{const repo=repository(),order=[],handler=createFinancialActualsHandler({repository:repo,resolveContext:async()=>context(['financial_actuals.read','financial_actuals.export']),decodeExport:()=>{order.push('decode');return model},renderExport:()=>{order.push('render');return Buffer.from('%PDF exact')}});repo.read.mockImplementation(async()=>{order.push('read');return authority});repo.recordExportEvidence.mockImplementation(async(_context,values)=>{order.push('evidence');return{schemaVersion:'FINANCIAL_ACTUAL_EXPORT_EVIDENCE_V1',financialActualId:actual,revisionId:revision,revisionNumber:1,inputDigest:'a'.repeat(64),formulaVersion:'FINANCIAL_ACTUAL_V1',reportVersion:'FINANCIAL_ACTUAL_PNL_V1',generatedAt:values.generatedAt}});const res=response();await handler(request(),res);expect(order).toEqual(['read','decode','render','evidence']);expect(res.statusCode).toBe(200);expect(res.headers['Content-Type']).toBe('application/pdf');expect(res.ended.toString()).toBe('%PDF exact');expect(repo.historicalRevision).not.toHaveBeenCalled()});
test('reads exact historical revision and never substitutes current',async()=>{const repo=repository(),other='55555555-5555-4555-8555-555555555555';repo.read.mockResolvedValue({final:{id:other}});repo.historicalRevision.mockResolvedValue({revision:{id:revision}});const handler=createFinancialActualsHandler({repository:repo,resolveContext:async()=>context(['financial_actuals.read','financial_actuals.export']),decodeExport:input=>{expect(input.historical.revision.id).toBe(revision);return model},renderExport:()=>Buffer.from('%PDF historical')});const res=response();await handler(request(),res);expect(repo.historicalRevision).toHaveBeenCalledWith(expect.anything(),{actualId:actual,revisionId:revision});expect(res.statusCode).toBe(200)});
test('discards rendered bytes when export evidence fails',async()=>{const repo=repository();repo.recordExportEvidence.mockRejectedValue(Object.assign(new Error('secret'),{statusCode:500}));const handler=createFinancialActualsHandler({repository:repo,resolveContext:async()=>context(['financial_actuals.read','financial_actuals.export']),decodeExport:()=>model,renderExport:()=>Buffer.from('%PDF private')});const res=response();await handler(request(),res);expect(res.statusCode).toBe(500);expect(res.ended).toBeNull();expect(JSON.stringify(res.body)).not.toContain('secret')});
