const { createMissionChemicalsHandler } = require('../../server/operational-api');
const org='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',location='33333333-3333-4333-8333-333333333333',mission='44444444-4444-4444-8444-444444444444';
const response=()=>({statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;},end(){return this;}});
const req=(method,body={},query={})=>({method,body,query:{missionId:mission,...query},headers:{origin:'http://localhost:3000',host:'localhost:3000'}});
const context=(permissions)=>({organisation:{id:org},internalUser:{id:actor},permissions,operatingLocationIds:[location]});
const repository={get:jest.fn(),readMissionChemicalPlan:jest.fn(),saveMissionChemicalPlan:jest.fn(),searchChemicalIntelligence:jest.fn()};
beforeEach(()=>{repository.get.mockResolvedValue({id:mission,organisation_id:org,operating_location_id:location});repository.readMissionChemicalPlan.mockResolvedValue([{version_number:1,lines:[]}]);repository.saveMissionChemicalPlan.mockResolvedValue({record:{version_number:2,lines:[]},unmatchedReviewCreated:true});repository.searchChemicalIntelligence.mockResolvedValue([]);});

test('reads and saves versioned Mission chemicals with non-blocking review notice',async()=>{const handler=createMissionChemicalsHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.chemicals.read','mission.chemicals.plan']))});let res=response();await handler(req('GET'),res);expect(res.statusCode).toBe(200);res=response();await handler(req('POST',{expectedVersion:1,treatmentAreaHa:10,applicationVolumeLHa:40,tankCapacityL:40,lines:[{productName:'Unknown 500',matchState:'UNMATCHED',rate:2,rateUnit:'L_HA'}]}),res);expect(res.statusCode).toBe(201);expect(res.body.meta.unmatchedReviewCreated).toBe(true);});
test('requires permissions and returns concurrency conflict',async()=>{let handler=createMissionChemicalsHandler({repository,resolveContext:jest.fn().mockResolvedValue(context([]))}),res=response();await handler(req('GET'),res);expect(res.statusCode).toBe(403);repository.saveMissionChemicalPlan.mockResolvedValueOnce({conflict:true,currentVersion:3});handler=createMissionChemicalsHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.chemicals.plan']))});res=response();await handler(req('POST',{expectedVersion:1,treatmentAreaHa:10,applicationVolumeLHa:40,tankCapacityL:40,lines:[{productName:'Test',matchState:'UNMATCHED',rate:2,rateUnit:'L_HA'}]}),res);expect(res.statusCode).toBe(409);expect(res.body.error.code).toBe('VERSION_CONFLICT');});
test('validates rates and supports intelligence search without a Mission id',async()=>{const handler=createMissionChemicalsHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.chemicals.plan','chemical.register.read']))});let res=response();await handler(req('POST',{expectedVersion:0,treatmentAreaHa:10,applicationVolumeLHa:40,tankCapacityL:40,lines:[{productName:'Test',matchState:'UNMATCHED',rate:0,rateUnit:'L_HA'}]}),res);expect(res.statusCode).toBe(400);res=response();await handler(req('GET',{}, {action:'search',q:'grazon',missionId:undefined}),res);expect(res.statusCode).toBe(200);expect(repository.searchChemicalIntelligence).toHaveBeenCalled();});
