const {createMissionAuthorisationHandler}=require('../../server/operational-api');
const org='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',location='33333333-3333-4333-8333-333333333333',mission='44444444-4444-4444-8444-444444444444';
const response=()=>({statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}});
const request=(method,body={},query={})=>({method,body,query:{missionId:mission,...query},headers:{origin:'http://localhost:3000',host:'localhost:3000'}});
const context=permissions=>({organisation:{id:org},internalUser:{id:actor},permissions,operatingLocationIds:[location]});
const repository={get:jest.fn(),readMissionAuthorisation:jest.fn(),evaluateMissionReadiness:jest.fn(),authoriseMission:jest.fn(),generateMissionPack:jest.fn(),readMissionPack:jest.fn()};
beforeEach(()=>{jest.clearAllMocks();repository.get.mockResolvedValue({id:mission,organisation_id:org,operating_location_id:location});repository.evaluateMissionReadiness.mockResolvedValue({overallState:'READY',ready:true,blockers:[],warnings:[],categories:{}});repository.readMissionAuthorisation.mockResolvedValue(null);repository.authoriseMission.mockResolvedValue({record:{id:'55555555-5555-4555-8555-555555555555',version_number:1,evidence_manifest:{weather:{observed:{revisionId:'66666666-6666-4666-8666-666666666666'}}}}});repository.generateMissionPack.mockResolvedValue({record:{id:'77777777-7777-4777-8777-777777777777',version_number:1,authorisation_revision_id:'55555555-5555-4555-8555-555555555555'}});repository.readMissionPack.mockResolvedValue(null);});

test('reads grouped readiness and current immutable authorisation',async()=>{const handler=createMissionAuthorisationHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.authorisation.read']))});let res=response();await handler(request('GET',{}, {action:'readiness'}),res);expect(res.body.data.ready).toBe(true);expect(repository.evaluateMissionReadiness).toHaveBeenCalledWith(expect.anything(),mission);res=response();await handler(request('GET'),res);expect(res.statusCode).toBe(200);});
test('authorises one exact evidence set with optimistic concurrency',async()=>{const handler=createMissionAuthorisationHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.authorisation.authorise']))});const res=response();await handler(request('POST',{expectedVersion:0,declaration:'Evidence checked and accepted.'},{action:'authorise'}),res);expect(res.statusCode).toBe(201);expect(repository.authoriseMission).toHaveBeenCalledWith(expect.anything(),mission,0,'Evidence checked and accepted.');});
test('blocked readiness and stale writes fail visibly',async()=>{const handler=createMissionAuthorisationHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.authorisation.authorise']))});repository.authoriseMission.mockResolvedValueOnce({readinessBlocked:true,readiness:{ready:false,blockers:[{code:'WEATHER_EXPIRED'}]}});let res=response();await handler(request('POST',{expectedVersion:0,declaration:'Checked.'},{action:'authorise'}),res);expect(res.statusCode).toBe(409);expect(res.body.error.code).toBe('READINESS_BLOCKED');repository.authoriseMission.mockResolvedValueOnce({conflict:true,currentVersion:1});res=response();await handler(request('POST',{expectedVersion:0,declaration:'Checked.'},{action:'authorise'}),res);expect(res.statusCode).toBe(409);expect(res.body.error.code).toBe('VERSION_CONFLICT');});
test('generates and reads a pack only from an authorisation revision',async()=>{const handler=createMissionAuthorisationHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.pack.generate','mission.pack.read']))});let res=response();await handler(request('POST',{authorisationRevisionId:'55555555-5555-4555-8555-555555555555',expectedVersion:0},{action:'generate-pack'}),res);expect(res.statusCode).toBe(201);expect(repository.generateMissionPack).toHaveBeenCalled();res=response();await handler(request('GET',{}, {action:'pack'}),res);expect(res.statusCode).toBe(200);});
test('permission, tenant/location and unsupported actions are enforced',async()=>{let handler=createMissionAuthorisationHandler({repository,resolveContext:jest.fn().mockResolvedValue(context([]))}),res=response();await handler(request('GET'),res);expect(res.statusCode).toBe(403);repository.get.mockResolvedValueOnce(null);handler=createMissionAuthorisationHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.authorisation.read']))});res=response();await handler(request('GET'),res);expect(res.statusCode).toBe(404);res=response();await handler(request('POST',{expectedVersion:0},{action:'delete'}),res);expect(res.body.error.code).toBe('UNSUPPORTED_ACTION');});
