const {createMissionJsaHandler}=require('../../server/operational-api');
const org='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',location='33333333-3333-4333-8333-333333333333',mission='44444444-4444-4444-8444-444444444444',revision='55555555-5555-4555-8555-555555555555';
const response=()=>({statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}});
const request=(method,body={},query={})=>({method,body,query:{missionId:mission,...query},headers:{origin:'http://localhost:3000',host:'localhost:3000'}});
const context=permissions=>({organisation:{id:org},internalUser:{id:actor},permissions,operatingLocationIds:[location]});
const repository={get:jest.fn(),readMissionJsa:jest.fn(),saveMissionJsa:jest.fn(),approveMissionJsa:jest.fn(),evaluateMissionJsa:jest.fn()};
beforeEach(()=>{jest.clearAllMocks();repository.get.mockResolvedValue({id:mission,organisation_id:org,operating_location_id:location});repository.readMissionJsa.mockResolvedValue({id:revision,version_number:1});repository.saveMissionJsa.mockResolvedValue({record:{id:revision,version_number:1}});repository.approveMissionJsa.mockResolvedValue({record:{id:revision},readiness:{overallState:'READY'}});repository.evaluateMissionJsa.mockResolvedValue({overallState:'BLOCKED',ready:false,blockers:[],warnings:[],categories:{},outstandingSections:['Approval'],completedSections:['Questions']});});

test('reads current/history and grouped readiness',async()=>{const handler=createMissionJsaHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.jsa.read']))});let res=response();await handler(request('GET'),res);expect(res.statusCode).toBe(200);expect(res.body.data.version_number).toBe(1);res=response();await handler(request('GET',{}, {action:'readiness'}),res);expect(res.body.data.overallState).toBe('BLOCKED');expect(repository.evaluateMissionJsa).toHaveBeenCalledWith(expect.anything(),mission);});
test('saves immutable JSA revisions and maps stale conflicts',async()=>{const handler=createMissionJsaHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.jsa.write']))});let res=response();await handler(request('POST',{expectedVersion:0,responses:[{questionId:'maps',answer:true}],controls:[],attachments:[],generalComments:''}),res);expect(res.statusCode).toBe(201);expect(repository.saveMissionJsa).toHaveBeenCalled();repository.saveMissionJsa.mockResolvedValueOnce({conflict:true,currentVersion:2});res=response();await handler(request('POST',{expectedVersion:1,responses:[],controls:[]}),res);expect(res.statusCode).toBe(409);expect(res.body.error.code).toBe('VERSION_CONFLICT');});
test('assigned PIC approval uses permission and exact revision',async()=>{const handler=createMissionJsaHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.jsa.approve']))});const res=response();await handler(request('POST',{expectedVersion:2,revisionId:revision},{action:'approve'}),res);expect(res.statusCode).toBe(201);expect(repository.approveMissionJsa).toHaveBeenCalledWith(expect.anything(),mission,revision,2);});
test('permission, validation, location and unsupported action failures are explicit',async()=>{let handler=createMissionJsaHandler({repository,resolveContext:jest.fn().mockResolvedValue(context([]))}),res=response();await handler(request('GET'),res);expect(res.statusCode).toBe(403);handler=createMissionJsaHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['mission.jsa.write']))});res=response();await handler(request('POST',{expectedVersion:-1,responses:[]}),res);expect(res.statusCode).toBe(400);res=response();await handler(request('POST',{expectedVersion:0,responses:[]},{action:'remove-derived-controls'}),res);expect(res.body.error.code).toBe('UNSUPPORTED_ACTION');repository.get.mockResolvedValueOnce(null);res=response();await handler(request('GET'),res);expect(res.statusCode).toBe(404);});
