const {createOrganisationBrandingHandler}=require('../../server/operational-api');
const org='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222';
const response=()=>({statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}});
const request=(method,body={},action='profile')=>({method,body,query:{action},headers:{origin:'http://localhost:3000',host:'localhost:3000'}});
const context=permissions=>({organisation:{id:org},internalUser:{id:actor},permissions,operatingLocationIds:[]});
const repository={readOrganisationBranding:jest.fn(),updateOrganisationBranding:jest.fn(),storeOrganisationLogo:jest.fn(),activateOrganisationLogo:jest.fn(),removeOrganisationLogo:jest.fn()};

beforeEach(()=>{jest.clearAllMocks();repository.readOrganisationBranding.mockResolvedValue({organisation:{id:org,row_version:1},logos:[]});});

test('reads organisation-scoped branding without requiring an operating location',async()=>{const handler=createOrganisationBrandingHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['organisation.branding.read']))});const res=response();await handler(request('GET'),res);expect(res.statusCode).toBe(200);expect(repository.readOrganisationBranding).toHaveBeenCalledWith(expect.objectContaining({organisation:{id:org}}));});

test('requires manage permission for upload and returns internal metadata only',async()=>{const logo={id:'l1',internalFileId:'f1',fileVersion:1,originalFilename:'logo.png',contentType:'image/png',byteSize:24,checksum:'a'.repeat(64),width:320,height:120,uploadedAt:'2026-08-04T00:00:00Z',active:false};repository.storeOrganisationLogo.mockResolvedValue({record:logo});let handler=createOrganisationBrandingHandler({repository,resolveContext:jest.fn().mockResolvedValue(context([]))}),res=response();await handler(request('POST',{fileName:'logo.png',dataUrl:'data:image/png;base64,AA=='},'logo'),res);expect(res.statusCode).toBe(403);handler=createOrganisationBrandingHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['organisation.branding.manage']))});res=response();await handler(request('POST',{fileName:'logo.png',dataUrl:'data:image/png;base64,AA=='},'logo'),res);expect(res.statusCode).toBe(201);expect(res.body.data).toEqual(logo);expect(JSON.stringify(res.body)).not.toMatch(/provider|bucket|objectKey|url/i);});

test('routes activation with optimistic concurrency and exposes conflicts',async()=>{repository.activateOrganisationLogo.mockResolvedValueOnce({conflict:true,currentVersion:3});const handler=createOrganisationBrandingHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['organisation.branding.manage']))});const res=response();await handler(request('POST',{internalFileId:'33333333-3333-4333-8333-333333333333',fileVersion:1,expectedVersion:2},'activate-logo'),res);expect(res.statusCode).toBe(409);expect(res.body.error).toEqual(expect.objectContaining({code:'VERSION_CONFLICT',meta:{currentVersion:3}}));});

test('returns visible validation failures and rejects unsupported actions',async()=>{repository.storeOrganisationLogo.mockRejectedValue(Object.assign(new Error('Only PNG, JPEG or WebP logos are supported.'),{status:400,code:'UNSUPPORTED_LOGO'}));const handler=createOrganisationBrandingHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['organisation.branding.manage']))});let res=response();await handler(request('POST',{fileName:'logo.svg',dataUrl:'data:image/svg+xml;base64,AA=='},'logo'),res);expect(res.body.error).toEqual(expect.objectContaining({code:'UNSUPPORTED_LOGO'}));res=response();await handler(request('POST',{},'delete-logo'),res);expect(res.body.error.code).toBe('UNSUPPORTED_ACTION');});
