const fs=require('fs');
const path=require('path');

const migrationPath=path.join(__dirname,'../../supabase/migrations/20260804010000_organisation_branding_report_identity.sql');
const migration=()=>fs.readFileSync(migrationPath,'utf8');

test('extends the authoritative organisation without creating a duplicate profile',()=>{
 const sql=migration();
 for(const field of ['legal_business_name','trading_name','report_display_name','business_identifier_type','business_identifier_value','registered_address','postal_address','primary_phone','primary_email','website','report_contact_details','licence_accreditation_details','branding_status','active_logo_file_id','active_logo_file_version','row_version'])expect(sql).toContain(field);
 expect(sql).toContain('alter table public.organisations');
 expect(sql).not.toContain('create table public.organisation_business_profiles');
 expect(sql).not.toMatch(/set\s+legal_business_name\s*=\s*name/i);
});

test('provisions explicit permission and subscription capability catalogues',()=>{
 const sql=migration();
 for(const permission of ['organisation.branding.read','organisation.branding.manage','reports.read','reports.generate','mission.pack.generate','mission.record.generate'])expect(sql).toContain(`'${permission}'`);
 for(const state of ['BRANDING_UNAVAILABLE','ORGANISATION_BRANDING','ADVANCED_BRANDING','FULL_WHITE_LABEL'])expect(sql).toContain(`'${state}'`);
 expect(sql).toContain('organisation_capability_entitlements');
 expect(sql).not.toMatch(/Ben|Clare|@/);
});

test('uses trusted versioned commands with audit, outbox and tenant protection',()=>{
 const sql=migration();
 for(const fn of ['ftf_read_organisation_branding','ftf_update_organisation_branding','ftf_actor_has_permission'])expect(sql).toContain(`public.${fn}`);
 for(const token of ['p_expected_version','conflict','forbidden','organisation.branding.updated','platform.organisation.branding_updated','enable row level security','force row level security','current_user_has_organisation_access'])expect(sql).toContain(token);
 expect(sql).toContain('row_version=p_expected_version');
 expect(sql).toContain('set_tenant_row_update_metadata');
});

test('preserves mandatory Spray Command attribution and deferred white label boundary',()=>{
 const sql=migration();
 expect(sql).toContain("'Generated by Spray Command'");
 expect(sql).toContain("full_white_label_enabled boolean not null default false");
});
