const {createPersonnelIdentityHandler}=require('../../server/operational-api');
const org='61000000-0000-4000-8000-000000000001',actor='61000000-0000-4000-8000-000000000101',person='61000000-0000-4000-8000-000000000201',user='61000000-0000-4000-8000-000000000102',membership='61000000-0000-4000-8000-000000000122';
const response=()=>({statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}});
const request=(method,body={},query={})=>({method,body,query:{personnelId:person,...query},headers:{origin:'http://localhost:3000',host:'localhost:3000'}});
const context=permissions=>({organisation:{id:org},internalUser:{id:actor},permissions,operatingLocationIds:[]});
const repository={listPersonnelIdentityCandidates:jest.fn(),linkPersonnelIdentity:jest.fn(),unlinkPersonnelIdentity:jest.fn()};
beforeEach(()=>{jest.clearAllMocks();repository.listPersonnelIdentityCandidates.mockResolvedValue({personnel:{id:person,rowVersion:1},candidates:[]});repository.linkPersonnelIdentity.mockResolvedValue({record:{id:person,row_version:2,internal_user_id:user}});repository.unlinkPersonnelIdentity.mockResolvedValue({record:{id:person,row_version:3,internal_user_id:null}});});

test('authorised administrator lists comparison candidates',async()=>{const handler=createPersonnelIdentityHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['personnel.identity.manage']))}),res=response();await handler(request('GET'),res);expect(res.statusCode).toBe(200);expect(repository.listPersonnelIdentityCandidates).toHaveBeenCalledWith(expect.anything(),person);});
test('ordinary user cannot read or mutate identity links',async()=>{const handler=createPersonnelIdentityHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['personnel.read']))});for(const method of['GET','POST']){const res=response();await handler(request(method,{action:'LINK',expectedVersion:1,internalUserId:user,membershipId:membership,reason:'confirmed'}),res);expect(res.statusCode).toBe(403);expect(res.body.error.code).toBe('FORBIDDEN');}});
test('link requires explicit identity, version and reason',async()=>{const handler=createPersonnelIdentityHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['personnel.identity.manage']))}),res=response();await handler(request('POST',{action:'LINK',expectedVersion:1,internalUserId:user,membershipId:membership,reason:'Confirmed identity comparison'}),res);expect(res.statusCode).toBe(201);expect(repository.linkPersonnelIdentity).toHaveBeenCalledWith(expect.anything(),person,1,user,membership,'Confirmed identity comparison');const invalid=response();await handler(request('POST',{action:'LINK',expectedVersion:1,internalUserId:user,membershipId:membership,reason:''}),invalid);expect(invalid.statusCode).toBe(400);});
test('unlink and replace conflicts remain explicit',async()=>{const handler=createPersonnelIdentityHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['personnel.identity.manage']))});let res=response();await handler(request('POST',{action:'UNLINK',expectedVersion:2,reason:'Account recovery'}),res);expect(res.statusCode).toBe(201);expect(repository.unlinkPersonnelIdentity).toHaveBeenCalledWith(expect.anything(),person,2,'Account recovery');repository.linkPersonnelIdentity.mockResolvedValueOnce({conflict:true,currentVersion:4});res=response();await handler(request('POST',{action:'LINK',expectedVersion:2,internalUserId:user,membershipId:membership,reason:'Replace confirmed link'}),res);expect(res.statusCode).toBe(409);expect(res.body.error.code).toBe('VERSION_CONFLICT');});
test('unsupported methods and actions fail visibly',async()=>{const handler=createPersonnelIdentityHandler({repository,resolveContext:jest.fn().mockResolvedValue(context(['personnel.identity.manage']))});let res=response();await handler(request('DELETE'),res);expect(res.statusCode).toBe(405);res=response();await handler(request('POST',{action:'MERGE',expectedVersion:1,reason:'x'}),res);expect(res.body.error.code).toBe('UNSUPPORTED_ACTION');});
