import{render,screen,waitFor}from'@testing-library/react';
import userEvent from'@testing-library/user-event';
import MissionWeatherEvidence from'../MissionWeatherEvidence';

const observer={id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',fullName:'Alex Pilot',isActive:true,operatingLocationIds:['cccccccc-cccc-4ccc-8ccc-cccccccccccc'],operationalRoles:['pilot'],credentials:[],engagementStatus:'employee',rowVersion:1};
const personnelApi=()=>({list:jest.fn().mockResolvedValue([observer])}as any);
const readiness={ready:false,blockers:[{code:'WEATHER_NOT_SELECTED',message:'Select evidence'}],warnings:[]};
const selectedForecast={id:'forecast',version_number:1,evidence_stage:'PLANNING',provider:'OPEN_METEO',provider_model:'best_match',issued_at:'2026-08-03T00:00:00Z',valid_from:'2026-08-09T22:00:00Z',valid_to:'2026-08-10T02:00:00Z',latitude:-27.5,longitude:153.1,selected:true,selection_version:1,provider_snapshot:{timezone:'Australia/Brisbane',utc_offset_seconds:36000,hourly:{time:['2026-08-10T08:00','2026-08-10T09:00'],temperature_2m:[24,25],relative_humidity_2m:[60,55],wind_speed_10m:[10,12],wind_gusts_10m:[18,20],wind_direction_10m:[90,100],precipitation_probability:[20,30],precipitation:[0,0.2],cloud_cover:[30,40]}}};
const weatherApi=(records:any[]=[],forecasts:any[]=[])=>( {read:jest.fn().mockResolvedValue(records),forecasts:jest.fn().mockResolvedValue(forecasts),readiness:jest.fn().mockResolvedValue(readiness),createForecast:jest.fn().mockResolvedValue(selectedForecast),selectForecast:jest.fn().mockResolvedValue({selection_version:1}),createManual:jest.fn().mockResolvedValue({id:'ffffffff-ffff-4fff-8fff-ffffffffffff',version_number:1,delta_t_c:9.6,delta_t_source:'CALCULATED',calculated_delta_t_c:9.6,delta_t_variance_warning:false,freshness_state:'CURRENT'}),select:jest.fn().mockResolvedValue({selection_version:1})}as any);
const locationCapture=((success:PositionCallback)=>success({coords:{latitude:-27.5,longitude:153.1,accuracy:8,altitude:null,altitudeAccuracy:null,heading:null,speed:null},timestamp:Date.now()}as GeolocationPosition))as Geolocation['getCurrentPosition'];

test('captures current device coordinates into read-only evidence fields',async()=>{const weather=weatherApi();render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);await screen.findByText('Alex Pilot');await userEvent.click(screen.getByRole('button',{name:'Capture current location'}));expect(screen.getByLabelText('Latitude')).toHaveValue(-27.5);expect(screen.getByLabelText('Longitude')).toHaveValue(153.1);expect(screen.getByLabelText('Latitude')).toHaveAttribute('readonly');expect(screen.getByLabelText('Longitude')).toHaveAttribute('readonly');expect(screen.getByText(/8 m accuracy/)).toBeInTheDocument();});

test('keeps the Weather observer label floated with an open outline notch',async()=>{const weather=weatherApi();render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);await screen.findByText('Alex Pilot');const select=screen.getByRole('combobox',{name:/Weather observer/});const label=document.querySelector(`label[for="${select.id}"]`);expect(label).toHaveAttribute('data-shrink','true');const legend=select.closest('.MuiFormControl-root')?.querySelector('fieldset legend');expect(getComputedStyle(legend as Element).maxWidth).toBe('100%');});

test('location failure without a valid saved boundary remains a clear blocker',async()=>{const weather=weatherApi();const denied=((_:PositionCallback,failure:PositionErrorCallback)=>failure({code:1,message:'denied',PERMISSION_DENIED:1,POSITION_UNAVAILABLE:2,TIMEOUT:3}as GeolocationPositionError))as Geolocation['getCurrentPosition'];render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={denied}/>);await screen.findByText('Alex Pilot');await userEvent.click(screen.getByRole('button',{name:'Capture current location'}));expect(await screen.findByText(/Current location could not be captured/)).toBeInTheDocument();expect(screen.getByText(/No valid authoritative Mission boundary is available/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Use Mission boundary location'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Save Manual Weather'})).toBeDisabled();expect(weather.createManual).not.toHaveBeenCalled();});

test('explicitly uses and retains the authoritative Mission boundary centroid after GPS denial',async()=>{const weather=weatherApi(),onEvidenceChanged=jest.fn();const denied=((_:PositionCallback,failure:PositionErrorCallback)=>failure({code:1,message:'Permission denied',PERMISSION_DENIED:1,POSITION_UNAVAILABLE:2,TIMEOUT:3}as GeolocationPositionError))as Geolocation['getCurrentPosition'];const boundary={revisionId:'11111111-1111-4111-8111-111111111111',revisionVersion:3,geometryId:'22222222-2222-4222-8222-222222222222',geometry:{type:'Polygon',coordinates:[[[153,-27],[153.02,-27],[153.02,-27.02],[153,-27.02],[153,-27]]]}};render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" authoritativeBoundary={boundary} onEvidenceChanged={onEvidenceChanged} weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={denied}/>);await screen.findByText('Alex Pilot');await userEvent.click(screen.getByRole('button',{name:'Capture current location'}));await userEvent.click(await screen.findByRole('button',{name:'Use Mission boundary location'}));expect(screen.getByText('Location source: Mission boundary centroid')).toBeInTheDocument();expect(screen.getByText(/Observation location is based on the Mission boundary centroid/)).toBeInTheDocument();expect(screen.getByLabelText('Latitude')).toHaveValue(-27.01);expect(screen.getByLabelText('Longitude')).toHaveValue(153.01);await userEvent.selectOptions(screen.getByRole('combobox',{name:/Weather observer/}),observer.id);for(const[name,value]of[['Observation location','Field 1'],['Temperature (°C)','30'],['Relative humidity (%)','40'],['Wind speed (km/h)','10'],['Wind direction (degrees)','90'],['Reason for manual entry','On-site reading']])await userEvent.type(screen.getByLabelText(name),value);await userEvent.selectOptions(screen.getByRole('combobox',{name:/Inversion assessment/}),'UNLIKELY');await userEvent.click(screen.getByRole('button',{name:'Save Manual Weather'}));await waitFor(()=>expect(weather.createManual).toHaveBeenCalledWith(expect.any(String),expect.objectContaining({locationSource:'MISSION_BOUNDARY',missionMapRevisionId:boundary.revisionId,missionBoundaryGeometryId:boundary.geometryId,centroidCalculationVersion:'POLYGON_CENTROID_V1',locationFailureReason:'Permission denied'})));expect(onEvidenceChanged).toHaveBeenCalledTimes(1);});

test('saves calculated Delta T mode and displays only the authoritative server result',async()=>{const weather=weatherApi();render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);await screen.findByText('Alex Pilot');expect(screen.getByRole('checkbox',{name:'Calculate Delta T from temperature and humidity'})).toBeChecked();expect(screen.getByLabelText('Delta T (°C)')).toHaveAttribute('readonly');await userEvent.selectOptions(screen.getByRole('combobox',{name:/Weather observer/}),observer.id);await userEvent.click(screen.getByRole('button',{name:'Capture current location'}));expect(screen.getByText(/Location source: Device GPS/)).toBeInTheDocument();for(const[name,value]of[['Observation location','Field 1'],['Temperature (°C)','30'],['Relative humidity (%)','40'],['Wind speed (km/h)','10'],['Wind direction (degrees)','90'],['Reason for manual entry','On-site reading']])await userEvent.type(screen.getByLabelText(name),value);await userEvent.selectOptions(screen.getByRole('combobox',{name:/Inversion assessment/}),'UNLIKELY');await userEvent.click(screen.getByRole('button',{name:'Save Manual Weather'}));await waitFor(()=>expect(weather.createManual).toHaveBeenCalledWith(expect.any(String),expect.objectContaining({latitude:-27.5,longitude:153.1,locationSource:'DEVICE_GPS',locationAccuracyM:8,locationCapturedAt:expect.any(String),deltaTMode:'CALCULATED'})));expect(await screen.findByText('Authoritative Delta T: 9.6 °C')).toBeInTheDocument();expect(screen.getByText('Source: Calculated from temperature and humidity')).toBeInTheDocument();});

test('retains Kestrel Delta T as authoritative and warns on server comparison variance',async()=>{const weather=weatherApi();weather.createManual.mockResolvedValue({id:'measured',version_number:1,delta_t_c:7.1,delta_t_source:'KESTREL_MEASURED',calculated_delta_t_c:9.6,delta_t_variance_c:-2.5,delta_t_variance_warning:true,freshness_state:'CURRENT'});render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);await screen.findByText('Alex Pilot');await userEvent.click(screen.getByRole('checkbox',{name:'Calculate Delta T from temperature and humidity'}));expect(screen.getByLabelText('Delta T (°C)')).not.toHaveAttribute('readonly');await userEvent.type(screen.getByLabelText('Delta T (°C)'),'7.1');await userEvent.selectOptions(screen.getByRole('combobox',{name:/Weather observer/}),observer.id);await userEvent.click(screen.getByRole('button',{name:'Capture current location'}));for(const[name,value]of[['Observation location','Field 1'],['Temperature (°C)','30'],['Relative humidity (%)','40'],['Wind speed (km/h)','10'],['Wind direction (degrees)','90'],['Reason for manual entry','Kestrel on site']])await userEvent.type(screen.getByLabelText(name),value);await userEvent.selectOptions(screen.getByRole('combobox',{name:/Inversion assessment/}),'UNLIKELY');await userEvent.click(screen.getByRole('button',{name:'Save Manual Weather'}));await waitFor(()=>expect(weather.createManual).toHaveBeenCalledWith(expect.any(String),expect.objectContaining({deltaTMode:'KESTREL_MEASURED',deltaTC:7.1})));expect(await screen.findByText(/Kestrel Delta T differs from the calculated comparison/)).toBeInTheDocument();expect(screen.getByText('Authoritative Delta T: 7.1 °C')).toBeInTheDocument();});

test('reopened PostgreSQL evidence retains authoritative Delta T',async()=>{const weather=weatherApi([{id:'saved',version_number:1,source:'MANUAL',delta_t_c:7.4,freshness_state:'CURRENT',selected:true}]);render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);expect(await screen.findByText('Authoritative Delta T: 7.4 °C')).toBeInTheDocument();});
test('separates Planning Forecast Weather from Observed Pre-flight Weather',async()=>{const weather=weatherApi();render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" scheduledStartAt="2026-08-09T22:00:00Z" plannedCoordinates={{latitude:-27.5,longitude:153.1}} weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);expect(await screen.findByText('PLANNING FORECAST')).toBeInTheDocument();expect(screen.getByText('OBSERVED PRE-FLIGHT WEATHER')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Get Forecast'}));await waitFor(()=>expect(weather.createForecast).toHaveBeenCalledWith(expect.any(String),expect.objectContaining({latitude:-27.5,longitude:153.1})));expect(weather.selectForecast).toHaveBeenCalledWith(expect.any(String),'forecast',0);expect(screen.getByText(/Planning forecast version 1 selected/)).toBeInTheDocument();});

test('reloads and displays the selected PostgreSQL forecast as the Planning guide',async()=>{const weather=weatherApi([],[selectedForecast]);render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" scheduledStartAt="2026-08-09T22:00:00Z" plannedCoordinates={{latitude:-27.5,longitude:153.1}} weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);expect(await screen.findByText('Selected forecast · version 1')).toBeInTheDocument();for(const text of ['Open-Meteo · best_match','24 °C','60%','5.4 °C','10 km/h','18 km/h','90°','20%','0 mm','30%','-27.500000, 153.100000','Current','Exact Mission-time interval'])expect(screen.getByText(text)).toBeInTheDocument();expect(screen.getByText(/Valid from/)).toBeInTheDocument();expect(screen.getByText(/Retrieved/)).toBeInTheDocument();expect(screen.getByText(/Inversion guidance is not provided/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Refresh Forecast'})).toBeInTheDocument();});

test('warns when the selected immutable forecast no longer aligns after the planned Mission time changes',async()=>{const weather=weatherApi([],[selectedForecast]);const view=render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" scheduledStartAt="2026-08-09T22:00:00Z" plannedCoordinates={{latitude:-27.5,longitude:153.1}} weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);expect(await screen.findByText('Exact Mission-time interval')).toBeInTheDocument();view.rerender(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" scheduledStartAt="2026-08-11T08:00:00Z" plannedCoordinates={{latitude:-27.5,longitude:153.1}} weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);expect(await screen.findByText(/Selected forecast no longer aligns with the planned Mission time/)).toBeInTheDocument();expect(screen.getByText('Misaligned')).toBeInTheDocument();expect(weather.selectForecast).not.toHaveBeenCalled();expect(weather.createForecast).not.toHaveBeenCalled();});
