import{render,screen,waitFor}from'@testing-library/react';
import userEvent from'@testing-library/user-event';
import MissionWeatherEvidence from'../MissionWeatherEvidence';

const observer={id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',fullName:'Alex Pilot',isActive:true,operatingLocationIds:['cccccccc-cccc-4ccc-8ccc-cccccccccccc'],operationalRoles:['pilot'],credentials:[],engagementStatus:'employee',rowVersion:1};
const personnelApi=()=>({list:jest.fn().mockResolvedValue([observer])}as any);
const readiness={ready:false,blockers:[{code:'WEATHER_NOT_SELECTED',message:'Select evidence'}],warnings:[]};
const weatherApi=(records:any[]=[])=>( {read:jest.fn().mockResolvedValue(records),readiness:jest.fn().mockResolvedValue(readiness),createManual:jest.fn().mockResolvedValue({id:'ffffffff-ffff-4fff-8fff-ffffffffffff',version_number:1,delta_t_c:9.6,freshness_state:'CURRENT'}),select:jest.fn().mockResolvedValue({selection_version:1})}as any);
const locationCapture=((success:PositionCallback)=>success({coords:{latitude:-27.5,longitude:153.1,accuracy:8,altitude:null,altitudeAccuracy:null,heading:null,speed:null},timestamp:Date.now()}as GeolocationPosition))as Geolocation['getCurrentPosition'];

test('captures current device coordinates into read-only evidence fields',async()=>{const weather=weatherApi();render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);await screen.findByText('Alex Pilot');await userEvent.click(screen.getByRole('button',{name:'Capture current location'}));expect(screen.getByLabelText('Latitude')).toHaveValue(-27.5);expect(screen.getByLabelText('Longitude')).toHaveValue(153.1);expect(screen.getByLabelText('Latitude')).toHaveAttribute('readonly');expect(screen.getByLabelText('Longitude')).toHaveAttribute('readonly');expect(screen.getByText(/8 m accuracy/)).toBeInTheDocument();});

test('location failure is visible and cannot create Weather evidence',async()=>{const weather=weatherApi();const denied=((_:PositionCallback,failure:PositionErrorCallback)=>failure({code:1,message:'denied',PERMISSION_DENIED:1,POSITION_UNAVAILABLE:2,TIMEOUT:3}as GeolocationPositionError))as Geolocation['getCurrentPosition'];render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={denied}/>);await screen.findByText('Alex Pilot');await userEvent.click(screen.getByRole('button',{name:'Capture current location'}));expect(await screen.findByText(/Current location could not be captured/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Save Manual Weather'})).toBeDisabled();expect(weather.createManual).not.toHaveBeenCalled();});

test('saves captured coordinates and displays only authoritative server Delta T',async()=>{const weather=weatherApi();render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);await screen.findByText('Alex Pilot');await userEvent.selectOptions(screen.getByRole('combobox',{name:/Weather observer/}),observer.id);await userEvent.click(screen.getByRole('button',{name:'Capture current location'}));for(const[name,value]of[['Observation location','Field 1'],['Temperature (°C)','30'],['Relative humidity (%)','40'],['Wind speed (km/h)','10'],['Wind direction (degrees)','90'],['Reason for manual entry','On-site Kestrel reading']])await userEvent.type(screen.getByLabelText(name),value);await userEvent.selectOptions(screen.getByRole('combobox',{name:/Inversion assessment/}),'UNLIKELY');await userEvent.click(screen.getByRole('button',{name:'Save Manual Weather'}));await waitFor(()=>expect(weather.createManual).toHaveBeenCalledWith(expect.any(String),expect.objectContaining({latitude:-27.5,longitude:153.1})));expect(await screen.findByText('Authoritative Delta T: 9.6 °C')).toBeInTheDocument();await waitFor(()=>expect(weather.select).toHaveBeenCalled());});

test('reopened PostgreSQL evidence retains authoritative Delta T',async()=>{const weather=weatherApi([{id:'saved',version_number:1,source:'MANUAL',delta_t_c:7.4,freshness_state:'CURRENT',selected:true}]);render(<MissionWeatherEvidence missionId="eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee" operatingLocationId="cccccccc-cccc-4ccc-8ccc-cccccccccccc" weatherApi={weather} personnelApi={personnelApi()} getCurrentPosition={locationCapture}/>);expect(await screen.findByText('Authoritative Delta T: 7.4 °C')).toBeInTheDocument();});
