import React from 'react';
import { Alert, Button, FormControl, FormHelperText, Grid, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import { createPersonnelApi } from '../../services/personnelApi';

type Api=Pick<ReturnType<typeof createPersonnelApi>,'createCasaCredential'>;
const split=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean);

export default function PersonnelCredentialEditor({personnelId,personnelName,api,onSaved}:{personnelId:string;personnelName:string;api:Api;onSaved:()=>void}){
 const[open,setOpen]=React.useState(false),[saving,setSaving]=React.useState(false),[message,setMessage]=React.useState(''),[file,setFile]=React.useState<File|null>(null);
 const[form,setForm]=React.useState({credentialType:'RePL',arn:'',identifier:'',issuer:'CASA',issueDate:'',expiryDate:'',categories:'',ratings:'',aircraftTypes:'',minimumWeightKg:'',maximumWeightKg:'',conditions:'',limitations:''});
 const update=(key:keyof typeof form)=>(event:any)=>setForm(current=>({...current,[key]:event.target.value}));
 const save=async()=>{if(!file)return;setSaving(true);setMessage('');try{await api.createCasaCredential(personnelId,{credentialType:form.credentialType,arn:form.arn.trim(),identifier:form.identifier.trim(),issuer:form.issuer.trim(),issueDate:form.issueDate,expiryDate:form.credentialType==='RePL'?null:(form.expiryDate||null),categories:split(form.categories),ratings:split(form.ratings),aircraftTypes:split(form.aircraftTypes),minimumWeightKg:form.minimumWeightKg===''?null:Number(form.minimumWeightKg),maximumWeightKg:form.maximumWeightKg===''?null:Number(form.maximumWeightKg),conditions:form.conditions.trim()||null,limitations:form.limitations.trim()||null,file,provenance:{source:'OPERATOR_UPLOAD',personnelName}});setMessage('Credential evidence saved for verification.');setOpen(false);onSaved();}catch(error){setMessage(error instanceof Error?error.message:'Credential evidence could not be saved.');}finally{setSaving(false);}};
 const valid=Boolean(form.identifier.trim()&&form.issuer.trim()&&form.issueDate&&file);
 return <Stack spacing={1}>{!open&&<Button size="small" variant="outlined" onClick={()=>setOpen(true)}>Add CASA credential</Button>}{open&&<Grid container spacing={1.5} sx={{mt:1}}>
  <Grid size={{xs:12}}><Typography fontWeight={800}>CASA certificate evidence for {personnelName}</Typography><Alert severity="info">Saving records evidence for independent verification. It does not automatically approve the credential.</Alert></Grid>
  <Grid size={{xs:12,sm:4}}><FormControl fullWidth><InputLabel id="credential-type-label">Credential type</InputLabel><Select labelId="credential-type-label" label="Credential type" value={form.credentialType} onChange={update('credentialType')} inputProps={{'aria-label':'Credential type'}}><MenuItem value="RePL">RePL</MenuItem><MenuItem value="AROC">AROC</MenuItem></Select></FormControl></Grid>
  <Grid size={{xs:12,sm:4}}><TextField required fullWidth label="ARN" inputProps={{'aria-label':'ARN'}} value={form.arn} onChange={update('arn')}/></Grid>
  <Grid size={{xs:12,sm:4}}><TextField required fullWidth label="Credential identifier" inputProps={{'aria-label':'Credential identifier'}} value={form.identifier} onChange={update('identifier')}/></Grid><Grid size={{xs:12,sm:4}}><TextField required fullWidth label="Issuer" inputProps={{'aria-label':'Issuer'}} value={form.issuer} onChange={update('issuer')}/></Grid>
  <Grid size={{xs:12,sm:4}}><TextField required fullWidth type="date" label="Issue date" inputProps={{'aria-label':'Issue date'}} InputLabelProps={{shrink:true}} value={form.issueDate} onChange={update('issueDate')}/></Grid>
  <Grid size={{xs:12,sm:4}}>{form.credentialType==='RePL'?<Alert severity="info">RePL certificates do not expire.</Alert>:<Stack><TextField fullWidth type="date" label="Expiry date (optional)" InputLabelProps={{shrink:true}} value={form.expiryDate} onChange={update('expiryDate')}/><FormHelperText>If no expiry appears on the certificate, leave this blank.</FormHelperText></Stack>}</Grid>
  <Grid size={{xs:12,sm:4}}><Button component="label" fullWidth variant="outlined">{file?file.name:'Upload certificate'}<input hidden type="file" aria-label="Certificate file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={event=>setFile(event.target.files?.[0]||null)}/></Button></Grid>
  <Grid size={{xs:12,sm:4}}><TextField fullWidth label="Categories" inputProps={{'aria-label':'Categories'}} helperText="Comma separated" value={form.categories} onChange={update('categories')}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth label="Ratings" inputProps={{'aria-label':'Ratings'}} helperText="Comma separated" value={form.ratings} onChange={update('ratings')}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth label="Aircraft types" inputProps={{'aria-label':'Aircraft types'}} helperText="Comma separated" value={form.aircraftTypes} onChange={update('aircraftTypes')}/></Grid>
  <Grid size={{xs:12,sm:3}}><TextField fullWidth type="number" label="Minimum aircraft weight (kg)" value={form.minimumWeightKg} onChange={update('minimumWeightKg')}/></Grid><Grid size={{xs:12,sm:3}}><TextField fullWidth type="number" label="Maximum aircraft weight (kg)" value={form.maximumWeightKg} onChange={update('maximumWeightKg')}/></Grid><Grid size={{xs:12,sm:3}}><TextField fullWidth label="Conditions" value={form.conditions} onChange={update('conditions')}/></Grid><Grid size={{xs:12,sm:3}}><TextField fullWidth label="Limitations" value={form.limitations} onChange={update('limitations')}/></Grid>
  <Grid size={{xs:12}}><Stack direction="row" spacing={1}><Button variant="contained" disabled={saving||!valid} onClick={()=>void save()}>{saving?'Saving evidence…':'Save credential evidence'}</Button><Button onClick={()=>setOpen(false)}>Cancel</Button></Stack></Grid>
 </Grid>}{message&&<Alert severity={message.includes('saved')?'success':'error'}>{message}</Alert>}</Stack>;
}
