export type FinancialDecimal=string&{readonly __financialDecimal:unique symbol};
export type FinancialLifecycle='DRAFT'|'FINAL'|'UNINITIALISED';
export type FinancialCostCategory='LABOUR'|'PRODUCT'|'TRAVEL'|'AIRCRAFT_EQUIPMENT'|'OTHER';
export type FinancialProvenanceClass='AUTHORITATIVE_OPERATIONAL_INPUT'|'SYSTEM_DERIVED'|'MANUAL_FINANCIAL_INPUT'|'MANUAL_OVERRIDE';
export interface FinancialCalculation{formulaVersion?:'FINANCIAL_ACTUAL_V1';currencyCode?:'AUD';operationalDays?:number;totalHours?:FinancialDecimal;revenue:FinancialDecimal;totalCost:FinancialDecimal;grossProfit:FinancialDecimal;grossMarginPercentage:FinancialDecimal|null;effectiveHourlyRevenue?:FinancialDecimal|null;categoryTotals?:Record<FinancialCostCategory,FinancialDecimal>;lineAmounts?:Record<string,FinancialDecimal>}
export interface FinancialSummary{ id:string;reference:string;operatingLocation:{id:string;label:string};client:{id:string;label:string};job:{id:string;label:string};mission:{id:string;label:string}|null;lifecycle:FinancialLifecycle;correctionDraftInProgress:boolean;activeDraft:{id:string;revisionNumber:number;rowVersion:number}|null;currentFinalRevisionNumber:number|null;finalCalculation:Pick<FinancialCalculation,'revenue'|'totalCost'|'grossProfit'|'grossMarginPercentage'>|null;sourceDrift:string;archived:boolean }
export interface FinancialSummaryPage{schemaVersion:'FINANCIAL_ACTUAL_LIST_V1';rows:FinancialSummary[];nextCursor:string|null}
export interface FinancialProvenance{id:string;fieldPath:string;provenanceClass:FinancialProvenanceClass;predecessorProvenanceId:string|null;sourceEntityType:string|null;sourceEntityId:string|null;sourceVersion:string|null;sourceRecordedAt:string|null;originalValue:string;effectiveValue:string;unitCode:string|null;overrideReason:string|null;acceptedByInternalUserId:string;acceptedAt:string}
export interface FinancialWorkEntry{id:string;workDate:string;actualWorkHours:FinancialDecimal;provenanceId:string}
export interface FinancialCostLine{id:string;category:FinancialCostCategory;subtype:string;description:string;incurredOn:string|null;quantity:FinancialDecimal;unitCode:string;unitCost:FinancialDecimal;amount:FinancialDecimal;provenanceId:string;displayOrder:number}
export interface FinancialDraft{id:string;revisionNumber:number;status:'DRAFT';rowVersion:number;currencyCode:'AUD';formulaVersion:'FINANCIAL_ACTUAL_V1';startDate:string;endDate:string;operationalSources:Record<string,unknown>;revenueInputs:Record<string,unknown>;workEntries:FinancialWorkEntry[];costLines:FinancialCostLine[];provenance:FinancialProvenance[]}
export interface FinancialFinal{id:string;revisionNumber:number;status:'FINAL';rowVersion:number;currencyCode:'AUD';formulaVersion:'FINANCIAL_ACTUAL_V1';startDate:string;endDate:string;input:Record<string,unknown>;provenance:{rows:Record<string,unknown>[]};calculation:FinancialCalculation;sourceManifest:Record<string,unknown>;inputDigest:string;finalisedAt:string;finalisedByInternalUserId:string}
export interface FinancialActualDetail{schemaVersion:'FINANCIAL_ACTUAL_AUTHORITY_DETAIL_V1';record:{id:string;reference:string;organisationId:string;operatingLocationId:string;clientId:string;propertyId:string;fieldId:string;jobId:string;missionId:string|null;rowVersion:number;archivedAt:string|null;currentFinalRevisionId:string|null;activeDraftRevisionId:string|null};hierarchy:Record<string,{id:string;label:string}|null>;draft:FinancialDraft|null;final:FinancialFinal|null;sourceDrift:Record<string,unknown>}
export interface FinancialPrefillFact{fieldPath:string;evidenceIdentity:string;value:string;unitCode:string;sourceEntityType:string;sourceEntityId:string;sourceVersion:string;sourceRecordedAt:string;comparison:string}
export interface FinancialPrefill{missionId:string;completionRevisionId:string;completionVersion:number;sources:Record<string,unknown>;facts:FinancialPrefillFact[];proposalDigest:string;draftRevisionId:string;draftVersion:number}
export interface FinancialRevisionSummary{id:string;revisionNumber:number;status:'DRAFT'|'FINAL';rowVersion:number;predecessorRevisionId:string|null;correctionReason:string|null;formulaVersion:'FINANCIAL_ACTUAL_V1';finalisedAt:string|null;finalisedByInternalUserId:string|null;current:boolean;activeDraft:boolean}
export interface FinancialRevisionHistory{schemaVersion:'FINANCIAL_ACTUAL_REVISION_HISTORY_V1';financialActualId:string;reference:string;archivedAt:string|null;currentFinalRevisionId:string|null;activeDraftRevisionId:string|null;rows:FinancialRevisionSummary[];nextBeforeRevisionNumber:number|null}
export interface FinancialHistoricalRevision{schemaVersion:'FINANCIAL_ACTUAL_HISTORICAL_REVISION_V1';financialActualId:string;reference:string;archivedAt:string|null;current:boolean;revision:FinancialFinal&{predecessorRevisionId:string|null;correctionReason:string|null}}
export interface FinancialCorrectionResult{schemaVersion:'FINANCIAL_ACTUAL_CORRECTION_V1';record:{id:string;reference:string;rowVersion:number;currentFinalRevisionId:string;activeDraftRevisionId:string};revision:{id:string;revisionNumber:number;status:'DRAFT';rowVersion:number;predecessorRevisionId:string;correctionReason:string}}
export interface FinancialArchiveResult{schemaVersion:'FINANCIAL_ACTUAL_ARCHIVE_V1';record:{id:string;reference:string;rowVersion:number;archivedAt:string;currentFinalRevisionId:string}}
