export type MaintenanceAssetClass = 'aircraft' | 'battery' | 'controller' | 'spray-kit' | 'truck' | 'trailer' | 'generator' | 'pump' | 'loader' | 'support-equipment';
export type MaintenanceScope = 'rpas' | 'fleet';
export type MaintenanceWorkflowStatus = 'reported' | 'assessed' | 'work-in-progress' | 'awaiting-release' | 'serviceable' | 'deferred' | 'unserviceable';
export type MaintenanceRecordType = 'defect' | 'inspection' | 'maintenance' | 'field-repair' | 'part-change' | 'reading' | 'firmware';
export type ScheduleMeter = 'calendar' | 'flight-hours' | 'component-hours' | 'cycles' | 'kilometres' | 'operating-hours';

export interface MaintenanceReadings { flightHours?: number; componentHours?: number; cycles?: number; kilometres?: number; operatingHours?: number; }
export interface MaintenanceAsset { id: string; tenantId: string; sourceId: string; scope: MaintenanceScope; assetClass: MaintenanceAssetClass; name: string; manufacturer?: string; model?: string; serialNumber?: string; uniqueMark?: string; priorMarks?: string[]; maximumGrossWeightKg?: number; parentAssetId?: string; status: 'serviceable' | 'unserviceable' | 'maintenance' | 'retired'; readings: MaintenanceReadings; firmwareVersion?: string; missionCritical?: boolean; createdAt: string; updatedAt: string; }
export interface MaintenanceSchedule { id: string; tenantId: string; assetId: string; title: string; meter: ScheduleMeter; dueAt: string | number; alternateMeter?: ScheduleMeter; alternateDueAt?: string | number; dueSoonBy: number; mandatory: boolean; source: 'manufacturer' | 'operator' | 'service-bulletin' | 'approval-condition' | 'internal'; instructions?: string; createdAt: string; updatedAt: string; }
export interface MaintenanceAttachment { id: string; name: string; dataUrl?: string; mimeType?: string; }
export interface MaintenanceCertification { certifiedBy: string; certifiedByName: string; authority: 'maintenance-controller' | 'authorised-maintainer'; certifiedAt: string; statement: string; }
export interface MaintenanceRecord { id: string; tenantId: string; assetId: string; type: MaintenanceRecordType; title: string; description: string; status: MaintenanceWorkflowStatus; occurredAt: string; createdAt: string; createdBy: string; createdByName: string; createdByRole: string; affectsServiceability: boolean; resultingServiceability: 'serviceable' | 'unserviceable' | 'unchanged'; location?: string; missionId?: string; readings?: MaintenanceReadings; procedureReference?: string; parts?: Array<{ name: string; partNumber?: string; serialNumber?: string; action: 'installed' | 'removed' }>; previousFirmwareVersion?: string; firmwareVersion?: string; verificationTest?: string; limitations?: string; deferUntil?: string; cost?: number; attachments: MaintenanceAttachment[]; certification?: MaintenanceCertification; amendmentOf?: string; amendmentReason?: string; }
export interface MaintenanceAuditEvent { id: string; tenantId: string; assetId: string; recordId?: string; action: 'record-created' | 'status-changed' | 'amended' | 'schedule-created' | 'asset-synchronised'; actorId: string; actorName: string; occurredAt: string; detail: string; }
export interface MaintenanceStore { assets: MaintenanceAsset[]; schedules: MaintenanceSchedule[]; records: MaintenanceRecord[]; auditEvents: MaintenanceAuditEvent[]; }
export type MaintenanceRecordInput = Omit<MaintenanceRecord, 'id' | 'tenantId' | 'createdAt' | 'createdBy' | 'createdByName' | 'createdByRole'>;
export type MaintenanceScheduleInput = Omit<MaintenanceSchedule, 'id' | 'tenantId' | 'createdAt' | 'updatedAt'>;
export interface ScheduleStatus { state: 'current' | 'due-soon' | 'due' | 'overdue'; remaining?: number; dueLabel: string; }
export interface MaintenanceActor { id?: string; name?: string; role?: string; maintenanceAuthority?: 'pic' | 'maintainer' | 'maintenance-controller' | 'authorised-maintainer'; }
