import React,{useMemo,useState}from'react';
import{Alert,Box,Button,Card,CardContent,MenuItem,Stack,TextField,Typography}from'@mui/material';
import ArrowBackIcon from'@mui/icons-material/ArrowBack';
import{useNavigate}from'react-router-dom';
import{useOperationalData}from'../contexts/OperationalDataContext';
import{createFinancialActualsApi}from'../services/financialActualsApi';

const api=createFinancialActualsApi();const today=()=>new Date().toISOString().slice(0,10);
export default function ActualCreate(){const navigate=useNavigate(),operational=useOperationalData(),[form,setForm]=useState({operatingLocationId:'',clientId:'',propertyId:'',fieldId:'',jobId:'',missionId:'',startDate:today(),endDate:today()}),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const properties=useMemo(()=>operational.properties.filter(x=>x.clientId===form.clientId),[operational.properties,form.clientId]),fields=useMemo(()=>operational.fields.filter(x=>x.propertyId===form.propertyId),[operational.fields,form.propertyId]),jobs=useMemo(()=>operational.jobs.filter(x=>x.clientId===form.clientId&&x.propertyId===form.propertyId&&x.fieldIds.includes(form.fieldId)),[operational.jobs,form]),missions=useMemo(()=>operational.missions.filter(x=>x.jobId===form.jobId&&x.operatingLocationId===form.operatingLocationId),[operational.missions,form]);
 const set=(key:string,value:string)=>setForm(previous=>({...previous,[key]:value,...(key==='clientId'?{propertyId:'',fieldId:'',jobId:'',missionId:''}:{}),...(key==='propertyId'?{fieldId:'',jobId:'',missionId:''}:{}),...(key==='fieldId'?{jobId:'',missionId:''}:{}),...(key==='jobId'?{missionId:''}:{})}));
 const valid=operational.status==='ready'&&Boolean(form.operatingLocationId&&form.clientId&&form.propertyId&&form.fieldId&&form.jobId&&form.startDate&&form.endDate&&form.startDate<=form.endDate);
 const create=async()=>{setSaving(true);setError('');try{const result=await api.create({...form,missionId:form.missionId||null,currencyCode:'AUD',formulaVersion:'FINANCIAL_ACTUAL_V1',provenance:[],workEntries:[],costLines:[]});navigate(`/financials/${result.actualId}`)}catch(e){setError(e instanceof Error?e.message:'Financial Actual could not be created.')}finally{setSaving(false)}};
 return <Box sx={{maxWidth:900,mx:'auto'}}><Button startIcon={<ArrowBackIcon/>} onClick={()=>navigate('/financials')} sx={{mb:2}}>Financial Actuals</Button><Typography component="h1" variant="h4" fontWeight={800} color="primary.dark">New Financial Actual</Typography><Typography color="text.secondary" mb={3}>Choose the authoritative operational context, then open a server-backed Draft.</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{operational.status!=='ready'&&<Alert severity={operational.status==='error'?'error':'info'} sx={{mb:2}}>Authoritative operational context is {operational.status}.</Alert>}<Card variant="outlined"><CardContent><Typography variant="h6" mb={2}>Context</Typography><Stack spacing={2}><TextField select label="Operating location" value={form.operatingLocationId} onChange={e=>set('operatingLocationId',e.target.value)} disabled={operational.status!=='ready'}>{operational.operatingLocations.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><TextField select label="Client" value={form.clientId} onChange={e=>set('clientId',e.target.value)}>{operational.clients.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><TextField select label="Property" value={form.propertyId} onChange={e=>set('propertyId',e.target.value)} disabled={!form.clientId}>{properties.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><TextField select label="Field" value={form.fieldId} onChange={e=>set('fieldId',e.target.value)} disabled={!form.propertyId}>{fields.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><TextField select label="Job" value={form.jobId} onChange={e=>set('jobId',e.target.value)} disabled={!form.fieldId}>{jobs.map(x=><MenuItem key={x.id} value={x.id}>{x.reference}</MenuItem>)}</TextField><TextField select label="Mission (optional)" value={form.missionId} onChange={e=>set('missionId',e.target.value)} disabled={!form.jobId}><MenuItem value="">No Mission</MenuItem>{missions.map(x=><MenuItem key={x.id} value={x.id}>{x.missionNumber}</MenuItem>)}</TextField><Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField type="date" label="Start date" value={form.startDate} onChange={e=>set('startDate',e.target.value)} InputLabelProps={{shrink:true}} fullWidth/><TextField type="date" label="End date" value={form.endDate} onChange={e=>set('endDate',e.target.value)} InputLabelProps={{shrink:true}} fullWidth/></Stack><Button variant="contained" disabled={!valid||saving} onClick={create}>{saving?'Creating…':'Create authoritative Draft'}</Button></Stack></CardContent></Card></Box>}
