import React from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Divider, Grid, LinearProgress, MenuItem, Skeleton, Stack, TextField, Typography } from '@mui/material';
import { createComplianceApi } from '../services/complianceApi';

const state=(value:any,missing='Missing')=>{if(!value)return missing;const days=Number(value.daysRemaining);if(Number.isFinite(days)){if(days<0)return'Expired';if(days<=30)return'Due 30 days';if(days<=90)return'Due 90 days';}return value.status==='UNDER_REVIEW'?'Under review':value.status==='SUPERSEDED'?'Superseded':value.status==='NOT_APPLICABLE'?'Not applicable':'Current';};
const colour=(status:string):'success'|'warning'|'error'|'info'|'default'=>status==='Current'?'success':status==='Expired'||status==='Missing'?'error':status.startsWith('Due')?'warning':status==='Under review'?'info':'default';

export default function CasaComplianceOverview(){
 const api=React.useMemo(()=>createComplianceApi(),[]),[data,setData]=React.useState<any>(null),[error,setError]=React.useState(''),[message,setMessage]=React.useState('');
 const[calendarView,setCalendarView]=React.useState('Next 90 days'),[recordType,setRecordType]=React.useState('ALL');
 const[reoc,setReoc]=React.useState({instrumentNumber:'',issueDate:'',expiryDate:'',holder:'',arn:'',conditions:''}),[reocFile,setReocFile]=React.useState<File|null>(null);
 const[manual,setManual]=React.useState({title:'RPAS Operations Manual',effectiveDate:'',reviewDueDate:''}),[manualFile,setManualFile]=React.useState<File|null>(null);
 const load=React.useCallback(()=>api.overview().then(setData).catch(e=>setError(e.message)),[api]);React.useEffect(()=>{void load()},[load]);
 const saveReoc=async()=>{if(!reoc.instrumentNumber||!reoc.expiryDate||!reocFile)return;try{await api.saveInstrument({operation:'CREATE',instrumentType:'REOC',instrumentNumber:reoc.instrumentNumber,issueDate:reoc.issueDate||null,expiryDate:reoc.expiryDate,status:'CURRENT',scope:{legalCertificateHolder:reoc.holder,organisationArn:reoc.arn},conditions:reoc.conditions.split('\n').filter(Boolean)},reocFile);setMessage('ReOC certificate and protected evidence saved.');await load();}catch(e){setError(e instanceof Error?e.message:'ReOC could not be saved.')}};
 const publishManual=async()=>{if(!manual.effectiveDate||!manualFile)return;try{await api.publishManual({...manual,documentId:data?.operationsManual?.document_id,expectedVersion:data?.operationsManual?.document_row_version},manualFile);setMessage('Operations Manual version published immutably.');await load();}catch(e){setError(e instanceof Error?e.message:'Operations Manual could not be published.')}};
 if(error)return<Alert severity="error">{error}</Alert>;if(!data)return<Stack spacing={2}><Typography variant="h3">CASA Compliance Overview</Typography><Skeleton height={180}/><Skeleton height={180}/></Stack>;
 const health=data.healthScore,events=(data.calendar?.events||[]).filter((event:any)=>recordType==='ALL'||event.recordType===recordType).filter((event:any)=>{const days=Number(event.daysRemaining);if(calendarView==='Next 90 days')return days>=0&&days<=90;if(calendarView==='Overdue')return days<0;if(calendarView==='Due soon')return days>=0&&days<=30;if(calendarView==='Completed')return event.state==='COMPLETED';return true;});
 const cards=[['ReOC',state(data.reoc),data.reoc?.instrument_number||'No ReOC recorded'],['Operations Manual',state(data.operationsManual),data.operationsManual?`Version ${data.operationsManual.version_number}`:'No published manual'],['Personnel Credentials',data.personnel?.missingCertificates?'Missing':data.personnel?.unverifiedCertificates?'Under review':'Current',`${data.personnel?.missingCertificates||0} missing · ${data.personnel?.unverifiedCertificates||0} under review`],['Aircraft Approvals',data.aircraft?.missingEvidence?'Missing':'Current',`${data.aircraft?.missingEvidence||0} missing evidence`],['Training',data.training?.outstanding?'Due 30 days':'Current',`${data.training?.outstanding||0} outstanding`],['Checklists',data.checklists?.missing?'Missing':'Current',`${data.checklists?.missing||0} missing`],['Missing Evidence',data.warnings?.missingEvidence?'Missing':'Current',`${data.warnings?.missingEvidence||0} records`],['Renewals',data.warnings?.renewalsOverdue?'Expired':'Current',`${data.warnings?.renewalsOverdue||0} overdue`],['Retention & Legal Hold',data.warnings?.legalHolds?'Under review':'Current',`${data.warnings?.legalHolds||0} active legal holds`]];
 return <Box sx={{maxWidth:1400,mx:'auto'}}><Stack spacing={1} sx={{mb:3}}><Typography variant="h3" fontWeight={800}>CASA Compliance Overview</Typography><Typography color="text.secondary">Authoritative Australian Part 101 compliance status for this organisation. Status is evidence-based; missing records are shown, never inferred.</Typography></Stack>{message&&<Alert severity="success" sx={{mb:2}}>{message}</Alert>}
  {health&&<Card variant="outlined" sx={{mb:2}}><CardContent><Stack spacing={2}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="overline">Compliance health</Typography><Typography variant="h3" fontWeight={900}>{health.percentage}%</Typography><Stack direction="row" spacing={1} alignItems="center"><Chip color={health.status==='CRITICAL'?'error':health.status==='STRONG'?'success':'warning'} label={String(health.status).replaceAll('_',' ')}/><Typography variant="caption">{health.modelVersion}</Typography></Stack></Box><Alert severity="info" sx={{maxWidth:620}}>Compliance health based on records currently held in Spray Command. This is operational guidance, not legal certification.</Alert></Stack><LinearProgress variant="determinate" value={Math.max(0,Math.min(100,health.percentage))}/>{health.criticalBlockers?.map((blocker:any)=><Alert key={`${blocker.criticalRuleCode}:${blocker.sourceEntityId||'missing'}`} severity="error"><Typography fontWeight={800}>{blocker.reason}</Typography><Typography variant="caption">{blocker.criticalRuleCode} v{blocker.criticalRuleVersion} · {blocker.affectedArea}</Typography>{blocker.route&&<Button size="small" href={blocker.route}>Open source</Button>}</Alert>)}<Grid container spacing={1}>{health.categories?.map((category:any)=><Grid key={category.code} size={{xs:12,md:6,lg:4}}><Card variant="outlined"><CardContent><Typography fontWeight={800}>{category.label}</Typography><Typography variant="h6">{category.earnedPoints} / {category.weight}</Typography><Typography variant="caption">{category.counts?.assessed||0} assessed · {category.counts?.missing||0} missing · {category.counts?.blocking||0} blocking</Typography></CardContent></Card></Grid>)}</Grid></Stack></CardContent></Card>}
  <Card variant="outlined" sx={{mb:2}}><CardContent><Stack spacing={2}><Box><Typography variant="h5" fontWeight={800}>Compliance Calendar</Typography><Typography color="text.secondary">A derived timeline of authoritative obligations. Complete work in its source record.</Typography></Box><Stack direction="row" flexWrap="wrap" gap={1}>{['Next 90 days','Agenda','Month','Overdue','Due soon','Completed'].map(view=><Button key={view} variant={calendarView===view?'contained':'outlined'} onClick={()=>setCalendarView(view)}>{view}</Button>)}</Stack><TextField select size="small" label="Record type" value={recordType} onChange={e=>setRecordType(e.target.value)} sx={{maxWidth:320}}><MenuItem value="ALL">All record types</MenuItem>{(data.calendar?.facets?.recordTypes||[]).map((type:string)=><MenuItem key={type} value={type}>{type}</MenuItem>)}</TextField><Divider/>{events.length===0?<Alert severity="info">No authorised obligations in this view.</Alert>:events.map((event:any)=><Stack key={event.eventKey} direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1} sx={{py:1}}><Box><Typography fontWeight={800}>{event.title}</Typography><Typography variant="body2" color="text.secondary">{event.dueDate} · {String(event.state).replaceAll('_',' ')}</Typography><Typography variant="body2">{event.requiredAction}</Typography></Box>{event.route&&<Button href={event.route}>Open source</Button>}</Stack>)}</Stack></CardContent></Card>
  <Grid container spacing={2}>{cards.map(([title,status,detail])=><Grid key={title} size={{xs:12,sm:6,lg:4}}><Card variant="outlined" sx={{height:'100%'}}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Typography variant="h6" fontWeight={800}>{title}</Typography><Chip size="small" label={status} color={colour(status)}/></Stack><Typography sx={{mt:2}}>{detail}</Typography></CardContent></Card></Grid>)}</Grid>
  <Grid container spacing={2} sx={{mt:1}}><Grid size={{xs:12,lg:6}}><Card variant="outlined"><CardContent><Stack spacing={1.5}><Typography variant="h6" fontWeight={800}>ReOC and organisation certificate</Typography><TextField label="ReOC number" value={reoc.instrumentNumber} onChange={e=>setReoc(v=>({...v,instrumentNumber:e.target.value}))}/><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField fullWidth type="date" label="Issue date" InputLabelProps={{shrink:true}} value={reoc.issueDate} onChange={e=>setReoc(v=>({...v,issueDate:e.target.value}))}/><TextField required fullWidth type="date" label="Expiry date" InputLabelProps={{shrink:true}} value={reoc.expiryDate} onChange={e=>setReoc(v=>({...v,expiryDate:e.target.value}))}/></Stack><TextField label="Legal certificate holder" value={reoc.holder} onChange={e=>setReoc(v=>({...v,holder:e.target.value}))}/><TextField label="Organisation ARN" value={reoc.arn} onChange={e=>setReoc(v=>({...v,arn:e.target.value}))}/><TextField multiline minRows={2} label="Certificate conditions" value={reoc.conditions} onChange={e=>setReoc(v=>({...v,conditions:e.target.value}))}/><Button component="label" variant="outlined">{reocFile?.name||'Upload ReOC certificate'}<input hidden type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e=>setReocFile(e.target.files?.[0]||null)}/></Button><Button variant="contained" disabled={!reoc.instrumentNumber||!reoc.expiryDate||!reocFile} onClick={()=>void saveReoc()}>Save authoritative ReOC</Button></Stack></CardContent></Card></Grid>
   <Grid size={{xs:12,lg:6}}><Card variant="outlined"><CardContent><Stack spacing={1.5}><Typography variant="h6" fontWeight={800}>Controlled Operations Manual</Typography><Alert severity="info">Publishing creates a new immutable version. Existing Mission evidence and earlier manual versions remain unchanged.</Alert><TextField label="Document title" value={manual.title} onChange={e=>setManual(v=>({...v,title:e.target.value}))}/><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField required fullWidth type="date" label="Effective date" InputLabelProps={{shrink:true}} value={manual.effectiveDate} onChange={e=>setManual(v=>({...v,effectiveDate:e.target.value}))}/><TextField fullWidth type="date" label="Review due date" InputLabelProps={{shrink:true}} value={manual.reviewDueDate} onChange={e=>setManual(v=>({...v,reviewDueDate:e.target.value}))}/></Stack><Button component="label" variant="outlined">{manualFile?.name||'Upload Operations Manual'}<input hidden type="file" accept="application/pdf" onChange={e=>setManualFile(e.target.files?.[0]||null)}/></Button><Button variant="contained" disabled={!manual.effectiveDate||!manualFile} onClick={()=>void publishManual()}>Publish controlled manual version</Button></Stack></CardContent></Card></Grid></Grid>
 </Box>;
}
