import React from 'react';
import {Alert,Box,Button,Card,CardContent,Chip,Collapse,Divider,Grid,LinearProgress,MenuItem,Skeleton,Stack,TextField,Typography}from'@mui/material';
import {useNavigate}from'react-router-dom';
import {createComplianceApi}from'../services/complianceApi';

type Tone='success'|'warning'|'error'|'info'|'default';
const evaluatedLabel=(value:string)=>value?new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit',timeZone:'Australia/Brisbane'}).format(new Date(value)):'';
const tone=(status:string):Tone=>status==='Current'||status==='Complete'?'success':status==='Missing'||status==='Expired'||status==='Blocked'?'error':status==='Due soon'||status==='Attention required'?'warning':status==='Under review'?'info':'default';
const categoryStatus=(counts:any)=>counts?.blocking?'Blocked':counts?.missing||counts?.expired?'Missing':counts?.due30||counts?.due90?'Due soon':'Current';
const issueCopy=(blocker:any)=>{
 const code=String(blocker?.criticalRuleCode||'');
 if(code==='REOC_MISSING')return{title:'ReOC certificate missing',reason:'Upload your current ReOC certificate so Spray Command can assess the organisation’s operating authority.',action:'Upload ReOC',panel:'reoc'};
 if(code==='REOC_EVIDENCE_MISSING')return{title:'ReOC certificate evidence missing',reason:'Add the current ReOC certificate evidence to clear this critical issue.',action:'Upload ReOC',panel:'reoc'};
 if(code==='REOC_EXPIRED')return{title:'ReOC certificate expired',reason:'Add the renewed ReOC certificate before relying on the organisation’s operating authority.',action:'Upload ReOC',panel:'reoc'};
 if(code==='REQUIRED_PERSONNEL_CREDENTIAL_INVALID')return{title:'Personnel licence needs attention',reason:'Review the affected Personnel qualification before assigning operational work.',action:'View personnel',route:'/personnel'};
 if(code==='AIRCRAFT_NOT_SERVICEABLE'||code==='AIRCRAFT_TECHNICAL_OVERDUE')return{title:'Aircraft compliance needs attention',reason:'Review the aircraft technical record before assigning it to a Mission.',action:'Review aircraft',route:'/aircraft'};
 return{title:'Compliance action required',reason:blocker?.reason||'Review the supporting compliance record.',action:'Review issue',route:blocker?.route||'/compliance'};
};
const eventName=(event:any)=>{const type=String(event.recordType||'').toUpperCase();if(type.includes('REOC'))return'ReOC renewal due';if(type.includes('AIRCRAFT'))return'Aircraft technical review due';if(type.includes('CONTROLLED_DOCUMENT'))return'Operations Manual review due';if(type.includes('PERSONNEL'))return'Personnel licence review due';if(type.includes('CHECKLIST'))return'Checklist action due';return event.title||'Compliance action due';};
const eventState=(event:any)=>event.state==='DUE_30'||event.state==='DUE_90'?'Due soon':event.state==='EXPIRED_OVERDUE'?'Expired':event.state==='OPERATIONALLY_BLOCKING'?'Blocked':event.state==='MISSING'?'Missing':event.state==='COMPLETED'?'Complete':'Current';
const upcomingEventState=(event:any)=>{const days=Number(event.daysRemaining);return days>=0&&days<=90?'Due soon':eventState(event);};
const categoryReason=(key:string,status:string)=>{
 if(key==='REOC')return status==='Current'?'Your ReOC evidence is current.':status==='Missing'?'Your ReOC certificate evidence is missing.':'Your ReOC record needs attention.';
 if(key==='DOCUMENTS')return status==='Current'?'Your approved Operations Manual is current.':status==='Missing'?'Your approved Operations Manual has not yet been published.':'Your Operations Manual needs attention.';
 if(key==='PERSONNEL')return status==='Current'?'Required Personnel licences are current.':status==='Missing'?'Required Personnel licence evidence is missing.':'A Personnel licence needs attention.';
 if(key==='AIRCRAFT')return status==='Current'?'Aircraft technical evidence is current.':status==='Missing'?'Required aircraft technical evidence is missing.':'Aircraft technical evidence needs attention.';
 return status==='Current'?'Checklist reviews and corrective actions are current.':status==='Missing'?'No checklist or corrective-action evidence is available yet.':'A checklist review or corrective action needs attention.';
};

export default function CasaComplianceOverview(){
 const navigate=useNavigate();
 const api=React.useMemo(()=>createComplianceApi(),[]),[data,setData]=React.useState<any>(null),[error,setError]=React.useState(''),[message,setMessage]=React.useState('');
 const[calendarOpen,setCalendarOpen]=React.useState(false),[calendarView,setCalendarView]=React.useState('Next 90 days'),[recordType,setRecordType]=React.useState('ALL'),[issueDetails,setIssueDetails]=React.useState(false),[categoryDetails,setCategoryDetails]=React.useState<string|null>(null);
 const load=React.useCallback(()=>api.overview().then(setData).catch(e=>setError(e.message)),[api]);React.useEffect(()=>{void load()},[load]);
 if(error)return<Alert severity="error">{error}</Alert>;if(!data)return<Stack spacing={2}><Typography variant="h3">CASA Compliance</Typography><Skeleton height={220}/><Skeleton height={160}/></Stack>;

 const health=data.healthScore||{},blockers=health.criticalBlockers||[],primaryBlocker=blockers[0],primaryIssue=issueCopy(primaryBlocker),allEvents=data.calendar?.events||[],nextEvents=allEvents.filter((event:any)=>Number(event.daysRemaining)>=0&&Number(event.daysRemaining)<=90).slice(0,4);
 const categoryMap=new Map((health.categories||[]).map((category:any)=>[category.code,category]));
 const definitions=[
  {key:'REOC',label:'ReOC and Organisation',codes:['REOC'],weight:20,emptySummary:'No ReOC or organisation-authority evidence is available yet.',summary:(status:string)=>status==='Current'?'Organisation authority evidence is current.':'The organisation authority record needs attention.',action:'Manage ReOC certificate',panel:'reoc' as const},
  {key:'DOCUMENTS',label:'Operations Manual',codes:['DOCUMENTS'],weight:12,emptySummary:'No approved Operations Manual evidence is available yet.',summary:(status:string)=>status==='Current'?'The current approved manual is published.':'The approved Operations Manual is not yet published.',action:'Publish Operations Manual',panel:'manual' as const},
  {key:'PERSONNEL',label:'Personnel and Licences',codes:['PERSONNEL'],weight:15,emptySummary:'No Personnel qualification evidence is available yet.',summary:(status:string)=>status==='Current'?'Required Personnel qualifications held in Spray Command are current.':'One or more Personnel qualifications need attention.',action:'View personnel',route:'/personnel'},
  {key:'AIRCRAFT',label:'Aircraft and Technical',codes:['AIRCRAFT'],weight:15,emptySummary:'No aircraft technical evidence is available yet.',summary:(status:string)=>status==='Current'?'Aircraft technical evidence is current.':'Aircraft technical evidence needs attention.',action:'Review aircraft',route:'/aircraft'},
  {key:'CHECKLISTS',label:'Checklists and Actions',codes:['CHECKLISTS','RENEWALS'],weight:15,emptySummary:'No checklist or corrective-action evidence is available yet.',summary:(status:string)=>status==='Current'?'Checklist reviews and actions are up to date.':'A checklist review or corrective action needs attention.',action:'View checklists',route:'/compliance/checklists'},
 ];
 const categories=definitions.map(def=>{const matches=def.codes.map(code=>categoryMap.get(code)).filter(Boolean)as any[],counts=matches.reduce((sum:any,item:any)=>({assessed:sum.assessed+(item.counts?.assessed||0),missing:sum.missing+(item.counts?.missing||0),blocking:sum.blocking+(item.counts?.blocking||0),expired:sum.expired+(item.counts?.expired||0),due30:sum.due30+(item.counts?.due30||0),due90:sum.due90+(item.counts?.due90||0)}),{assessed:0,missing:0,blocking:0,expired:0,due30:0,due90:0}),earned=matches.reduce((n,item)=>n+Number(item.earnedPoints||0),0),weight=matches.length?matches.reduce((n,item)=>n+Number(item.weight||0),0):def.weight,status=matches.length?categoryStatus(counts):'Missing';return{...def,counts,earned,weight,status,summaryText:categoryReason(def.key,status),sources:matches.flatMap(item=>item.sources||[])};});
 const filteredEvents=allEvents.filter((event:any)=>recordType==='ALL'||event.recordType===recordType).filter((event:any)=>{const days=Number(event.daysRemaining);if(calendarView==='Next 90 days')return days>=0&&days<=90;if(calendarView==='Overdue')return days<0;if(calendarView==='Due soon')return days>=0&&days<=30;if(calendarView==='Completed')return event.state==='COMPLETED';return true;});
 const openEvidenceWorkspace=(panel:'reoc'|'manual')=>navigate(panel==='reoc'?'/compliance/reoc':'/compliance/operations-manual');
 const openPrimary=()=>{if(primaryIssue.panel)openEvidenceWorkspace(primaryIssue.panel as 'reoc'|'manual');else if(primaryIssue.route)navigate(primaryIssue.route);};

 return <Box sx={{maxWidth:1320,mx:'auto',pb:6}}>
  <Stack spacing={.75} sx={{mb:{xs:2.5,md:4}}}><Typography variant="overline" color="text.secondary" sx={{letterSpacing:1.6}}>CASA COMPLIANCE</Typography><Typography variant="h3" fontWeight={850} sx={{fontSize:{xs:'2rem',md:'2.75rem'}}}>Know what is current. Fix what is not.</Typography><Typography color="text.secondary" sx={{maxWidth:720}}>A clear view of the evidence Spray Command currently holds for your organisation.</Typography></Stack>
  {message&&<Alert severity="success" sx={{mb:2}}>{message}</Alert>}

  <Card sx={{mb:3,border:'1px solid',borderColor:primaryBlocker?'error.light':'success.light',boxShadow:'0 14px 42px rgba(16,48,29,.08)',overflow:'hidden'}}><CardContent sx={{p:{xs:2.25,md:4},'&:last-child':{pb:{xs:2.25,md:4}}}}><Grid container spacing={{xs:3,md:5}} alignItems="stretch">
   <Grid size={{xs:12,md:4}}><Stack spacing={1.5}><Typography variant="overline" color="text.secondary">Compliance health</Typography><Stack direction="row" alignItems="baseline" spacing={1}><Typography variant="h2" fontWeight={900} sx={{fontSize:{xs:'4rem',md:'5.25rem'},lineHeight:.9}}>{health.percentage}%</Typography></Stack><Chip label={health.status==='CRITICAL'?'Critical attention required':health.status==='STRONG'?'Current':'Attention required'} color={health.status==='CRITICAL'?'error':health.status==='STRONG'?'success':'warning'} sx={{alignSelf:'flex-start',fontWeight:800}}/><LinearProgress variant="determinate" value={Math.max(0,Math.min(100,health.percentage||0))} sx={{height:8,borderRadius:8}}/><Typography variant="body2" color="text.secondary">Last updated {evaluatedLabel(health.evaluationTimestamp)}</Typography></Stack></Grid>
   <Grid size={{xs:12,md:8}}><Stack spacing={2} sx={{height:'100%',justifyContent:'center'}}>{primaryBlocker?<><Box><Typography variant="overline" color="error.main">Needs attention now</Typography><Typography variant="h5" fontWeight={850} sx={{mt:.5}}>{primaryIssue.title}</Typography><Typography color="text.secondary" sx={{mt:.75,maxWidth:680}}>{primaryIssue.reason}</Typography></Box><Stack direction={{xs:'column',sm:'row'}} spacing={1.25}><Button variant="contained" color="error" size="large" onClick={openPrimary} sx={{minHeight:48}}>{primaryIssue.action}</Button><Button size="large" onClick={()=>setIssueDetails(v=>!v)} aria-expanded={issueDetails}>{issueDetails?'Hide issue details':'View issue details'}</Button>{blockers.length>1&&<Button size="large" onClick={()=>setIssueDetails(true)}>View all issues ({blockers.length})</Button>}</Stack><Collapse in={issueDetails} unmountOnExit><Stack spacing={1.25} sx={{p:2,bgcolor:'action.hover',borderRadius:2}}>{blockers.map((blocker:any)=><Box key={`${blocker.criticalRuleCode}:${blocker.sourceEntityId||'missing'}`}><Typography fontWeight={800}>{blocker.reason}</Typography><Typography variant="caption" display="block">Rule {blocker.criticalRuleCode} v{blocker.criticalRuleVersion} · Model {health.modelVersion}</Typography><Typography variant="caption" display="block">Source: {blocker.sourceEntityType} · {blocker.sourceEntityId||'No source record'}</Typography><Typography variant="caption" display="block">Record version {blocker.sourceRowVersion??'not available'} · Evaluated {evaluatedLabel(blocker.evaluationTimestamp)}</Typography></Box>)}</Stack></Collapse></>:<><Typography variant="h5" fontWeight={850}>No critical issues found</Typography><Typography color="text.secondary">Continue monitoring upcoming obligations and keep evidence current.</Typography></>}</Stack></Grid>
  </Grid><Alert severity="info" sx={{mt:3}}>This status reflects evidence currently held in Spray Command. It supports operational decisions but is not legal certification.</Alert></CardContent></Card>

  <Grid container spacing={2.5} sx={{mb:3}}><Grid size={{xs:12,lg:5}}><Card variant="outlined" sx={{height:'100%'}}><CardContent sx={{p:{xs:2,md:3}}}><Stack spacing={2}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="overline" color="text.secondary">UPCOMING</Typography><Typography variant="h5" fontWeight={850}>Next 90 days</Typography></Box><Button onClick={()=>setCalendarOpen(v=>!v)} aria-expanded={calendarOpen}>View calendar</Button></Stack>{nextEvents.length?nextEvents.map((event:any)=>{const state=upcomingEventState(event);return <Stack key={event.eventKey} direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1.5} sx={{py:1.5,borderTop:'1px solid',borderColor:'divider'}}><Box><Typography fontWeight={800}>{eventName(event)}</Typography><Chip size="small" label={state} color={tone(state)} sx={{mt:1}}/><Typography variant="body2" color="text.secondary" sx={{mt:.75}}>{Number(event.daysRemaining)} days remaining</Typography></Box>{event.route&&<Button href={event.route} sx={{alignSelf:{xs:'stretch',sm:'center'},minHeight:44}}>Open</Button>}</Stack>}):<Box sx={{py:3}}><Typography fontWeight={800}>No obligations due in the next 90 days</Typography><Typography color="text.secondary">Spray Command will show upcoming actions here.</Typography></Box>}</Stack></CardContent></Card></Grid>
   <Grid size={{xs:12,lg:7}}><Grid container spacing={2}>{categories.map(category=><Grid key={category.key} size={{xs:12,sm:6}}><Card variant="outlined" sx={{height:'100%'}}><CardContent><Stack spacing={1.5}><Stack direction="row" justifyContent="space-between" gap={1}><Typography fontWeight={850}>{category.label}</Typography><Chip size="small" label={category.status} color={tone(category.status)}/></Stack><Typography variant="body2" color="text.secondary" sx={{minHeight:{sm:42}}}>{category.summaryText}</Typography>{category.panel?<Button variant="contained" onClick={()=>openEvidenceWorkspace(category.panel!)} sx={{minHeight:44}}>{category.action}</Button>:<Button variant="contained" href={category.route} sx={{minHeight:44}}>{category.action}</Button>}<Button onClick={()=>setCategoryDetails(categoryDetails===category.key?null:category.key)} aria-expanded={categoryDetails===category.key} sx={{alignSelf:'flex-start'}}>View details</Button><Collapse in={categoryDetails===category.key} unmountOnExit><Stack spacing={1} sx={{pt:1}}><Typography variant="caption">Scoring: {category.earned} of {category.weight} points · {category.counts.assessed} assessed · {category.counts.missing} missing · {category.counts.blocking} blocking · {category.counts.due30+category.counts.due90} due soon</Typography>{category.sources.length?category.sources.map((source:any)=><Box key={`${source.sourceEntityType}:${source.sourceEntityId||source.reason}`} sx={{p:1.5,bgcolor:'action.hover',borderRadius:1.5}}><Typography variant="body2" fontWeight={750}>{source.reason}</Typography><Typography variant="caption" display="block">{source.sourceEntityType} · {source.sourceEntityId||'No source record'}</Typography><Typography variant="caption" display="block">Record version {source.sourceRowVersion??'not available'}</Typography>{source.route&&<Button size="small" href={source.route}>Open source record</Button>}</Box>):<Typography variant="body2" color="text.secondary">No detailed records in this category.</Typography>}</Stack></Collapse></Stack></CardContent></Card></Grid>)}</Grid></Grid></Grid>

  <Collapse in={calendarOpen} unmountOnExit><Card variant="outlined" sx={{mb:3}}><CardContent><Stack spacing={2}><Typography variant="h5" fontWeight={850}>Compliance calendar</Typography><Stack direction="row" flexWrap="wrap" gap={1}>{['Next 90 days','Agenda','Month','Overdue','Due soon','Completed'].map(view=><Button key={view} variant={calendarView===view?'contained':'outlined'} onClick={()=>setCalendarView(view)}>{view}</Button>)}</Stack><TextField select size="small" label="Record type" value={recordType} onChange={e=>setRecordType(e.target.value)} sx={{maxWidth:320}}><MenuItem value="ALL">All record types</MenuItem>{(data.calendar?.facets?.recordTypes||[]).map((type:string)=><MenuItem key={type} value={type}>{type}</MenuItem>)}</TextField><Divider/>{filteredEvents.length?filteredEvents.map((event:any)=><Stack key={event.eventKey} direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1} sx={{py:1}}><Box><Typography fontWeight={800}>{eventName(event)}</Typography><Typography variant="body2" color="text.secondary">{event.dueDate} · {eventState(event)}</Typography><Typography variant="body2">{event.requiredAction}</Typography></Box>{event.route&&<Button href={event.route}>Open</Button>}</Stack>):<Alert severity="info">No compliance actions in this view.</Alert>}</Stack></CardContent></Card></Collapse>

 </Box>;
}
