import React from 'react';
import {Alert,Box,Button,Card,CardContent,Checkbox,FormControlLabel,Grid,MenuItem,Stack,TextField,Typography} from '@mui/material';
import {createChecklistsApi} from '../services/checklistsApi';
import {WorkflowMaturityBoundary} from '../components/productMaturity/WorkflowMaturityBoundary';

const categories=['PRE_FLIGHT','POST_FLIGHT','AIRCRAFT_SETUP','EQUIPMENT_SETUP','BATTERY_HANDLING','CHEMICAL_LOADING','TANK_MIXING','SITE_SETUP','WEATHER','EMERGENCY_RESPONSE','MAINTENANCE','VEHICLE_TRAILER','WASHDOWN','NIGHT_OPERATIONS','SPECIAL_OPERATIONS','CUSTOM'];
const types=['YES_NO','PASS_FAIL','COMPLETE_INCOMPLETE','NUMERIC','TEXT','DATETIME','PERSONNEL','AIRCRAFT','EQUIPMENT','PHOTO','FILE','SIGNATURE','ACKNOWLEDGEMENT','CUSTOM_OPTIONS'];
const stages=['PLANNING','PRE_FLIGHT','OPERATIONAL','COMPLETION','POST_MISSION'];
const blankFailure={comment:false,photo:false,file:false,action:false,signoff:false,repeat:false};

function ChecklistAdministration(){
 const api=React.useMemo(()=>createChecklistsApi(),[]),[templates,setTemplates]=React.useState<any[]>([]),[open,setOpen]=React.useState(false),[editing,setEditing]=React.useState<any>(null),[message,setMessage]=React.useState(''),[name,setName]=React.useState(''),[category,setCategory]=React.useState('PRE_FLIGHT'),[stage,setStage]=React.useState('PRE_FLIGHT'),[prompt,setPrompt]=React.useState(''),[itemType,setItemType]=React.useState('PASS_FAIL'),[mandatory,setMandatory]=React.useState(true),[items,setItems]=React.useState<any[]>([]),[failure,setFailure]=React.useState(blankFailure);
 const load=React.useCallback(()=>api.templates().then(setTemplates).catch(e=>setMessage(e.message)),[api]);React.useEffect(()=>{void load()},[load]);
 const reset=()=>{setEditing(null);setName('');setCategory('PRE_FLIGHT');setStage('PRE_FLIGHT');setItems([]);setPrompt('');setMandatory(true);setFailure(blankFailure);setOpen(true)};
 const latest=(template:any)=>[...(template.checklist_template_versions||[])].sort((a:any,b:any)=>b.version_number-a.version_number)[0];
 const nextVersion=(template:any)=>{const version=latest(template);setEditing(template);setName(template.name);setCategory(template.category);setStage(template.applicable_lifecycle_stages?.[0]||'PRE_FLIGHT');setItems((version?.sections||[]).flatMap((section:any)=>section.items||[]));setOpen(true)};
 const add=()=>{if(!prompt.trim())return;setItems(current=>[...current,{id:`item-${Date.now()}`,prompt:prompt.trim(),type:itemType,mandatory,required_comment_on_failure:failure.comment,required_photo_on_failure:failure.photo,required_file_on_failure:failure.file,create_corrective_action_on_failure:failure.action,requires_signoff_on_failure:failure.signoff,repeat_required_on_failure:failure.repeat}]);setPrompt('')};
 const move=(index:number,delta:number)=>setItems(current=>{const next=[...current],target=index+delta;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target],next[index]];return next});
 const publish=async()=>{try{let list=items;if(prompt.trim()){list=[...items,{id:`item-${Date.now()}`,prompt:prompt.trim(),type:itemType,mandatory,required_comment_on_failure:failure.comment,required_photo_on_failure:failure.photo,required_file_on_failure:failure.file,create_corrective_action_on_failure:failure.action,requires_signoff_on_failure:failure.signoff,repeat_required_on_failure:failure.repeat}];setItems(list)}if(!name.trim()||!list.length)return;const record=editing||((await api.createTemplate({stableCode:`CUSTOM_${Date.now()}`,name:name.trim(),category,applicableLifecycleStages:[stage]})).record);await api.publish({templateId:record.id,expectedVersion:record.row_version||record.rowVersion||1,changeSummary:editing?'New controlled version':'Initial controlled version',effectiveAt:new Date().toISOString(),sections:[{id:'section-1',title:'Checks',items:list}],visibilityRules:[],signoffPolicy:{mode:'COMPLETING_PERSONNEL'}});setMessage('Controlled checklist version published. Earlier versions remain immutable.');setOpen(false);setEditing(null);await load()}catch(e){setMessage(e instanceof Error?e.message:'Checklist could not be published.')}};
 return <><Stack direction="row" justifyContent="flex-end" sx={{mb:3}}><Button variant="contained" onClick={reset}>Create checklist</Button></Stack>{message&&<Alert severity={message.includes('published')?'success':'error'} sx={{mb:2}}>{message}</Alert>}
 {open&&<Card variant="outlined" sx={{mb:3}}><CardContent><Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Checklist name" inputProps={{'aria-label':'Checklist name'}} value={name} onChange={e=>setName(e.target.value)}/></Grid><Grid size={{xs:12,md:3}}><TextField select fullWidth label="Category" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><MenuItem key={x} value={x}>{x.replaceAll('_',' ')}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,md:3}}><TextField select fullWidth label="Lifecycle stage" value={stage} onChange={e=>setStage(e.target.value)}>{stages.map(x=><MenuItem key={x} value={x}>{x.replaceAll('_',' ')}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,md:8}}><TextField fullWidth label="Item prompt" inputProps={{'aria-label':'Item prompt'}} value={prompt} onChange={e=>setPrompt(e.target.value)}/></Grid><Grid size={{xs:12,md:4}}><TextField select fullWidth label="Response type" value={itemType} onChange={e=>setItemType(e.target.value)}>{types.map(x=><MenuItem key={x} value={x}>{x.replaceAll('_',' ')}</MenuItem>)}</TextField></Grid><Grid size={{xs:12}}><FormControlLabel control={<Checkbox checked={mandatory} onChange={(_,checked)=>setMandatory(checked)}/>} label="Mandatory item"/><Stack direction="row" useFlexGap flexWrap="wrap">{([['comment','Comment required on failure'],['photo','Photo required on failure'],['file','File required on failure'],['action','Create corrective action on failure'],['signoff','Sign-off required on failure'],['repeat','Repeat required on failure']]as const).map(([key,label])=><FormControlLabel key={key} control={<Checkbox checked={failure[key]} onChange={(_,checked)=>setFailure(v=>({...v,[key]:checked}))}/>} label={label}/>)}</Stack><Button variant="outlined" onClick={add}>Add item</Button></Grid>{items.map((item,index)=><Grid size={{xs:12}} key={item.id}><Alert severity="info" action={<Stack direction="row"><Button disabled={index===0} onClick={()=>move(index,-1)}>Up</Button><Button disabled={index===items.length-1} onClick={()=>move(index,1)}>Down</Button><Button color="error" onClick={()=>setItems(v=>v.filter(x=>x.id!==item.id))}>Remove</Button></Stack>}>{index+1}. {item.prompt} · {item.type.replaceAll('_',' ')} · {item.mandatory?'Mandatory':'Optional'}</Alert></Grid>)}<Grid size={{xs:12}}><Stack direction="row" spacing={1}><Button variant="contained" disabled={!name.trim()||(!items.length&&!prompt.trim())} onClick={()=>void publish()}>Publish controlled version</Button><Button onClick={()=>setOpen(false)}>Cancel</Button></Stack></Grid></Grid></CardContent></Card>}
 {templates.length===0?<Alert severity="info">No controlled checklists yet.</Alert>:<Grid container spacing={2}>{templates.map(t=><Grid key={t.id} size={{xs:12,md:6}}><Card variant="outlined"><CardContent><Typography variant="h6" fontWeight={800}>{t.name}</Typography><Typography>{String(t.category).replaceAll('_',' ')} · {t.status}</Typography>{[...(t.checklist_template_versions||[])].sort((a:any,b:any)=>b.version_number-a.version_number).map((v:any)=><Typography variant="body2" key={v.id}>Version {v.version_number} · {v.status}</Typography>)}<Button sx={{mt:1}} variant="outlined" onClick={()=>nextVersion(t)}>Create next version</Button></CardContent></Card></Grid>)}</Grid>}
 </>
}
export default function ControlledChecklists(){return<Box sx={{maxWidth:1200,mx:'auto'}}><Stack spacing={.5} sx={{mb:3}}><Typography variant="h3" fontWeight={800}>Checklists</Typography><Typography color="text.secondary">Organisation-controlled operational checklists. Published versions are immutable.</Typography></Stack><WorkflowMaturityBoundary moduleCode="controlled-checklists" workflowCode="administration"><ChecklistAdministration/></WorkflowMaturityBoundary></Box>}
