import React,{useEffect,useRef,useState}from'react';
import{Alert,Box,Button,Card,CardActionArea,CardContent,Chip,CircularProgress,Stack,Typography}from'@mui/material';
import AddIcon from'@mui/icons-material/Add';
import{useNavigate}from'react-router-dom';
import{createFinancialActualsApi}from'../services/financialActualsApi';
import type{FinancialSummary}from'../types/financialActuals';
import{useAuth}from'../contexts/AuthContext';
import{authorityScopeKey}from'../services/authorityScope';

const api=createFinancialActualsApi();
const money=(value?:string|null)=>value==null?'—':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',minimumFractionDigits:2}).format(Number(value));
export default function FinancialsList(){const navigate=useNavigate(),{user}=useAuth(),scope=authorityScopeKey(user),scopeRef=useRef(scope),generation=useRef(0),[resolved,setResolved]=useState<{scope:string;rows:FinancialSummary[]}|null>(null),[loadingScope,setLoadingScope]=useState(scope),[errorState,setErrorState]=useState<{scope:string;message:string}|null>(null);scopeRef.current=scope;const rows=resolved?.scope===scope?resolved.rows:[],loading=loadingScope===scope,error=errorState?.scope===scope?errorState.message:'';
 useEffect(()=>{const active=++generation.current;setLoadingScope(scope);setErrorState(null);api.list({pageSize:50}).then(page=>{if(active===generation.current&&scopeRef.current===scope)setResolved({scope,rows:page.rows})}).catch(e=>{if(active===generation.current&&scopeRef.current===scope)setErrorState({scope,message:e instanceof Error?e.message:'Financial Actuals could not be loaded.'})}).finally(()=>{if(active===generation.current&&scopeRef.current===scope)setLoadingScope('')});return()=>{generation.current++}},[scope]);
 return <Box sx={{maxWidth:1200,mx:'auto'}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Chip label="Development acceptance" size="small" color="warning"/><Typography variant="h4" component="h1" fontWeight={800} color="primary.dark">Financial Actuals</Typography><Typography color="text.secondary">Authoritative Drafts and frozen FINAL results.</Typography></Box><Button variant="contained" startIcon={<AddIcon/>} onClick={()=>navigate('/financials/new')}>New Financial Actual</Button></Stack>{loading&&<CircularProgress aria-label="Loading Financial Actuals"/>}{error&&<Alert severity="error">{error}</Alert>}{!loading&&!error&&rows.length===0&&<Alert severity="info">No authoritative Financial Actuals yet.</Alert>}<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:2}}>{rows.map(row=><Box key={row.id}><Card variant="outlined" sx={{borderLeft:4,borderLeftColor:row.lifecycle==='FINAL'?'success.main':'warning.main'}}><CardActionArea onClick={()=>navigate(`/financials/${row.id}`)}><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h6">{row.reference}</Typography><Chip label={row.lifecycle} color={row.lifecycle==='FINAL'?'success':'warning'} size="small"/></Stack><Typography fontWeight={700}>{row.client.label} · {row.job.label}</Typography><Typography variant="body2" color="text.secondary">{row.mission?.label??'No Mission'} · {row.operatingLocation.label}</Typography>{row.lifecycle==='DRAFT'?<Alert severity="warning" sx={{mt:2}}>Draft revision {row.activeDraft?.revisionNumber} requires review.</Alert>:<Box sx={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:1,mt:1}}><Box><Typography variant="caption">Revenue</Typography><Typography fontWeight={700}>{money(row.finalCalculation?.revenue)}</Typography></Box><Box><Typography variant="caption">Gross profit</Typography><Typography fontWeight={700}>{money(row.finalCalculation?.grossProfit)}</Typography></Box></Box>}{row.sourceDrift==='CHANGED'&&<Alert severity="warning" sx={{mt:2}}>Operational source changed after acceptance.</Alert>}</CardContent></CardActionArea></Card></Box>)}</Box></Box>}
