import React from 'react';import {Alert,Box,Button,Card,CardContent,Checkbox,FormControlLabel,Grid,MenuItem,Stack,TextField,Typography} from '@mui/material';import {useOperationalData} from '../contexts/OperationalDataContext';import {createPersonnelApi,PersonnelApiError} from '../services/personnelApi';import {PersonnelRecord,PersonnelRole} from '../types/personnel';
import PersonnelCredentialEditor from '../components/personnel/PersonnelCredentialEditor';
import PersonnelIdentityLinker from '../components/personnel/PersonnelIdentityLinker';import{createPersonnelIdentityApi}from'../services/personnelIdentityApi';import{createOperationalApi}from'../services/operationalApi';
const roles:PersonnelRole[]=['pilot_in_command','pilot','observer','ground_crew','chemical_operator','loader','supervisor','maintenance_support','other'];
export default function Personnel(){const operational=useOperationalData(),api=React.useMemo(()=>createPersonnelApi(),[]),identityApi=React.useMemo(()=>createPersonnelIdentityApi(),[]),[canManageIdentity,setCanManageIdentity]=React.useState(false),[records,setRecords]=React.useState<PersonnelRecord[]>([]),[name,setName]=React.useState(''),[location,setLocation]=React.useState(''),[selectedRoles,setSelectedRoles]=React.useState<PersonnelRole[]>([]),[status,setStatus]=React.useState<'loading'|'ready'|'saving'|'error'>('loading'),[message,setMessage]=React.useState('');
 const load=React.useCallback(async()=>{setStatus('loading');try{const[personnel,session]=await Promise.all([api.list(),createOperationalApi().session()]);setRecords(personnel);setCanManageIdentity(session.permissions.includes('personnel.identity.manage'));setStatus('ready');}catch(e){setMessage(e instanceof Error?e.message:'Personnel could not be loaded.');setStatus('error');}},[api]);React.useEffect(()=>{if(operational.mode==='remote')void load();},[load,operational.mode]);React.useEffect(()=>{if(!location&&operational.operatingLocations[0])setLocation(operational.operatingLocations[0].id);},[location,operational.operatingLocations]);
 if(operational.mode!=='remote')return <Alert severity="error">Authoritative Personnel requires the Production Beta backend. No legacy Personnel record is available.</Alert>;
 const create=async()=>{setMessage('');setStatus('saving');try{await api.create({fullName:name.trim(),engagementStatus:'employee',isActive:true,operatingLocationIds:[location],operationalRoles:selectedRoles});setName('');setSelectedRoles([]);await load();setMessage('Personnel record saved authoritatively.');}catch(e){setMessage(e instanceof PersonnelApiError?e.message:'Personnel could not be saved.');setStatus('ready');}};
 const archive=async(record:PersonnelRecord)=>{if(!window.confirm(`Archive ${record.fullName}?`))return;try{await api.archive(record.id,record.rowVersion);await load();}catch(e){setMessage(e instanceof Error?e.message:'Personnel could not be archived.');}};
 return <Box sx={{maxWidth:1200,mx:'auto'}}><Typography variant="h3" fontWeight={800} gutterBottom>Personnel</Typography><Alert severity="info" sx={{mb:2}}>Personnel are organisation-owned operational records. Creating a non-login person does not create a user account, seat, or permissions.</Alert>{message&&<Alert severity={message.includes('saved')?'success':'error'} sx={{mb:2}}>{message}</Alert>}<Card variant="outlined" sx={{mb:2}}><CardContent><Typography variant="h6" fontWeight={800} gutterBottom>Add Personnel</Typography><Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField fullWidth required label="Full name" value={name} onChange={e=>setName(e.target.value)}/></Grid><Grid size={{xs:12,md:6}}><TextField select fullWidth required label="Operating location" value={location} onChange={e=>setLocation(e.target.value)}>{operational.operatingLocations.map(l=><MenuItem key={l.id} value={l.id}>{l.name}</MenuItem>)}</TextField></Grid><Grid size={{xs:12}}><Stack direction="row" useFlexGap flexWrap="wrap">{roles.map(role=><FormControlLabel key={role} control={<Checkbox checked={selectedRoles.includes(role)} onChange={(_,checked)=>setSelectedRoles(current=>checked?[...current,role]:current.filter(r=>r!==role))}/>} label={role.replaceAll('_',' ')}/>)}</Stack></Grid><Grid size={{xs:12}}><Button variant="contained" disabled={!name.trim()||!location||status==='saving'} onClick={()=>void create()}>Create Personnel</Button></Grid></Grid></CardContent></Card>{status==='loading'?<Typography>Loading authoritative Personnel…</Typography>:<Stack spacing={1.5}>{records.map(record=><Card key={record.id} variant="outlined"><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={2}><Box sx={{flex:1}}><Typography variant="h6" fontWeight={800}>{record.fullName}</Typography><Typography color="text.secondary">{record.operationalRoles.join(', ')||'No operational role'} · {record.internalUserId?'Member-linked':'Non-login Personnel'}</Typography><Typography variant="body2" sx={{my:1}}>{record.credentials.length?record.credentials.map(credential=>`${credential.credential_type}${credential.expiry_date?` · expires ${credential.expiry_date}`:''}`).join(', '):'No credentials recorded'}</Typography><Stack direction="row" spacing={1} useFlexGap flexWrap="wrap"><PersonnelCredentialEditor personnelId={record.id} personnelName={record.fullName} api={api} onSaved={()=>void load()}/><PersonnelIdentityLinker personnel={record} canManage={canManageIdentity} api={identityApi} onChanged={()=>void load()}/></Stack></Box><Button color="error" onClick={()=>void archive(record)}>Archive</Button></Stack></CardContent></Card>)}</Stack>}</Box>;
}
