import React from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import MyLocationIcon from '@mui/icons-material/MyLocation';
import StarIcon from '@mui/icons-material/Star';
import StarBorderIcon from '@mui/icons-material/StarBorder';
import AirIcon from '@mui/icons-material/Air';
import NightsStayIcon from '@mui/icons-material/NightsStay';
import WbSunnyIcon from '@mui/icons-material/WbSunny';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { createOperationsBriefApi, BriefWeather, OperationsBrief, WeatherLocation } from '../services/operationsBriefApi';
import { selectRollingTwoHourly, weatherLocationKey } from '../utils/weatherOutlook';

const api = createOperationsBriefApi();
const time = (value: string) => value.match(/T(\d{2}:\d{2})/)?.[1] || new Date(value).toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit', hour12: false });
const day = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString('en-AU', { weekday: 'short', day: 'numeric' });
const providerTime = (value?:string, timezone?:string) => { if(!value)return '';try{return new Intl.DateTimeFormat('en-AU',{timeZone:timezone,hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));}catch{return time(value);} };
const factors = (value:any) => `Factors: ${value?.factors?.length?value.factors.join(', '):'No elevated proxy factors'}`;
const riskColour: Record<string,string> = { low:'#2e7d32', moderate:'#ed6c02', high:'#c62828' };
const directionDegrees: Record<string,number> = { N:0,NE:45,E:90,SE:135,S:180,SW:225,W:270,NW:315 };

function OutlookChart({hours}:{hours:any[]}) {
  const selected=selectRollingTwoHourly(hours,hours[0]?.time||'');
  const points=selected.map((hour,index)=>{const rating=hour.inversionPotential?.rating||'unknown',score=hour.inversionPotential?.score??0,previous=index>0?(selected[index-1].inversionPotential?.rating||'unknown'):rating;return{...hour,label:time(hour.time),inversionScore:score,inversionLabel:hour.inversionPotential?.label||'Unknown',inversionLow:rating==='low'||previous==='low'?score:null,inversionModerate:rating==='moderate'||previous==='moderate'?score:null,inversionHigh:rating==='high'||previous==='high'?score:null};});
  if(!points.length)return <Typography color="text.secondary">The two-hour outlook is not available.</Typography>;
  return <Box>
    <Typography variant="body2" color="text.secondary" sx={{mb:1}}>Two-hour view from now. Arrows show forecast wind direction; inversion is advisory and must be checked on site.</Typography>
    <Stack direction="row" gap={2} flexWrap="wrap" sx={{mb:1}} aria-label="Weather chart legend">
      <Typography variant="caption" fontWeight={800}><AirIcon sx={{fontSize:15,verticalAlign:'text-bottom',mr:.5}}/>Wind (km/h)</Typography>
      <Typography variant="caption" fontWeight={800}>Blue dashed: gusts</Typography>
      <Typography variant="caption" fontWeight={800}>Forecast inversion potential: <Box component="span" color="#2e7d32">Low</Box> / <Box component="span" color="#ed6c02">Medium</Box> / <Box component="span" color="#c62828">High</Box></Typography>
    </Stack>
    <Box sx={{width:'100%',height:320}} aria-label="Two-hour wind and inversion outlook">
      <ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{top:16,right:42,left:42,bottom:8}}>
        <CartesianGrid strokeDasharray="3 5" vertical={false}/><XAxis dataKey="label"/><YAxis yAxisId="wind" width={84} unit=" km/h" label={{value:'Wind (km/h)',angle:-90,position:'insideLeft'}}/><YAxis yAxisId="risk" width={88} orientation="right" domain={[0,2]} ticks={[0,1,2]} tickFormatter={value=>value===2?'High':value===1?'Medium':'Low'} label={{value:'Forecast inversion potential',angle:90,position:'insideRight'}}/>
        <Tooltip formatter={(value:any,name:string,props:any)=>name==='Forecast inversion potential'?[props.payload.inversionLabel,name]:[`${value} km/h`,name]} labelFormatter={label=>`${label} · wind ${points.find(item=>item.label===label)?.windDirection||'—'}`}/>
        <Line yAxisId="wind" type="monotone" dataKey="windSpeedKmh" name="Wind speed" stroke="#0f5132" strokeWidth={3} dot={(props:any)=><g key={`wind-${props.index}`} transform={`translate(${props.cx} ${props.cy}) rotate(${directionDegrees[props.payload.windDirection]||0})`}><circle r="8" fill="#fff" stroke="#0f5132"/><path d="M 0 -6 L 4 3 L 0 1 L -4 3 Z" fill="#0f5132"/></g>}/>
        <Line yAxisId="wind" type="monotone" dataKey="windGustKmh" name="Wind gusts" stroke="#3478a4" strokeWidth={2} strokeDasharray="6 4" dot={false}/>
        <Line yAxisId="risk" type="linear" dataKey="inversionLow" name="Forecast inversion potential" stroke="#2e7d32" strokeWidth={3} dot={false} connectNulls={false} tooltipType="none"/>
        <Line yAxisId="risk" type="linear" dataKey="inversionModerate" name="Forecast inversion potential" stroke="#ed6c02" strokeWidth={3} dot={false} connectNulls={false} tooltipType="none"/>
        <Line yAxisId="risk" type="linear" dataKey="inversionHigh" name="Forecast inversion potential" stroke="#c62828" strokeWidth={3} dot={false} connectNulls={false} tooltipType="none"/>
        <Line yAxisId="risk" type="linear" dataKey="inversionScore" name="Forecast inversion potential" stroke="transparent" dot={(props:any)=><circle key={`risk-${props.index}`} cx={props.cx} cy={props.cy} r={5} fill={riskColour[props.payload.inversionPotential?.rating]||'#64748b'} stroke="#fff" strokeWidth={2}/>}/>
      </LineChart></ResponsiveContainer>
    </Box>
    <Typography variant="caption" color="text.secondary">Times shown in provider local time. The bottom labels are forecast times; the coloured line uses the right-hand risk scale.</Typography>
    <Stack direction="row" gap={1} flexWrap="wrap" sx={{mt:1}}>{points.map((point,index)=><Chip icon={point.isDay?<WbSunnyIcon/>:<NightsStayIcon/>} key={point.time} size="small" label={`${index===0?'Now · ':''}${point.label} ${point.windDirection||'—'} · ${point.inversionLabel}`} sx={{borderLeft:`4px solid ${riskColour[point.inversionPotential?.rating]||'#64748b'}`}}/>)}</Stack>
  </Box>;
}

export default function WeatherCentre() {
  const [brief,setBrief]=React.useState<OperationsBrief|null>(null),[error,setError]=React.useState(''),[query,setQuery]=React.useState('');
  const [locating,setLocating]=React.useState(false),[searching,setSearching]=React.useState(false),[results,setResults]=React.useState<WeatherLocation[]>([]);
  const [advisoryWeather,setAdvisoryWeather]=React.useState<BriefWeather|null>(null),[recentSearches,setRecentSearches]=React.useState<WeatherLocation[]>([]),[favourites,setFavourites]=React.useState<WeatherLocation[]>([]);
  React.useEffect(()=>{api.read().then(setBrief).catch(e=>setError(e.message));},[]);
  React.useEffect(()=>{if(brief){setRecentSearches(brief.recentWeatherSearches||[]);setFavourites(brief.favouriteWeatherLocations||[]);}},[brief]);
  const useDeviceLocation=()=>{setLocating(true);navigator.geolocation.getCurrentPosition(async position=>{try{setAdvisoryWeather(await api.deviceWeather(position.coords.latitude,position.coords.longitude));}catch(e:any){setError(e.message);}finally{setLocating(false);}},event=>{setError(event.message||'Device location is unavailable.');setLocating(false);},{enableHighAccuracy:true,timeout:10000});};
  const searchLocations=async()=>{setSearching(true);setError('');try{setResults((await api.searchWeather(query)).results);}catch(e:any){setError(e.message);}finally{setSearching(false);}};
  const openSearchedLocation=async(location:WeatherLocation)=>{setSearching(true);setError('');try{const weather=await api.searchedWeather(location);setAdvisoryWeather(weather);setResults([]);setRecentSearches(weather.recentSearches||[]);setFavourites(weather.favouriteWeatherLocations||favourites);}catch(e:any){setError(e.message);}finally{setSearching(false);}};
  const toggleFavourite=async(location:WeatherLocation)=>{setError('');try{const saved=favourites.some(item=>weatherLocationKey(item)===weatherLocationKey(location));const data=saved?await api.unfavouriteWeather(location):await api.favouriteWeather(location);setFavourites(data.favouriteWeatherLocations);}catch(e:any){setError(e.message);}};
  if(!brief&&!error)return <Stack alignItems="center" sx={{py:10}}><CircularProgress/></Stack>;
  if(!brief)return <Alert severity="error">{error}</Alert>;
  const weather=advisoryWeather||brief.weather,placeLabel=weather.resolvedLocation?.label||brief.weather.resolvedLocation?.label||'Operating location not selected';
  const selected=weather.resolvedLocation,favourite=selected&&favourites.some(item=>weatherLocationKey(item)===weatherLocationKey(selected));
  const setOperatingLocation=async(id:string)=>{await api.selectLocation(id);setAdvisoryWeather(null);setBrief(await api.read());};
  return <Box sx={{maxWidth:1400,mx:'auto',pb:6}}>
    <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="overline" color="primary.main" fontWeight={900}>OPERATIONAL WEATHER</Typography><Typography variant="h3" fontWeight={900} color="primary.dark">Weather Centre</Typography><Typography variant="h6" fontWeight={800}>{placeLabel}</Typography><Typography variant="body2" color="text.secondary">{weather.sourceLabel?`Source: ${weather.sourceLabel}`:''}{weather.timezone?` · ${weather.timezone}`:''}{weather.retrievedAt?` · Updated ${providerTime(weather.retrievedAt,weather.timezone)}`:''}</Typography></Box>{'geolocation' in navigator&&<Button variant="outlined" startIcon={<MyLocationIcon/>} disabled={locating} onClick={useDeviceLocation}>{locating?'Locating…':'Use my current location'}</Button>}</Stack>
    <Alert severity="info" sx={{my:2.5}}>Weather, forecast inversion potential and Spray Score are decision support only. Check conditions on site; they do not authorise operations or replace operator judgement.</Alert>
    <Card sx={{mb:2.5}}><CardContent><Typography variant="h6" fontWeight={800}>Choose a weather location</Typography><Grid container spacing={1.5} sx={{mt:.5}}><Grid size={{xs:12,md:5}}><TextField fullWidth value={query} onChange={e=>setQuery(e.target.value)} label="Search weather location" placeholder="Suburb, town, postcode or address" onKeyDown={e=>{if(e.key==='Enter')searchLocations();}}/></Grid><Grid size={{xs:12,sm:6,md:2}}><Button fullWidth sx={{height:'100%'}} variant="contained" startIcon={<SearchIcon/>} disabled={searching||query.trim().length<3} onClick={searchLocations}>Search locations</Button></Grid>{brief.locations.length>1&&<Grid size={{xs:12,sm:6,md:5}}><Select fullWidth value={brief.location?.id||''} displayEmpty aria-label="Operating location" onChange={e=>setOperatingLocation(String(e.target.value))}><MenuItem value="" disabled>Choose operating location</MenuItem>{brief.locations.map(item=><MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</Select></Grid>}</Grid>
      {results.length>0&&<Stack spacing={1} sx={{mt:1.5}}>{results.map(item=><Button key={weatherLocationKey(item)} variant="outlined" onClick={()=>openSearchedLocation(item)} sx={{justifyContent:'flex-start'}}>{item.label}</Button>)}</Stack>}
      {selected&&weather.locationSource==='SEARCH'&&<Button sx={{mt:1.5}} startIcon={favourite?<StarIcon/>:<StarBorderIcon/>} aria-label={`${favourite?'Remove':'Add'} ${selected.label} ${favourite?'from':'to'} favourites`} onClick={()=>toggleFavourite(selected)}>{favourite?'Remove favourite':'Add to favourites'}</Button>}
      {favourites.length>0&&<Box sx={{mt:2}}><Typography fontWeight={800}>Favourite locations</Typography><Stack direction="row" gap={1} flexWrap="wrap" sx={{mt:1}}>{favourites.map(item=><Chip icon={<StarIcon/>} key={weatherLocationKey(item)} label={item.label} clickable onClick={()=>openSearchedLocation(item)} component="button"/>)}</Stack></Box>}
      {recentSearches.length>0&&<Stack direction="row" gap={1} flexWrap="wrap" alignItems="center" sx={{mt:2}}><Typography variant="body2" color="text.secondary">Recent searches</Typography>{recentSearches.map(item=><Chip key={weatherLocationKey(item)} label={item.label} clickable onClick={()=>openSearchedLocation(item)} component="button"/>)}</Stack>}{weather.locationSource==='SEARCH'&&<Alert severity="info" sx={{mt:2}}>Advisory search — Home and Mission defaults unchanged.</Alert>}
    </CardContent></Card>
    {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
    {weather.state!=='READY'||!weather.current?<Alert severity="warning">{weather.message||'Weather needs a valid operating-location address before it can be shown.'}</Alert>:<Grid container spacing={2.5}>
      <Grid size={{xs:12,md:5}}><Card><CardContent><Typography variant="h6" fontWeight={800}>Current conditions</Typography><Typography variant="h2" fontWeight={900} sx={{my:1}}>{Math.round(weather.current.temperatureC)}°C</Typography><Stack direction="row" gap={1} flexWrap="wrap"><Chip label={`${weather.current.windSpeedKmh} km/h wind`}/><Chip label={`${weather.current.windGustKmh} km/h gusts`}/><Chip label={`Rain ${weather.current.rainProbability}%`}/><Chip label={`Delta T ${weather.current.deltaTC}°C`}/><Chip color={weather.current.sprayCondition?.status==='GO'?'success':'warning'} label={weather.current.sprayCondition?.label||'Advisory'}/>{weather.current.inversionPotential&&<Chip label={`Forecast inversion potential: ${weather.current.inversionPotential.label}`} sx={{borderLeft:`4px solid ${riskColour[weather.current.inversionPotential.rating]}`}}/>}</Stack>{weather.current.inversionPotential&&<Typography variant="caption" color="text.secondary" display="block" sx={{mt:1}}>{factors(weather.current.inversionPotential)}. Check on site.</Typography>}</CardContent></Card></Grid>
      <Grid size={{xs:12,md:7}}><Card><CardContent><Typography variant="h6" fontWeight={800}>Best spray window</Typography>{weather.bestSprayWindow?<Typography variant="h4" fontWeight={900} sx={{my:2}}>{time(weather.bestSprayWindow.start)} – {time(weather.bestSprayWindow.end)}</Typography>:<Typography sx={{my:2}}>No clearly favourable window is currently identified.</Typography>}<Typography color="text.secondary">Check the hourly forecast and reassess conditions on site.</Typography></CardContent></Card></Grid>
      <Grid size={{xs:12}}><Card><CardContent><Typography variant="h6" fontWeight={800}>Wind and inversion outlook</Typography><OutlookChart hours={weather.hourly||[]}/></CardContent></Card></Grid>
      <Grid size={{xs:12}}><Card><CardContent><Typography variant="h6" fontWeight={800} sx={{mb:2}}>Next 24 hours</Typography><Box sx={{display:'grid',gridAutoFlow:'column',gridAutoColumns:{xs:170,md:'minmax(160px,1fr)'},overflowX:'auto',gap:1}}>{(weather.hourly||[]).slice(0,25).map((hour:any,index:number)=><Box key={hour.time} sx={{border:'1px solid',borderColor:'divider',borderRadius:2,p:1.5,bgcolor:hour.isDay?'rgba(255,193,7,.06)':'rgba(25,55,95,.07)',borderTop:`4px solid ${riskColour[hour.inversionPotential?.rating]||'#64748b'}`}}><Stack direction="row" alignItems="center" justifyContent="space-between"><Typography fontWeight={800}>{index===0?'Now · ':''}{time(hour.time)}</Typography>{hour.isDay?<WbSunnyIcon color="warning" fontSize="small"/>:<NightsStayIcon color="primary" fontSize="small"/>}</Stack><Typography variant="h6">{Math.round(hour.temperatureC)}°</Typography><Typography variant="body2">Wind {hour.windSpeedKmh} {hour.windDirection||''}</Typography><Typography variant="body2">Gust {hour.windGustKmh}</Typography><Typography variant="body2">Rain {hour.rainProbability}%</Typography><Typography variant="body2">Delta T {hour.deltaTC}°</Typography>{hour.inversionPotential&&<><Typography variant="body2" fontWeight={800} color={riskColour[hour.inversionPotential.rating]||'#64748b'}>Forecast inversion potential: {hour.inversionPotential.label}</Typography><Typography variant="caption" color="text.secondary">{factors(hour.inversionPotential)}</Typography></>}</Box>)}</Box></CardContent></Card></Grid>
      <Grid size={{xs:12}}><Card><CardContent><Typography variant="h6" fontWeight={800} sx={{mb:2}}>7 day forecast</Typography><Grid container spacing={1}>{(weather.daily||[]).slice(0,7).map((item:any)=><Grid size={{xs:6,sm:'auto'}} key={item.date}><Box sx={{bgcolor:'action.hover',borderRadius:2,p:1.5}}><Typography fontWeight={800}>{day(item.date)}</Typography><Typography>{Math.round(item.minTemperatureC)}° / {Math.round(item.maxTemperatureC)}°</Typography><Typography variant="body2" color="text.secondary">Rain {item.rainProbability}%</Typography></Box></Grid>)}</Grid></CardContent></Card></Grid>
    </Grid>}
  </Box>;
}
