import React from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, Stack, Typography } from '@mui/material';
import { createOperationsBriefApi, OperationsBrief } from '../services/operationsBriefApi';

const api = createOperationsBriefApi();
const time = (value: string) => new Date(value).toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit', hour12: false });
const day = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString('en-AU', { weekday: 'short', day: 'numeric' });

export default function WeatherCentre() {
  const [brief, setBrief] = React.useState<OperationsBrief | null>(null);
  const [error, setError] = React.useState('');
  const [locating, setLocating] = React.useState(false);
  React.useEffect(() => { api.read().then(setBrief).catch(e => setError(e.message)); }, []);
  const useDeviceLocation = () => { setLocating(true); navigator.geolocation.getCurrentPosition(async position => { try { const weather = await api.deviceWeather(position.coords.latitude, position.coords.longitude); setBrief(current => current ? { ...current, location: { id: 'device', name: 'Current device location' }, weather } : current); } catch (e: any) { setError(e.message); } finally { setLocating(false); } }, error => { setError(error.message || 'Device location is unavailable.'); setLocating(false); }, { enableHighAccuracy: true, timeout: 10000 }); };
  if (!brief && !error) return <Stack alignItems="center" sx={{ py: 10 }}><CircularProgress /></Stack>;
  if (!brief) return <Alert severity="error">{error}</Alert>;
  const weather = brief.weather;
  return <Box sx={{ maxWidth: 1400, mx: 'auto', pb: 6 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2}><Box><Typography variant="overline" color="primary.main" fontWeight={900}>OPERATIONAL WEATHER</Typography><Typography variant="h3" fontWeight={900} color="primary.dark">Weather Centre</Typography><Typography color="text.secondary">{brief.location?.name || 'Operating location not selected'}</Typography></Box>{'geolocation' in navigator && <Button variant="outlined" disabled={locating} onClick={useDeviceLocation}>{locating ? 'Locating…' : 'Use my current location'}</Button>}</Stack><Alert severity="info" sx={{ my: 2.5 }}>Weather and Spray Score are decision support only. They do not authorise operations or replace operator judgement.</Alert>
    {weather.state !== 'READY' || !weather.current ? <Alert severity="warning">{weather.message || 'Weather needs a valid operating-location address before it can be shown.'}</Alert> : <Grid container spacing={2.5}>
      <Grid size={{ xs: 12, md: 5 }}><Card><CardContent><Typography variant="h6" fontWeight={800}>Current conditions</Typography><Typography variant="h2" fontWeight={900} sx={{ my: 1 }}>{Math.round(weather.current.temperatureC)}°C</Typography><Stack direction="row" gap={1} flexWrap="wrap"><Chip label={`${weather.current.windSpeedKmh} km/h wind`} /><Chip label={`${weather.current.windGustKmh} km/h gusts`} /><Chip label={`Rain ${weather.current.rainProbability}%`} /><Chip label={`Delta T ${weather.current.deltaTC}°C`} /><Chip color={weather.current.sprayCondition?.status === 'GO' ? 'success' : 'warning'} label={weather.current.sprayCondition?.label || 'Advisory'} /></Stack></CardContent></Card></Grid>
      <Grid size={{ xs: 12, md: 7 }}><Card><CardContent><Typography variant="h6" fontWeight={800}>Best spray window</Typography>{weather.bestSprayWindow ? <Typography variant="h4" fontWeight={900} sx={{ my: 2 }}>{time(weather.bestSprayWindow.start)} – {time(weather.bestSprayWindow.end)}</Typography> : <Typography sx={{ my: 2 }}>No clearly favourable window is currently identified.</Typography>}<Typography color="text.secondary">Check the hourly forecast and reassess conditions on site.</Typography></CardContent></Card></Grid>
      <Grid size={{ xs: 12 }}><Card><CardContent><Typography variant="h6" fontWeight={800} sx={{ mb: 2 }}>Next 24 hours</Typography><Box sx={{ display: 'grid', gridAutoFlow: 'column', gridAutoColumns: { xs: 145, md: 'minmax(135px,1fr)' }, overflowX: 'auto', gap: 1 }}>{(weather.hourly || []).slice(0, 24).map((hour: any) => <Box key={hour.time} sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 2, p: 1.5 }}><Typography fontWeight={800}>{time(hour.time)}</Typography><Typography variant="h6">{Math.round(hour.temperatureC)}°</Typography><Typography variant="body2">Wind {hour.windSpeedKmh}</Typography><Typography variant="body2">Gust {hour.windGustKmh}</Typography><Typography variant="body2">Rain {hour.rainProbability}%</Typography><Typography variant="body2">Delta T {hour.deltaTC}°</Typography></Box>)}</Box></CardContent></Card></Grid>
      <Grid size={{ xs: 12 }}><Card><CardContent><Typography variant="h6" fontWeight={800} sx={{ mb: 2 }}>7 day forecast</Typography><Grid container spacing={1}>{(weather.daily || []).slice(0, 7).map((item: any) => <Grid size={{ xs: 6, sm: 'auto' }} key={item.date}><Box sx={{ bgcolor: 'action.hover', borderRadius: 2, p: 1.5 }}><Typography fontWeight={800}>{day(item.date)}</Typography><Typography>{Math.round(item.minTemperatureC)}° / {Math.round(item.maxTemperatureC)}°</Typography><Typography variant="body2" color="text.secondary">Rain {item.rainProbability}%</Typography></Box></Grid>)}</Grid></CardContent></Card></Grid>
    </Grid>}
  </Box>;
}
