import React from 'react';import{Alert,Button,Card,CardContent,Chip,Divider,LinearProgress,Stack,TextField,Typography}from'@mui/material';
type Review=Record<string,any>;
async function call(path:string,init:RequestInit={}){const response=await fetch(path,{...init,credentials:'same-origin',headers:init.body?{'Content-Type':'application/json'}:undefined});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error?.message||'Chemical Intelligence review request failed.');return body.data;}
export default function AuthoritativeChemicalReviews(){const[permissions,setPermissions]=React.useState<string[]>([]),[research,setResearch]=React.useState<Review[]>([]),[approval,setApproval]=React.useState<Review[]>([]),[loading,setLoading]=React.useState(true),[error,setError]=React.useState(''),[drafts,setDrafts]=React.useState<Record<string,{researchNotes:string;recommendation:string}>>({});
 const load=React.useCallback(async()=>{setLoading(true);setError('');try{const session=await call('/api/v1/session'),p:string[]=session.permissions||[];setPermissions(p);const canResearch=p.includes('*')||p.includes('chemical.review.*')||p.includes('chemical.review.research'),canApprove=p.includes('*')||p.includes('chemical.review.*')||p.includes('chemical.review.approve');const[researchQueue,approvalQueue]=await Promise.all([canResearch?call('/api/v1/chemical-reviews?queue=research'):[],canApprove?call('/api/v1/chemical-reviews?queue=approval'):[]]);setResearch(researchQueue);setApproval(approvalQueue);}catch(c){setError(c instanceof Error?c.message:'Review queues could not be loaded.');}finally{setLoading(false);}},[]);React.useEffect(()=>{void load();},[load]);
 const transition=async(review:Review,action:string)=>{setError('');try{const draft=drafts[review.id]||{researchNotes:review.research_notes||'',recommendation:review.recommendation||''};await call(`/api/v1/chemical-reviews?id=${encodeURIComponent(review.id)}`,{method:'POST',body:JSON.stringify({action,expectedVersion:review.row_version,researchNotes:draft.researchNotes,recommendation:draft.recommendation})});await load();}catch(c){setError(c instanceof Error?c.message:'Review could not be updated.');}};
 const has=(code:string)=>permissions.includes('*')||permissions.includes('chemical.review.*')||permissions.includes(code);const edit=(id:string,key:'researchNotes'|'recommendation',value:string)=>setDrafts(current=>({...current,[id]:{researchNotes:current[id]?.researchNotes||'',recommendation:current[id]?.recommendation||'',[key]:value}}));
 const card=(review:Review,approvalMode=false)=><Card key={review.id} variant="outlined"><CardContent><Stack spacing={1.5}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{review.product_name}</Typography><Chip label={review.status}/></Stack><Typography variant="body2">Manufacturer: {review.manufacturer||'Not supplied'} · APVMA: {review.apvma_number||'Not supplied'}</Typography><Typography variant="body2">Active ingredient: {review.active_ingredient||'Not supplied'} · Formulation: {review.formulation||'Not supplied'}</Typography>{!approvalMode&&<><TextField multiline minRows={2} label="Research notes" value={drafts[review.id]?.researchNotes??review.research_notes??''} onChange={e=>edit(review.id,'researchNotes',e.target.value)}/><TextField multiline minRows={2} label="Recommendation for Ben" value={drafts[review.id]?.recommendation??review.recommendation??''} onChange={e=>edit(review.id,'recommendation',e.target.value)}/><Stack direction="row" spacing={1}><Button onClick={()=>void transition(review,'START_RESEARCH')}>Start research</Button><Button variant="contained" onClick={()=>void transition(review,'READY_FOR_APPROVAL')}>Ready for Ben</Button></Stack></>}{approvalMode&&<><Typography><strong>Research:</strong> {review.research_notes||'No notes'}</Typography><Typography><strong>Recommendation:</strong> {review.recommendation||'No recommendation'}</Typography><Stack direction="row" spacing={1} useFlexGap flexWrap="wrap"><Button variant="contained" color="success" onClick={()=>void transition(review,'APPROVE')}>Approve and publish</Button><Button onClick={()=>void transition(review,'RETURN')}>Return to Clare</Button><Button onClick={()=>void transition(review,'DUPLICATE')}>Mark duplicate</Button><Button color="error" onClick={()=>void transition(review,'REJECT')}>Reject</Button></Stack></>}</Stack></CardContent></Card>;
 return <Stack spacing={2}><Typography variant="h6" fontWeight={800}>Chemical Intelligence Review</Typography><Alert severity="info">Unmatched Mission products arrive here automatically. Researchers prepare evidence; only the separately authorised approver can publish.</Alert>{loading&&<LinearProgress/>}{error&&<Alert severity="error">{error} No local review store has been substituted.</Alert>}{has('chemical.review.research')&&<><Typography fontWeight={800}>Clare’s research queue</Typography>{research.length?research.map(r=>card(r)):<Alert severity="success">No active research reviews.</Alert>}</>}{has('chemical.review.approve')&&<><Divider/><Typography fontWeight={800}>Ben’s approval queue</Typography>{approval.length?approval.map(r=>card(r,true)):<Alert severity="success">No reviews are ready for approval.</Alert>}</>}{!has('chemical.review.research')&&!has('chemical.review.approve')&&!loading&&<Alert severity="warning">This account does not have Chemical Intelligence research or approval permission.</Alert>}</Stack>;
}
