const val=(v:unknown)=>v===undefined||v===null||v===''?'Not recorded':String(v);const title=(lines:string[],value:string)=>{lines.push('',value.toUpperCase());};
export function buildMissionPackLines(pack:any):string[]{const lines:string[]=['SPRAY COMMAND MISSION PACK'];const a=pack?.authorisation||{},e=pack?.evidence||{},m=e?.mission?.snapshot||{},context=e?.businessContext||{},planning=e?.planning||{},preflight=e?.preflight||{},readiness=pack?.readiness||{};
 lines.push(`Evidence schema: ${val(e.schemaVersion||pack?.schemaVersion)}`,`Mission: ${val(m.mission_number)} — ${val(m.title)}`,`Mission ID: ${val(e?.mission?.id)}`,`Mission record version: ${val(e?.mission?.rowVersion)}`,`Scheduled start: ${val(m.scheduled_start_at)}`);
 title(lines,'Authorisation');lines.push(`Authorisation ID: ${val(a.id)}`,`Authorisation version: ${val(a.version_number)}`,`Authorised at: ${val(a.authorised_at)}`,`Authorised PIC: ${val(a.authorised_personnel_snapshot?.name||a.authorised_personnel_snapshot?.full_name)}`,`Declaration: ${val(a.declaration)}`);
 title(lines,'Business context');lines.push(`Client: ${val(context.client?.name)}`,`Property: ${val(context.property?.name)}`,`Job: ${val(context.job?.reference)}`,`Fields: ${val((context.fields||[]).map((f:any)=>f.name).join(', '))}`);
 title(lines,'Planning evidence');lines.push(`Mission map revision: ${val(planning.map?.id)} / version ${val(planning.map?.version_number)}`,`Map geometries: ${val((planning.map?.geometries||[]).map((g:any)=>`${g.role}${g.areaHectares?` (${g.areaHectares} ha)`:''}`).join(', '))}`,`Forecast revision: ${val(planning.forecastWeather?.id)} / version ${val(planning.forecastWeather?.version_number)}`,`Forecast provider: ${val(planning.forecastWeather?.provider)}`);
 for(const x of planning.aircraft||[])lines.push(`Aircraft: ${val(x.snapshot?.registration)} ${val(x.snapshot?.model)} [${val(x.aircraftId)} · row ${val(x.rowVersion)}]`);for(const x of planning.equipmentKits||[])lines.push(`Equipment Kit: ${val(x.snapshot?.name)} [${val(x.equipmentKitId)} · row ${val(x.rowVersion)}]`);lines.push(`Personnel revision: ${val(planning.personnel?.id)} / version ${val(planning.personnel?.version_number)}`);for(const x of planning.personnel?.assignments||[])lines.push(`Personnel: ${val(x.snapshot?.name)} — ${val(x.assignment_role||x.snapshot?.assignmentRole)} [${val(x.personnel_id||x.snapshot?.personnelId)}]`);lines.push(`Chemical plan revision: ${val(planning.chemicals?.id)} / version ${val(planning.chemicals?.version_number)}`);for(const x of planning.chemicals?.lines||[])lines.push(`Chemical: ${val(x.product_name_snapshot||x.entered_name)} — ${val(x.rate)} ${val(x.rate_unit)}`);
 title(lines,'Pre-flight evidence');lines.push(`Observed Weather revision: ${val(preflight.observedWeather?.id)} / version ${val(preflight.observedWeather?.version_number)}`,`Delta T: ${val(preflight.observedWeather?.delta_t_c)} °C`,`Inversion assessment: ${val(preflight.observedWeather?.inversion_assessment)}`,`JSA revision: ${val(preflight.jsa?.id)} / version ${val(preflight.jsa?.version_number)}`,`JSA template version: ${val(preflight.jsa?.template_version)}`);for(const d of preflight.requiredDocuments||[])lines.push(`Document: ${val(d.evidenceType)} [file ${val(d.internalFileId)} · version ${val(d.fileVersion)} · SHA-256 ${val(d.checksum)}]`);
 title(lines,'Readiness snapshot');lines.push(`Overall state: ${val(readiness.overallState)}`,`Completed: ${val((readiness.completedSections||[]).join(', '))}`,`Warnings: ${val((readiness.warnings||[]).map((w:any)=>w.message).join('; '))}`,'',`Generated from immutable Authorisation revision ${val(a.id)}. Current records were not queried or substituted.`);return lines;}
