import React from 'react';
import {Alert,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,FormControlLabel,Grid,InputLabel,MenuItem,Radio,RadioGroup,Select,Stack,TextField,Typography} from '@mui/material';
import VerifiedUserIcon from '@mui/icons-material/VerifiedUser';
import {createMissionJsaApi} from '../../services/missionJsaApi';
import {createPersonnelApi} from '../../services/personnelApi';
import {MissionJsaControl,MissionJsaReadiness,MissionJsaRevision} from '../../types/missionJsa';
import {isUnsafeAnswer,MISSION_CHECKS} from '../../utils/missionSafety';

type JsaApi=ReturnType<typeof createMissionJsaApi>;type PersonnelApi=ReturnType<typeof createPersonnelApi>;
const defaultApi=createMissionJsaApi(),defaultPersonnelApi=createPersonnelApi();
type Answer={questionId:string;answer:boolean|null;notes:string};
type ControlDraft={questionId:string;ownerPersonnelId:string;likelihood:number|null;consequence:number|null;mitigation:string;residualLikelihood:number|null;residualConsequence:number|null;completionState:'OPEN'|'IN_PROGRESS'|'COMPLETE';notes:string};
const emptyAnswers=():Answer[]=>MISSION_CHECKS.map(check=>({questionId:check.id,answer:null,notes:''}));
const emptyControl=(questionId:string):ControlDraft=>({questionId,ownerPersonnelId:'',likelihood:null,consequence:null,mitigation:'',residualLikelihood:null,residualConsequence:null,completionState:'OPEN',notes:''});
const score=(a:number|null,b:number|null)=>a&&b?a*b:null;

export default function AuthoritativeMissionJsa({open,missionId,missionName,operatingLocationId,onClose,onChanged,api=defaultApi,personnelApi=defaultPersonnelApi}:{open:boolean;missionId:string;missionName:string;operatingLocationId:string;onClose:()=>void;onChanged?:(revision:MissionJsaRevision,approved:boolean)=>void;api?:JsaApi;personnelApi?:PersonnelApi}){
 const[record,setRecord]=React.useState<MissionJsaRevision|null>(null),[answers,setAnswers]=React.useState<Answer[]>(emptyAnswers),[controls,setControls]=React.useState<ControlDraft[]>([]),[comments,setComments]=React.useState(''),[people,setPeople]=React.useState<any[]>([]),[readiness,setReadiness]=React.useState<MissionJsaReadiness|null>(null),[loading,setLoading]=React.useState(false),[saving,setSaving]=React.useState(false),[error,setError]=React.useState(''),[notice,setNotice]=React.useState('');
 const hydrate=(revision:MissionJsaRevision|null)=>{setRecord(revision);if(!revision){setAnswers(emptyAnswers());setControls([]);setComments('');return;}setAnswers(MISSION_CHECKS.map(check=>{const found=(revision.responses||[]).find(item=>item.question_id===check.id);return{questionId:check.id,answer:found?.answer??null,notes:found?.notes||''};}));setControls((revision.controls||[]).map((item:MissionJsaControl)=>({questionId:item.triggering_question_id,ownerPersonnelId:item.owner_personnel_id||'',likelihood:item.likelihood,residualLikelihood:item.residual_likelihood,consequence:item.consequence,residualConsequence:item.residual_consequence,mitigation:item.mitigation||'',completionState:item.completion_state==='COMPLETE'?'COMPLETE':item.completion_state==='IN_PROGRESS'?'IN_PROGRESS':'OPEN',notes:item.notes||''})));setComments(revision.general_comments||'');};
 const refresh=React.useCallback(async()=>{setLoading(true);setError('');try{const[current,nextReadiness,personnel]=await Promise.all([api.read(missionId),api.readiness(missionId),personnelApi.list(operatingLocationId)]);hydrate(Array.isArray(current)?current[0]||null:current);setReadiness(nextReadiness);setPeople((Array.isArray(personnel)?personnel:[]).filter((person:any)=>person.isActive));}catch(c){setError(c instanceof Error?c.message:'Mission JSA could not be loaded.');}finally{setLoading(false);}},[api,missionId,operatingLocationId,personnelApi]);
 React.useEffect(()=>{if(open)void refresh();},[open,refresh]);
 const updateAnswer=(questionId:string,answer:boolean|null,notes?:string)=>{setAnswers(current=>current.map(item=>item.questionId===questionId?{...item,answer,notes:notes===undefined?item.notes:notes}:item));const unsafe=isUnsafeAnswer(questionId,answer);setControls(current=>unsafe?(current.some(item=>item.questionId===questionId)?current:[...current,emptyControl(questionId)]):current.filter(item=>item.questionId!==questionId));};
 const updateControl=(questionId:string,changes:Partial<ControlDraft>)=>setControls(current=>current.map(item=>item.questionId===questionId?{...item,...changes}:item));
 const save=async()=>{setSaving(true);setError('');setNotice('');try{const revision=await api.save(missionId,{expectedVersion:record?.version_number||0,responses:answers,controls:controls.map(control=>({...control,ownerPersonnelId:control.ownerPersonnelId||undefined,likelihood:control.likelihood||undefined,consequence:control.consequence||undefined,residualLikelihood:control.residualLikelihood||undefined,residualConsequence:control.residualConsequence||undefined})),attachments:[],generalComments:comments,missionFacts:{}});hydrate(revision);setReadiness(await api.readiness(missionId));setNotice(`Authoritative JSA version ${revision.version_number} saved.`);onChanged?.(revision,false);}catch(c){setError(c instanceof Error?c.message:'Mission JSA could not be saved.');}finally{setSaving(false);}};
 const approve=async()=>{if(!record)return;setSaving(true);setError('');try{const result=await api.approve(missionId,record.id,record.version_number);hydrate(result.record);setReadiness(result.readiness);setNotice('Mission JSA approved by the assigned Pilot in Command.');onChanged?.(result.record,true);}catch(c){setError(c instanceof Error?c.message:'Mission JSA could not be approved.');}finally{setSaving(false);}};
 return <Dialog open={open} onClose={onClose} fullWidth maxWidth="lg"><DialogTitle><Stack direction="row" spacing={1} alignItems="center"><VerifiedUserIcon color="primary"/><Box><Typography variant="h6">Mission Checks</Typography><Typography variant="caption" color="text.secondary">{missionName||'Mission'} · authoritative JSA{record?` version ${record.version_number}`:''}</Typography></Box></Stack></DialogTitle><DialogContent dividers><Stack spacing={2}>
  {loading&&<Alert severity="info">Loading authoritative Mission JSA…</Alert>}{error&&<Alert severity="error">{error} No browser-stored JSA has been substituted.</Alert>}{notice&&<Alert severity="success">{notice}</Alert>}
  {readiness&&<Alert severity={readiness.ready?'success':readiness.overallState==='BLOCKED'?'error':'warning'}>{readiness.ready?'Mission JSA is ready.':readiness.blockers[0]?.message||'Complete the Mission JSA.'}<Typography variant="caption" display="block">Outstanding: {readiness.outstandingSections.join(', ')||'None'} · Completed: {readiness.completedSections.join(', ')||'None'}</Typography></Alert>}
  {MISSION_CHECKS.map((check,index)=>{const answer=answers.find(item=>item.questionId===check.id)!;const unsafe=isUnsafeAnswer(check.id,answer.answer);return <Box key={check.id} sx={{p:2,border:'1px solid',borderColor:unsafe?'warning.main':'divider',borderRadius:2}}><Typography sx={{fontWeight:800,mb:.5}}>{index+1}. {check.question}</Typography><RadioGroup row value={answer.answer===null?'':String(answer.answer)} onChange={event=>updateAnswer(check.id,event.target.value==='true')}><FormControlLabel value="true" control={<Radio/>} label="Yes"/><FormControlLabel value="false" control={<Radio/>} label="No"/></RadioGroup><TextField fullWidth size="small" multiline minRows={2} label="Notes" value={answer.notes} onChange={event=>updateAnswer(check.id,answer.answer,event.target.value)}/></Box>;})}
  <TextField fullWidth multiline minRows={3} label="Additional comments" value={comments} onChange={event=>setComments(event.target.value)}/>
  {controls.length>0&&<Typography variant="h6">Triggered Risk Controls</Typography>}{controls.map(control=>{const check=MISSION_CHECKS.find(item=>item.id===control.questionId)!;const initial=score(control.likelihood,control.consequence),residual=score(control.residualLikelihood,control.residualConsequence);return <Box key={control.questionId} sx={{p:2,bgcolor:'warning.50',border:'1px solid',borderColor:'warning.light',borderRadius:2}}><Typography sx={{fontWeight:800,mb:1}}>{check.question}</Typography><Alert severity="warning" sx={{mb:1}}>A platform-defined hazard and required control will be retained with this JSA revision.</Alert><Grid container spacing={1.25}><Grid size={{xs:12,md:4}}><TextField select fullWidth size="small" label="Control owner" value={control.ownerPersonnelId} onChange={e=>updateControl(control.questionId,{ownerPersonnelId:e.target.value})}>{people.map(person=><MenuItem key={person.id} value={person.id}>{person.fullName}</MenuItem>)}</TextField></Grid>{(['likelihood','consequence']as const).map(field=><Grid key={field} size={{xs:6,md:2}}><FormControl fullWidth size="small"><InputLabel>{field}</InputLabel><Select label={field} value={control[field]||''} onChange={e=>updateControl(control.questionId,{[field]:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><MenuItem key={n} value={n}>{n}</MenuItem>)}</Select></FormControl></Grid>)}<Grid size={{xs:6,md:2}}><TextField fullWidth size="small" label="Initial score" value={initial??'Not assessed'} slotProps={{input:{readOnly:true}}}/></Grid><Grid size={{xs:12}}><TextField fullWidth multiline minRows={2} label="Mitigation procedures" value={control.mitigation} onChange={e=>updateControl(control.questionId,{mitigation:e.target.value})}/></Grid>{(['residualLikelihood','residualConsequence']as const).map(field=><Grid key={field} size={{xs:6,md:3}}><FormControl fullWidth size="small"><InputLabel>{field==='residualLikelihood'?'Residual likelihood':'Residual consequence'}</InputLabel><Select label={field} value={control[field]||''} onChange={e=>updateControl(control.questionId,{[field]:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><MenuItem key={n} value={n}>{n}</MenuItem>)}</Select></FormControl></Grid>)}<Grid size={{xs:6,md:3}}><TextField fullWidth size="small" error={Boolean(residual&&residual>=6)} label="Residual score" value={residual??'Not assessed'} slotProps={{input:{readOnly:true}}}/></Grid><Grid size={{xs:12,md:3}}><TextField select fullWidth size="small" label="Completion" value={control.completionState} onChange={e=>updateControl(control.questionId,{completionState:e.target.value as ControlDraft['completionState']})}><MenuItem value="OPEN">Open</MenuItem><MenuItem value="IN_PROGRESS">In progress</MenuItem><MenuItem value="COMPLETE">Complete</MenuItem></TextField></Grid></Grid></Box>;})}
 </Stack></DialogContent><DialogActions><Button onClick={onClose}>Close</Button><Button variant="outlined" disabled={loading||saving} onClick={()=>void save()}>{saving?'Saving…':'Save Draft'}</Button><Button variant="contained" disabled={!record||saving||Boolean(record.approvals?.length)} onClick={()=>void approve()}>Approve Mission Checks as assigned PIC</Button></DialogActions></Dialog>;
}
