import React from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Grid, MenuItem, Stack, Step, StepLabel, Stepper, TextField, Typography } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import FieldBoundaryEditor from '../FieldBoundaryEditor';
import { useOperationalData } from '../../contexts/OperationalDataContext';
import { describeOperationalError } from '../../services/operationalDataStore';
import { LatLng } from '../../types/fieldManagement';

const stages = ['Customer','Property','Field','Job','Mission','Map','Resources','Weather & Chemicals','JSA','Review'];
const today = () => new Date().toISOString().slice(0,10);

export default function GuidedMissionCreation() {
  const operational = useOperationalData();
  const navigate = useNavigate();
  const [step,setStep]=React.useState(0),[mode,setMode]=React.useState<'select'|'create'>('select'),[error,setError]=React.useState('');
  const [clientId,setClientId]=React.useState(''),[propertyId,setPropertyId]=React.useState(''),[fieldId,setFieldId]=React.useState(''),[jobId,setJobId]=React.useState('');
  const [client,setClient]=React.useState({name:'',contact:'',phone:'',email:'',notes:''});
  const [property,setProperty]=React.useState({name:'',address:'',state:'QLD',contact:'',accessNotes:'',notes:'',lat:undefined as number|undefined,lng:undefined as number|undefined});
  const [field,setField]=React.useState({name:'',notes:''}),[coords,setCoords]=React.useState<LatLng[]>([]),[polygons,setPolygons]=React.useState<LatLng[][]>([]),[area,setArea]=React.useState(0);
  const [job,setJob]=React.useState({reference:'',scope:'',requestedDate:today(),notes:''});
  const [mission,setMission]=React.useState({number:'',title:'',scheduledStart:`${today()}T09:00`,description:'',operatingLocationId:operational.operatingLocations[0]?.id||''});
  React.useEffect(()=>{if(!mission.operatingLocationId&&operational.operatingLocations[0])setMission(v=>({...v,operatingLocationId:operational.operatingLocations[0].id}));},[mission.operatingLocationId,operational.operatingLocations]);
  const properties=operational.properties.filter(x=>x.clientId===clientId),fields=operational.fields.filter(x=>x.propertyId===propertyId),jobs=operational.jobs.filter(x=>x.clientId===clientId&&x.propertyId===propertyId&&x.status.toLowerCase()!=='completed');
  const run=async(action:()=>Promise<void>)=>{setError('');try{await action();setMode('select');}catch(e){setError(describeOperationalError(e));}};
  const progress=<Box sx={{overflowX:'auto',pb:1}}><Stepper activeStep={step} alternativeLabel sx={{minWidth:900}}>{stages.map((label,index)=><Step key={label} completed={index<step}><StepLabel>{index+1} {label}</StepLabel></Step>)}</Stepper></Box>;
  const choose=(id:string,next:number,setter:(id:string)=>void)=>{setter(id);setStep(next);setMode('select');setError('');};
  return <Box sx={{maxWidth:1200,mx:'auto'}}>
    <Stack spacing={1} sx={{mb:3}}><Typography component="h1" variant="h3" fontWeight={800} color="primary.dark">Create a Mission</Typography><Typography color="text.secondary">Follow each step. Spray Command will create and connect the authoritative records as you go.</Typography></Stack>
    {progress}{error&&<Alert severity="error" sx={{my:2}}>{error}</Alert>}
    <Card variant="outlined" sx={{mt:2,borderRadius:3}}><CardContent sx={{p:{xs:2,md:4}}}>
      {step===0&&<Stack spacing={2}><Typography variant="h5" fontWeight={800}>Who is this Mission for?</Typography><Stack direction={{xs:'column',sm:'row'}} spacing={1}><Button variant={mode==='select'?'contained':'outlined'} onClick={()=>setMode('select')}>Select existing Client</Button><Button variant={mode==='create'?'contained':'outlined'} onClick={()=>setMode('create')}>Add new Client</Button></Stack>{mode==='select'?<><TextField select fullWidth label="Client" value={clientId} onChange={e=>setClientId(e.target.value)}>{operational.clients.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><Button variant="contained" disabled={!clientId} onClick={()=>setStep(1)}>Continue</Button></>:<Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Client or business name" value={client.name} onChange={e=>setClient(v=>({...v,name:e.target.value}))}/></Grid><Grid size={{xs:12,md:6}}><TextField fullWidth label="Primary contact" value={client.contact} onChange={e=>setClient(v=>({...v,contact:e.target.value}))}/></Grid><Grid size={{xs:12,md:6}}><TextField fullWidth label="Phone" value={client.phone} onChange={e=>setClient(v=>({...v,phone:e.target.value}))}/></Grid><Grid size={{xs:12,md:6}}><TextField fullWidth label="Email" value={client.email} onChange={e=>setClient(v=>({...v,email:e.target.value}))}/></Grid><Grid size={{xs:12}}><TextField fullWidth label="Client notes" value={client.notes} onChange={e=>setClient(v=>({...v,notes:e.target.value}))}/></Grid><Grid size={{xs:12}}><Button variant="contained" disabled={!client.name.trim()||operational.saving} onClick={()=>void run(async()=>{const saved=await operational.createClient({name:client.name.trim(),contactName:client.contact.trim(),phone:client.phone.trim(),email:client.email.trim(),notes:client.notes.trim(),contractorUserId:'',addresses:[]});choose(saved.id,1,setClientId);})}>Save Client and continue</Button></Grid></Grid>}</Stack>}
      {step===1&&<Stack spacing={2}><Typography variant="h5" fontWeight={800}>Where is the work?</Typography><Chip label={`Client: ${operational.clients.find(x=>x.id===clientId)?.name||client.name}`} sx={{alignSelf:'flex-start'}}/><Stack direction={{xs:'column',sm:'row'}} spacing={1}><Button variant={mode==='select'?'contained':'outlined'} onClick={()=>setMode('select')}>Select existing Property</Button><Button variant={mode==='create'?'contained':'outlined'} onClick={()=>setMode('create')}>Add new Property</Button></Stack>{mode==='select'?<><TextField select fullWidth label="Property" value={propertyId} onChange={e=>setPropertyId(e.target.value)}>{properties.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><Button variant="contained" disabled={!propertyId} onClick={()=>setStep(2)}>Continue</Button></>:<Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Property name" value={property.name} onChange={e=>setProperty(v=>({...v,name:e.target.value}))}/></Grid><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Street address" value={property.address} onChange={e=>setProperty(v=>({...v,address:e.target.value}))}/></Grid><Grid size={{xs:12,md:4}}><TextField select fullWidth label="State" value={property.state} onChange={e=>setProperty(v=>({...v,state:e.target.value}))}>{['QLD','NSW','VIC','SA','WA','TAS','NT','ACT'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,md:8}}><TextField fullWidth label="Primary property contact" value={property.contact} onChange={e=>setProperty(v=>({...v,contact:e.target.value}))}/></Grid><Grid size={{xs:12}}><TextField fullWidth label="Access notes" value={property.accessNotes} onChange={e=>setProperty(v=>({...v,accessNotes:e.target.value}))}/></Grid><Grid size={{xs:12}}><TextField fullWidth label="Property notes" value={property.notes} onChange={e=>setProperty(v=>({...v,notes:e.target.value}))}/></Grid><Grid size={{xs:12}}><Alert severity="info">Confirm the address or property position on the map in the next step. Coordinates are captured from the address/map—not typed manually.</Alert></Grid><Grid size={{xs:12}}><Button variant="contained" disabled={!property.name.trim()||!property.address.trim()||operational.saving} onClick={()=>void run(async()=>{const saved=await operational.createProperty({clientId,name:property.name.trim(),address:property.address.trim(),state:property.state as any,locality:'',lotPlan:'',lat:property.lat,lng:property.lng,primaryContactName:property.contact.trim(),accessNotes:property.accessNotes.trim(),notes:property.notes.trim()});choose(saved.id,2,setPropertyId);})}>Save Property and continue</Button></Grid></Grid>}</Stack>}
      {step===2&&<Stack spacing={2}><Typography variant="h5" fontWeight={800}>Define the operational area</Typography><Stack direction={{xs:'column',sm:'row'}} spacing={1}><Button variant={mode==='select'?'contained':'outlined'} onClick={()=>setMode('select')}>Select existing Field</Button><Button variant={mode==='create'?'contained':'outlined'} onClick={()=>setMode('create')}>Create new Field</Button></Stack>{mode==='select'?<><TextField select fullWidth label="Field" value={fieldId} onChange={e=>setFieldId(e.target.value)}>{fields.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><Button variant="contained" disabled={!fieldId} onClick={()=>setStep(3)}>Continue</Button></>:<><TextField required fullWidth label="Field name" value={field.name} onChange={e=>setField(v=>({...v,name:e.target.value}))}/><FieldBoundaryEditor coords={coords} polygons={polygons} onCoordsChange={setCoords} onPolygonsChange={setPolygons} onAreaChange={setArea} initialAddress={property.address} propertyLat={property.lat} propertyLng={property.lng} onAddressSelect={(address,lat,lng)=>setProperty(v=>({...v,address,lat,lng}))} onPropertyPinMove={(lat,lng)=>setProperty(v=>({...v,lat,lng}))} mapHeight={480}/><Typography fontWeight={700}>Calculated area: {area.toFixed(2)} ha</Typography><TextField fullWidth label="Field notes" value={field.notes} onChange={e=>setField(v=>({...v,notes:e.target.value}))}/><Button variant="contained" disabled={!field.name.trim()||coords.length<3||area<=0||operational.saving} onClick={()=>void run(async()=>{const authoritativeProperty=operational.properties.find(x=>x.id===propertyId);if(authoritativeProperty&&property.lat!==undefined&&property.lng!==undefined)await operational.updateProperty(propertyId,{address:property.address,lat:property.lat,lng:property.lng});const saved=await operational.createField({propertyId,name:field.name.trim(),sizeHa:area,boundary:null,boundaryCoords:coords,notes:field.notes});await operational.createFieldBoundaryVersion(saved.id,coords);choose(saved.id,3,setFieldId);})}>Save Field and boundary</Button></>}</Stack>}
      {step===3&&<Stack spacing={2}><Typography variant="h5" fontWeight={800}>Create the work request</Typography><Stack direction={{xs:'column',sm:'row'}} spacing={1}><Button variant={mode==='select'?'contained':'outlined'} onClick={()=>setMode('select')}>Select existing open Job</Button><Button variant={mode==='create'?'contained':'outlined'} onClick={()=>setMode('create')}>Create new Job</Button></Stack>{mode==='select'?<><TextField select fullWidth label="Job" value={jobId} onChange={e=>setJobId(e.target.value)}>{jobs.map(x=><MenuItem key={x.id} value={x.id}>{x.reference} — {x.scope}</MenuItem>)}</TextField><Button variant="contained" disabled={!jobId} onClick={()=>setStep(4)}>Continue</Button></>:<Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Job reference" value={job.reference} onChange={e=>setJob(v=>({...v,reference:e.target.value}))}/></Grid><Grid size={{xs:12,md:6}}><TextField type="date" fullWidth label="Requested or scheduled date" value={job.requestedDate} onChange={e=>setJob(v=>({...v,requestedDate:e.target.value}))} InputLabelProps={{shrink:true}}/></Grid><Grid size={{xs:12}}><TextField required fullWidth label="Job scope" value={job.scope} onChange={e=>setJob(v=>({...v,scope:e.target.value}))}/></Grid><Grid size={{xs:12}}><TextField fullWidth multiline minRows={2} label="Treatment request and notes" value={job.notes} onChange={e=>setJob(v=>({...v,notes:e.target.value}))}/></Grid><Grid size={{xs:12}}><Button variant="contained" disabled={!job.reference.trim()||!job.scope.trim()||operational.saving} onClick={()=>void run(async()=>{const saved=await operational.createJob({clientId,propertyId,fieldIds:[fieldId],reference:job.reference.trim(),scope:job.scope.trim(),status:'open',notes:job.notes.trim(),requestedDate:job.requestedDate,scheduledDate:job.requestedDate});choose(saved.id,4,setJobId);})}>Save Job and continue</Button></Grid></Grid>}</Stack>}
      {step===4&&<Stack spacing={2}><Typography variant="h5" fontWeight={800}>Create the authoritative Draft Mission</Typography><Alert severity="info">A stable Mission ID is created now. Map, resources, Weather, Chemicals and JSA will save against that Draft.</Alert><Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Mission number" value={mission.number} onChange={e=>setMission(v=>({...v,number:e.target.value}))}/></Grid><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Mission title" value={mission.title} onChange={e=>setMission(v=>({...v,title:e.target.value}))}/></Grid><Grid size={{xs:12,md:6}}><TextField type="datetime-local" fullWidth label="Scheduled date and time" value={mission.scheduledStart} onChange={e=>setMission(v=>({...v,scheduledStart:e.target.value}))} InputLabelProps={{shrink:true}}/></Grid><Grid size={{xs:12,md:6}}><TextField select fullWidth label="Operating location" value={mission.operatingLocationId} onChange={e=>setMission(v=>({...v,operatingLocationId:e.target.value}))}>{operational.operatingLocations.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField></Grid><Grid size={{xs:12}}><TextField fullWidth multiline minRows={2} label="Mission description" value={mission.description} onChange={e=>setMission(v=>({...v,description:e.target.value}))}/></Grid><Grid size={{xs:12}}><Button variant="contained" disabled={!mission.number.trim()||!mission.title.trim()||!mission.operatingLocationId||operational.saving} onClick={()=>void run(async()=>{const saved=await operational.createMission({jobId,operatingLocationId:mission.operatingLocationId,missionNumber:mission.number.trim(),title:mission.title.trim(),description:mission.description.trim(),scheduledStartAt:new Date(mission.scheduledStart).toISOString(),status:'Planning',aircraftIds:[],equipmentKitIds:[]});navigate(`/missions/${saved.id}?guided=1`);})}>Create Draft Mission</Button></Grid></Grid></Stack>}
      <Stack direction="row" justifyContent="space-between" sx={{mt:3}}><Button disabled={step===0} onClick={()=>{setStep(v=>Math.max(0,v-1));setMode('select');}}>Back</Button><Typography variant="body2" color="text.secondary">Each saved record is authoritative and available in its register.</Typography></Stack>
    </CardContent></Card>
  </Box>;
}
