import React from 'react';
import { Alert, Button, Checkbox, Chip, Divider, FormControlLabel, Grid, LinearProgress, Stack, TextField, Typography } from '@mui/material';
import { createMissionWeatherEvidenceApi } from '../../services/missionWeatherEvidenceApi';
import { createPersonnelApi } from '../../services/personnelApi';
import { PersonnelRecord } from '../../types/personnel';

type WeatherRecord=Record<string,any>;
type Readiness={ready:boolean;blockers?:Array<{code:string;message:string}>;warnings?:Array<{code:string;message:string}>};
type WeatherApi={read:(missionId:string)=>Promise<any>;forecasts:(missionId:string)=>Promise<any>;readiness:(missionId:string)=>Promise<Readiness>;createForecast:(missionId:string,input:Record<string,unknown>)=>Promise<WeatherRecord>;selectForecast:(missionId:string,forecastRevisionId:string,expectedVersion:number)=>Promise<WeatherRecord>;createManual:(missionId:string,input:Record<string,unknown>)=>Promise<WeatherRecord>;select:(missionId:string,observationId:string,expectedVersion:number)=>Promise<WeatherRecord>};
type PersonnelApi={list:(operatingLocationId?:string)=>Promise<PersonnelRecord[]>};
const defaultWeatherApi=createMissionWeatherEvidenceApi();
const defaultPersonnelApi=createPersonnelApi();
const defaultGetCurrentPosition:Geolocation['getCurrentPosition']=(success,failure,options)=>{if(typeof navigator!=='undefined'&&navigator.geolocation)return navigator.geolocation.getCurrentPosition(success,failure,options);failure?.({code:2,message:'Geolocation is unavailable.',PERMISSION_DENIED:1,POSITION_UNAVAILABLE:2,TIMEOUT:3}as GeolocationPositionError);};

const localDateTime=()=>{const now=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return now.toISOString().slice(0,16);};
const value=(record:WeatherRecord,...keys:string[])=>keys.map((key)=>record?.[key]).find((item)=>item!==undefined&&item!==null);

export default function MissionWeatherEvidence({missionId,operatingLocationId,scheduledStartAt,plannedCoordinates,weatherApi=defaultWeatherApi,personnelApi=defaultPersonnelApi,getCurrentPosition=defaultGetCurrentPosition}:{missionId:string;operatingLocationId:string;scheduledStartAt?:string;plannedCoordinates?:{latitude:number;longitude:number};weatherApi?:WeatherApi;personnelApi?:PersonnelApi;getCurrentPosition?:Geolocation['getCurrentPosition']}){
  const [observers,setObservers]=React.useState<PersonnelRecord[]>([]),[records,setRecords]=React.useState<WeatherRecord[]>([]),[readiness,setReadiness]=React.useState<Readiness>({ready:false}),[selectionVersion,setSelectionVersion]=React.useState(0);
  const [forecasts,setForecasts]=React.useState<WeatherRecord[]>([]),[forecastSelectionVersion,setForecastSelectionVersion]=React.useState(0),[forecastNotice,setForecastNotice]=React.useState('');
  const [loading,setLoading]=React.useState(true),[saving,setSaving]=React.useState(false),[error,setError]=React.useState('');
  const [locationState,setLocationState]=React.useState<'idle'|'capturing'|'captured'|'error'>('idle'),[locationAccuracy,setLocationAccuracy]=React.useState<number|null>(null),[locationError,setLocationError]=React.useState('');
  const [calculateDeltaT,setCalculateDeltaT]=React.useState(true),[deltaT,setDeltaT]=React.useState('');
  const [form,setForm]=React.useState<Record<string,string>>({observerPersonnelId:'',observedAt:localDateTime(),observationLocation:'',latitude:'',longitude:'',temperatureC:'',relativeHumidityPct:'',windSpeedKmh:'',windDirectionDegrees:'',cloudDescription:'',precipitationMm:'0',additionalNotes:'',manualReason:'',inversionAssessment:'NOT_ASSESSED'});
  const update=(key:string)=>(event:React.ChangeEvent<HTMLInputElement>)=>setForm((current)=>({...current,[key]:event.target.value}));
  const load=React.useCallback(async()=>{setLoading(true);setError('');try{const [weather,forecastHistory,assessment,people]=await Promise.all([weatherApi.read(missionId),weatherApi.forecasts(missionId),weatherApi.readiness(missionId),personnelApi.list(operatingLocationId)]);const history=Array.isArray(weather)?weather:(weather?.observations||weather?.records||[]),planning=Array.isArray(forecastHistory)?forecastHistory:[];setRecords(history);setForecasts(planning);setSelectionVersion(history.reduce((maximum:number,record:WeatherRecord)=>Math.max(maximum,Number(value(record,'selection_version','selectionVersion')||0)),Number(weather?.selection_version??weather?.selectionVersion??0)));setForecastSelectionVersion(planning.reduce((maximum:number,record:WeatherRecord)=>Math.max(maximum,Number(value(record,'selection_version','selectionVersion')||0)),0));setReadiness(assessment||{ready:false});setObservers(people.filter((person)=>person.isActive&&person.operatingLocationIds.includes(operatingLocationId)));}catch(caught){setError(caught instanceof Error?caught.message:'Mission Weather could not be loaded.');}finally{setLoading(false);}},[missionId,operatingLocationId,personnelApi,weatherApi]);
  React.useEffect(()=>{void load();},[load]);
  const captureLocation=()=>{setLocationState('capturing');setLocationError('');getCurrentPosition((position)=>{const latitude=Number(position.coords.latitude),longitude=Number(position.coords.longitude),accuracy=Number(position.coords.accuracy);if(!Number.isFinite(latitude)||latitude< -90||latitude>90||!Number.isFinite(longitude)||longitude< -180||longitude>180){setLocationState('error');setLocationError('Current location could not be captured because the device returned invalid coordinates.');return;}setForm((current)=>({...current,latitude:String(latitude),longitude:String(longitude)}));setLocationAccuracy(Number.isFinite(accuracy)?accuracy:null);setLocationState('captured');},()=>{setForm((current)=>({...current,latitude:'',longitude:''}));setLocationAccuracy(null);setLocationState('error');setLocationError('Current location could not be captured. Check location permission and try again.');},{enableHighAccuracy:true,timeout:15000,maximumAge:0});};
  const canSave=!loading&&!saving&&locationState==='captured'&&Boolean(form.observerPersonnelId&&form.observationLocation.trim()&&form.observedAt&&form.temperatureC&&form.relativeHumidityPct&&form.windSpeedKmh&&form.windDirectionDegrees&&form.manualReason.trim()&&form.inversionAssessment&&(calculateDeltaT||deltaT));
  const retrieveForecast=async()=>{if(!scheduledStartAt||!plannedCoordinates){setError('Save a scheduled start and Planning boundary before retrieving a forecast.');return;}setSaving(true);setError('');setForecastNotice('');try{const validFrom=new Date(scheduledStartAt),validTo=new Date(validFrom.getTime()+4*60*60*1000),expectedVersion=forecasts.reduce((maximum,record)=>Math.max(maximum,Number(value(record,'version_number','versionNumber')||0)),0);const forecast=await weatherApi.createForecast(missionId,{expectedVersion,latitude:plannedCoordinates.latitude,longitude:plannedCoordinates.longitude,validFrom:validFrom.toISOString(),validTo:validTo.toISOString()});await weatherApi.selectForecast(missionId,String(value(forecast,'id')),forecastSelectionVersion);setForecasts((current)=>[{...forecast,selected:true,selection_version:forecastSelectionVersion+1},...current.map((record)=>({...record,selected:false}))]);setForecastSelectionVersion((current)=>current+1);setForecastNotice(`Planning forecast version ${value(forecast,'version_number','versionNumber')} selected. It informs planning only and cannot authorise the Mission.`);setReadiness(await weatherApi.readiness(missionId));}catch(caught){setError(caught instanceof Error?caught.message:'Planning forecast could not be retrieved.');}finally{setSaving(false);}};
  const save=async()=>{setSaving(true);setError('');try{const expectedVersion=records.reduce((maximum,record)=>Math.max(maximum,Number(value(record,'version_number','versionNumber')||0)),0);const observation=await weatherApi.createManual(missionId,{observerPersonnelId:form.observerPersonnelId,expectedVersion,observedAt:new Date(form.observedAt).toISOString(),observationLocation:form.observationLocation,latitude:Number(form.latitude),longitude:Number(form.longitude),temperatureC:Number(form.temperatureC),relativeHumidity:Number(form.relativeHumidityPct),windSpeedKmh:Number(form.windSpeedKmh),windDirectionDegrees:Number(form.windDirectionDegrees),cloudDescription:form.cloudDescription,precipitationMm:Number(form.precipitationMm||0),manualReason:form.manualReason,inversionAssessment:form.inversionAssessment,notes:form.additionalNotes,deltaTMode:calculateDeltaT?'CALCULATED':'KESTREL_MEASURED',...(calculateDeltaT?{}:{deltaTC:Number(deltaT)})});setDeltaT(String(value(observation,'delta_t_c','deltaTC')??''));await weatherApi.select(missionId,String(value(observation,'id')),selectionVersion);setRecords((current)=>[{...observation,selected:true,selection_version:selectionVersion+1},...current.map((record)=>({...record,selected:false}))]);setSelectionVersion((current)=>current+1);setReadiness(await weatherApi.readiness(missionId));}catch(caught){setError(caught instanceof Error?caught.message:'Manual Weather could not be saved.');}finally{setSaving(false);}};
  return <Stack spacing={2}>
    {loading&&<LinearProgress/>}{error&&<Alert severity="error">{error} No browser-stored Weather has been substituted.</Alert>}
    <Typography variant="subtitle1" fontWeight={900}>Planning Forecast Weather</Typography>
    <Alert severity="info">Forecast revisions support planning only. They never become observed Weather or Mission Authorisation evidence.</Alert>
    <Button variant="outlined" disabled={loading||saving||!scheduledStartAt||!plannedCoordinates} onClick={()=>void retrieveForecast()}>Retrieve Planning Forecast</Button>
    {forecastNotice&&<Alert severity="success">{forecastNotice}</Alert>}
    {forecasts.length>0&&<Typography variant="body2">{forecasts.length} immutable Planning forecast revision{forecasts.length===1?'':'s'} retained.</Typography>}
    <Divider/>
    <Typography variant="subtitle1" fontWeight={900}>Observed Pre-flight Weather</Typography>
    <Alert severity={readiness.ready?'success':(readiness.blockers?.length?'warning':'info')}>{readiness.ready?'Mission Weather evidence is ready.':'Mission Weather is not ready.'}</Alert>
    {(readiness.blockers||[]).map((item)=><Alert key={item.code} severity="error">{item.message}</Alert>)}
    {(readiness.warnings||[]).map((item)=><Alert key={item.code} severity="warning">{item.message}</Alert>)}
    <Grid container spacing={1.5}>
      <Grid size={{xs:12,md:6}}><TextField select required fullWidth label="Weather observer" InputLabelProps={{shrink:true}} value={form.observerPersonnelId} onChange={update('observerPersonnelId')} SelectProps={{native:true}}><option value="">Select authoritative Personnel</option>{observers.map((observer)=><option key={observer.id} value={observer.id}>{observer.fullName}</option>)}</TextField></Grid>
      <Grid size={{xs:12,md:6}}><TextField required fullWidth type="datetime-local" label="Observation time" inputProps={{'aria-label':'Observation time'}} InputLabelProps={{shrink:true}} value={form.observedAt} onChange={update('observedAt')}/></Grid>
      <Grid size={{xs:12,md:6}}><TextField required fullWidth label="Observation location" inputProps={{'aria-label':'Observation location'}} value={form.observationLocation} onChange={update('observationLocation')}/></Grid>
      <Grid size={{xs:12}}><Button variant="outlined" disabled={locationState==='capturing'} onClick={captureLocation}>{locationState==='capturing'?'Capturing current location…':'Capture current location'}</Button></Grid>
      {locationError&&<Grid size={{xs:12}}><Alert severity="error">{locationError}</Alert></Grid>}
      {locationState==='captured'&&<Grid size={{xs:12}}><Alert severity="success">Current location captured{locationAccuracy===null?'':` · ${Math.round(locationAccuracy)} m accuracy`}.</Alert></Grid>}
      <Grid size={{xs:6,md:3}}><TextField required fullWidth type="number" label="Latitude" inputProps={{'aria-label':'Latitude',readOnly:true}} value={form.latitude}/></Grid>
      <Grid size={{xs:6,md:3}}><TextField required fullWidth type="number" label="Longitude" inputProps={{'aria-label':'Longitude',readOnly:true}} value={form.longitude}/></Grid>
      <Grid size={{xs:6,md:3}}><TextField required fullWidth type="number" label="Temperature (°C)" inputProps={{'aria-label':'Temperature (°C)'}} value={form.temperatureC} onChange={update('temperatureC')}/></Grid>
      <Grid size={{xs:6,md:3}}><TextField required fullWidth type="number" label="Relative humidity (%)" inputProps={{'aria-label':'Relative humidity (%)'}} value={form.relativeHumidityPct} onChange={update('relativeHumidityPct')}/></Grid>
      <Grid size={{xs:6,md:3}}><TextField required fullWidth type="number" label="Wind speed (km/h)" inputProps={{'aria-label':'Wind speed (km/h)'}} value={form.windSpeedKmh} onChange={update('windSpeedKmh')}/></Grid>
      <Grid size={{xs:6,md:3}}><TextField required fullWidth type="number" label="Wind direction (degrees)" inputProps={{'aria-label':'Wind direction (degrees)'}} value={form.windDirectionDegrees} onChange={update('windDirectionDegrees')}/></Grid>
      <Grid size={{xs:12,md:6}}><TextField select required fullWidth label="Inversion assessment" value={form.inversionAssessment} onChange={update('inversionAssessment')} SelectProps={{native:true}}><option value="NOT_ASSESSED">Not assessed</option><option value="UNLIKELY">Unlikely</option><option value="POSSIBLE">Possible</option><option value="LIKELY">Likely</option><option value="CONFIRMED">Confirmed</option><option value="UNABLE_TO_DETERMINE">Unable to determine</option></TextField></Grid>
      <Grid size={{xs:12,md:6}}><TextField fullWidth label="Cloud description" value={form.cloudDescription} onChange={update('cloudDescription')}/></Grid>
      <Grid size={{xs:12,md:6}}><TextField fullWidth type="number" label="Rain or precipitation (mm)" value={form.precipitationMm} onChange={update('precipitationMm')}/></Grid>
      <Grid size={{xs:12}}><TextField required fullWidth multiline minRows={2} label="Reason for manual entry" inputProps={{'aria-label':'Reason for manual entry'}} value={form.manualReason} onChange={update('manualReason')}/></Grid>
      <Grid size={{xs:12}}><TextField fullWidth multiline minRows={2} label="Additional notes" value={form.additionalNotes} onChange={update('additionalNotes')}/></Grid>
    </Grid>
    <FormControlLabel control={<Checkbox checked={calculateDeltaT} onChange={(event)=>{setCalculateDeltaT(event.target.checked);setDeltaT('');}}/>} label="Calculate Delta T from temperature and humidity"/>
    <TextField required fullWidth type="number" label="Delta T (°C)" inputProps={{'aria-label':'Delta T (°C)',readOnly:calculateDeltaT}} value={deltaT} onChange={calculateDeltaT?undefined:(event)=>setDeltaT(event.target.value)} helperText={calculateDeltaT?'Calculated authoritatively by Spray Command when saved.':'Enter the Delta T displayed by the on-site Kestrel.'}/>
    <Button variant="contained" disabled={!canSave} onClick={()=>void save()}>{saving?'Saving authoritative Weather…':'Save Manual Weather'}</Button>
    {records.length>0&&<><Divider/><Typography variant="subtitle2" fontWeight={800}>Authoritative observation history</Typography>{records.map((record,index)=>{const deltaSource=value(record,'delta_t_source','deltaTSource');const varianceWarning=Boolean(value(record,'delta_t_variance_warning','deltaTVarianceWarning'));return <Stack key={String(value(record,'id')||index)} spacing={0.5}><Stack direction={{xs:'column',sm:'row'}} spacing={1} alignItems={{sm:'center'}}><Chip size="small" color={index===0?'success':'default'} label={`Version ${value(record,'version_number','versionNumber')||'—'}`}/><Typography variant="body2">{value(record,'source')||'MANUAL'} · {value(record,'freshness_state','freshnessState')||'Freshness evaluated on retrieval'}</Typography></Stack>{value(record,'delta_t_c','deltaTC')!==undefined&&value(record,'delta_t_c','deltaTC')!==null&&<Typography variant="subtitle2" fontWeight={800}>Authoritative Delta T: {value(record,'delta_t_c','deltaTC')} °C</Typography>}{deltaSource&&<Typography variant="body2">Source: {deltaSource==='KESTREL_MEASURED'?'Kestrel measured':'Calculated from temperature and humidity'}</Typography>}{varianceWarning&&<Alert severity="warning">Kestrel Delta T differs from the calculated comparison ({value(record,'calculated_delta_t_c','calculatedDeltaTC')} °C). The Kestrel value remains authoritative.</Alert>}</Stack>;})}</>}
  </Stack>;
}
