import React from 'react';
import {Alert,Button,Chip,Divider,Grid,IconButton,LinearProgress,MenuItem,Stack,TextField,Typography} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import {createMissionChemicalApi} from '../../services/missionChemicalApi';
import {ChemicalIntelligenceResult,ChemicalPlanLineInput,ChemicalRateUnit,MissionChemicalPlan} from '../../types/missionChemicals';
type Api=ReturnType<typeof createMissionChemicalApi>;const defaultApi=createMissionChemicalApi();
const emptyLine=():ChemicalPlanLineInput=>({productName:'',matchState:'UNMATCHED',rate:0,rateUnit:'L_HA'});
const n=(value:unknown)=>Number(value||0);
export default function MissionChemicalPlanning({missionId,defaultAreaHa=0,api=defaultApi}:{missionId:string;defaultAreaHa?:number;api?:Api}){
 const[plan,setPlan]=React.useState<MissionChemicalPlan|null>(null),[lines,setLines]=React.useState<ChemicalPlanLineInput[]>([emptyLine()]),[area,setArea]=React.useState(String(defaultAreaHa||'')),[volume,setVolume]=React.useState('40'),[tank,setTank]=React.useState('40'),[loading,setLoading]=React.useState(true),[saving,setSaving]=React.useState(false),[error,setError]=React.useState(''),[notice,setNotice]=React.useState(''),[results,setResults]=React.useState<Record<number,ChemicalIntelligenceResult[]>>({});
 React.useEffect(()=>{let active=true;setLoading(true);api.read(missionId).then(record=>{if(!active)return;setPlan(record);if(record){setArea(String(record.treatment_area_ha));setVolume(String(record.application_volume_l_ha));setTank(String(record.tank_capacity_l));setLines(record.lines.map(line=>({productName:line.productName||String((line as any).product_name),matchState:line.matchState||((line as any).match_state),platformProductId:line.platformProductId||String((line as any).platform_product_id||''),platformProductVersionId:line.platformProductVersionId||String((line as any).platform_product_version_id||''),manufacturer:line.manufacturer,apvmaNumber:line.apvmaNumber||String((line as any).apvma_number||''),activeIngredient:line.activeIngredient||String((line as any).active_ingredient||''),formulation:line.formulation,rate:n(line.rate),rateUnit:line.rateUnit||((line as any).rate_unit)})));}}).catch(c=>active&&setError(c instanceof Error?c.message:'Chemical plan could not be loaded.')).finally(()=>active&&setLoading(false));return()=>{active=false};},[api,missionId]);
 const update=(index:number,values:Partial<ChemicalPlanLineInput>)=>setLines(current=>current.map((line,i)=>i===index?{...line,...values}:line));
 const search=async(index:number)=>{const q=lines[index].productName.trim();if(q.length<2)return;try{const matches=await api.search(q);setResults(current=>({...current,[index]:matches}));}catch(c){setError(c instanceof Error?c.message:'Chemical search failed.');}};
 const select=(index:number,result:ChemicalIntelligenceResult)=>{update(index,{productName:result.version.display_name,matchState:'VERIFIED',platformProductId:result.id,platformProductVersionId:result.version.id,manufacturer:result.manufacturer,apvmaNumber:result.apvma_number,activeIngredient:result.version.active_ingredient,formulation:result.version.formulation});setResults(current=>({...current,[index]:[]}));};
 const valid=n(area)>0&&n(volume)>0&&n(tank)>0&&lines.every(line=>line.productName.trim()&&n(line.rate)>0);
 const save=async()=>{setSaving(true);setError('');setNotice('');try{const result=await api.save(missionId,{expectedVersion:plan?.version_number||0,treatmentAreaHa:n(area),applicationVolumeLHa:n(volume),tankCapacityL:n(tank),lines});setPlan(result.record);setNotice(result.unmatchedReviewCreated?'Saved. An unmatched product was sent automatically to the Chemical Intelligence research queue. Mission planning can continue.':'Authoritative chemical plan saved.');}catch(c){setError(c instanceof Error?c.message:'Chemical plan could not be saved.');}finally{setSaving(false);}};
 return <Stack spacing={2}>{loading&&<LinearProgress/>}{error&&<Alert severity="error">{error} No browser-stored chemical plan has been substituted.</Alert>}{notice&&<Alert severity="success">{notice}</Alert>}
 <Alert severity="info">Products not yet in the verified register are permitted for planning and automatically flagged for platform research.</Alert>
 <Grid container spacing={1.5}><Grid size={{xs:12,md:4}}><TextField fullWidth required type="number" label="Treatment area (ha)" value={area} onChange={e=>setArea(e.target.value)}/></Grid><Grid size={{xs:12,md:4}}><TextField fullWidth required type="number" label="Application volume (L/ha)" value={volume} onChange={e=>setVolume(e.target.value)}/></Grid><Grid size={{xs:12,md:4}}><TextField fullWidth required type="number" label="Tank capacity (L)" value={tank} onChange={e=>setTank(e.target.value)}/></Grid></Grid>
 {lines.map((line,index)=><Stack key={index} spacing={1} sx={{p:1.5,border:'1px solid',borderColor:'divider',borderRadius:2}}><Stack direction="row" spacing={1}><TextField fullWidth required label="Product" value={line.productName} onChange={e=>update(index,{productName:e.target.value,matchState:'UNMATCHED',platformProductId:undefined,platformProductVersionId:undefined})}/><Button variant="outlined" onClick={()=>void search(index)}>Search register</Button><IconButton aria-label="Remove chemical" disabled={lines.length===1} onClick={()=>setLines(current=>current.filter((_,i)=>i!==index))}><DeleteOutlineIcon/></IconButton></Stack>{(results[index]||[]).map(result=><Button key={result.id} variant="text" onClick={()=>select(index,result)} sx={{justifyContent:'flex-start'}}>{result.version.display_name} · {result.manufacturer||'Manufacturer not recorded'} · verified</Button>)}
 <Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField required type="number" label="Rate" value={line.rate||''} onChange={e=>update(index,{rate:Number(e.target.value)})}/><TextField select label="Rate unit" value={line.rateUnit} onChange={e=>update(index,{rateUnit:e.target.value as ChemicalRateUnit})}>{(['L_HA','ML_HA','KG_HA','G_HA']as const).map(unit=><MenuItem key={unit} value={unit}>{unit.replace('_HA','/ha')}</MenuItem>)}</TextField><Chip color={line.matchState==='VERIFIED'?'success':'warning'} label={line.matchState==='VERIFIED'?'Verified intelligence':'Unmatched · admin review'}/></Stack></Stack>)}
 <Button startIcon={<AddIcon/>} variant="outlined" onClick={()=>setLines(current=>[...current,emptyLine()])}>Add chemical</Button>
 {plan&&<><Divider/><Typography fontWeight={800}>Authoritative version {plan.version_number}</Typography><Grid container spacing={1}><Grid size={{xs:6,md:3}}><Typography variant="body2">Total spray</Typography><Typography fontWeight={800}>{plan.total_spray_volume_l} L</Typography></Grid><Grid size={{xs:6,md:3}}><Typography variant="body2">Water</Typography><Typography fontWeight={800}>{plan.water_required_l} L</Typography></Grid><Grid size={{xs:6,md:3}}><Typography variant="body2">Hectares/batch</Typography><Typography fontWeight={800}>{plan.hectares_per_batch}</Typography></Grid><Grid size={{xs:6,md:3}}><Typography variant="body2">Batches</Typography><Typography fontWeight={800}>{plan.batch_count}</Typography></Grid></Grid>{plan.lines.map(line=><Typography key={line.id} variant="body2">{String((line as any).product_name||line.productName)}: {line.total_product_quantity} {line.total_product_unit} total · {line.product_per_batch} {line.total_product_unit}/batch</Typography>)}</>}
 <Button variant="contained" disabled={!valid||saving||loading} onClick={()=>void save()}>{saving?'Saving authoritative chemical plan…':'Save Chemical Plan'}</Button></Stack>;
}
