\set ON_ERROR_STOP on
begin transaction read only;

with
controlled_applications as (
  select application.*,
    (select count(*)::integer from public.commercial_onboarding_invitations invitation where invitation.application_id=application.id) invitation_count,
    (select array_agg(event.to_status order by event.created_at,event.id) from public.commercial_onboarding_application_events event where event.application_id=application.id) history
  from public.commercial_onboarding_applications application
  where application.application_reference ~ '^SC-APP-[A-Z0-9]+$'
    and application.business_name ~ '^SC ACCEPTANCE — [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{3}Z ONBOARDING$'
),
controlled_invitations as (
  select invitation.*, application.business_name, application.application_reference,
    (select array_agg(event.to_status order by event.created_at,event.id) from public.commercial_onboarding_invitation_events event where event.invitation_id=invitation.id and event.application_id=application.id) history,
    (select count(*)::integer from public.audit_events audit where audit.organisation_id=invitation.resulting_organisation_id and audit.event_type='commercial_onboarding.accepted' and audit.entity_id=invitation.id) accepted_audit_count
  from public.commercial_onboarding_invitations invitation join controlled_applications application on application.id=invitation.application_id
),
accepted as (
  select invitation.*, organisation.archived_at organisation_archived_at
  from controlled_invitations invitation left join public.organisations organisation on organisation.id=invitation.resulting_organisation_id and organisation.name=invitation.business_name
  where invitation.status='ACCEPTED'
),
rows(predicate,scope_id,category,expected,actual,passed) as (
  select 'governed_application_exists','a865f157-c334-447e-aa1e-661ee0db7b85','identity','1',count(*)::text,count(*)=1 from public.commercial_onboarding_applications where id='a865f157-c334-447e-aa1e-661ee0db7b85'
  union all select 'governed_invitation_exists','29b9b342-335e-4959-9402-4cb4e1090427','identity','1',count(*)::text,count(*)=1 from public.commercial_onboarding_invitations where id='29b9b342-335e-4959-9402-4cb4e1090427'
  union all select 'governed_organisation_exists','961a4354-40f5-479d-a577-74839596ad14','identity','1',count(*)::text,count(*)=1 from public.organisations where id='961a4354-40f5-479d-a577-74839596ad14'
  union all select 'governed_fixture_linkage','961a4354-40f5-479d-a577-74839596ad14','provenance','1',count(*)::text,count(*)=1 from public.commercial_onboarding_applications application join public.commercial_onboarding_invitations invitation on invitation.id='29b9b342-335e-4959-9402-4cb4e1090427' and invitation.application_id=application.id join public.organisations organisation on organisation.id='961a4354-40f5-479d-a577-74839596ad14' and organisation.id=invitation.resulting_organisation_id and organisation.name=application.business_name where application.id='a865f157-c334-447e-aa1e-661ee0db7b85' and application.application_reference='SC-APP-FD04165C43EA' and application.business_name ~ '^SC ACCEPTANCE — [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{3}Z ONBOARDING$' and organisation.archived_at is not null
  union all select 'application_status',id::text,'historical evidence','APPROVED',status,status='APPROVED' from controlled_applications
  union all select 'application_row_version',id::text,'historical evidence','3',row_version::text,row_version=3 from controlled_applications
  union all select 'application_history',id::text,'historical evidence','SUBMITTED>UNDER_REVIEW>APPROVED',coalesce(array_to_string(history,'>'),'NULL'),history is not distinct from array['SUBMITTED','UNDER_REVIEW','APPROVED']::text[] from controlled_applications
  union all select 'application_invitation_cardinality',id::text,'provenance','1',invitation_count::text,invitation_count=1 from controlled_applications
  union all select 'invitation_status_supported',id::text,'historical evidence','SENT|ACCEPTED',status,status in('SENT','ACCEPTED') from controlled_invitations
  union all select 'sent_invitation_version',id::text,'historical evidence','2',row_version::text,row_version=2 from controlled_invitations where status='SENT'
  union all select 'sent_invitation_identity_absent',id::text,'identity','true',(accepted_by_auth_user_id is null and resulting_organisation_id is null and resulting_internal_user_id is null and resulting_membership_id is null and resulting_operating_location_id is null)::text,(accepted_by_auth_user_id is null and resulting_organisation_id is null and resulting_internal_user_id is null and resulting_membership_id is null and resulting_operating_location_id is null) from controlled_invitations where status='SENT'
  union all select 'sent_invitation_history',id::text,'historical evidence','PENDING>SENT',coalesce(array_to_string(history,'>'),'NULL'),history is not distinct from array['PENDING','SENT']::text[] from controlled_invitations where status='SENT'
  union all select 'accepted_invitation_version',id::text,'historical evidence','3',row_version::text,row_version=3 from controlled_invitations where status='ACCEPTED'
  union all select 'accepted_invitation_identity_complete',id::text,'identity','true',(accepted_by_auth_user_id is not null and resulting_organisation_id is not null and resulting_internal_user_id is not null and resulting_membership_id is not null and resulting_operating_location_id is not null)::text,(accepted_by_auth_user_id is not null and resulting_organisation_id is not null and resulting_internal_user_id is not null and resulting_membership_id is not null and resulting_operating_location_id is not null) from controlled_invitations where status='ACCEPTED'
  union all select 'accepted_invitation_history',id::text,'historical evidence','PENDING>SENT>ACCEPTED',coalesce(array_to_string(history,'>'),'NULL'),history is not distinct from array['PENDING','SENT','ACCEPTED']::text[] from controlled_invitations where status='ACCEPTED'
  union all select 'accepted_invitation_audit',id::text,'archive evidence','1',accepted_audit_count::text,accepted_audit_count=1 from controlled_invitations where status='ACCEPTED'
  union all select 'accepted_organisation_link',id::text,'provenance','1',(select count(*)::text from public.organisations organisation where organisation.id=invitation.resulting_organisation_id and organisation.name=invitation.business_name),(select count(*)=1 from public.organisations organisation where organisation.id=invitation.resulting_organisation_id and organisation.name=invitation.business_name) from controlled_invitations invitation where status='ACCEPTED'
  union all select 'organisation_accepted_provenance',organisation.id::text,'provenance','1',(select count(*)::text from controlled_invitations invitation where invitation.status='ACCEPTED' and invitation.resulting_organisation_id=organisation.id and invitation.business_name=organisation.name),(select count(*)=1 from controlled_invitations invitation where invitation.status='ACCEPTED' and invitation.resulting_organisation_id=organisation.id and invitation.business_name=organisation.name) from public.organisations organisation where organisation.name ~ '^SC ACCEPTANCE — [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{3}Z ONBOARDING$'
  union all select 'ambiguous_provenance_count','controlled','provenance','0',count(*)::text,count(*)=0 from public.organisations organisation where organisation.name ~ '^SC ACCEPTANCE — [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{3}Z ONBOARDING$' and (select count(*) from controlled_invitations invitation where invitation.status='ACCEPTED' and invitation.resulting_organisation_id=organisation.id and invitation.business_name=organisation.name)<>1
  union all select 'active_controlled_organisation_count','controlled','operational state','0',count(*)::text,count(*)=0 from accepted where organisation_archived_at is null
  union all select predicate, a.resulting_organisation_id::text, category, expected, actual, passed from accepted a cross join lateral (values
    ('organisation_archived','operational state','true',(a.organisation_archived_at is not null)::text,a.organisation_archived_at is not null),
    ('internal_user_cardinality','identity','1',(select count(*)::text from public.internal_users r where r.organisation_id=a.resulting_organisation_id),(select count(*)=1 from public.internal_users r where r.organisation_id=a.resulting_organisation_id)),
    ('internal_user_final_state','identity','1',(select count(*)::text from public.internal_users r where r.id=a.resulting_internal_user_id and r.organisation_id=a.resulting_organisation_id and r.auth_user_id=a.accepted_by_auth_user_id and not r.is_active and r.archived_at is not null),(select count(*)=1 from public.internal_users r where r.id=a.resulting_internal_user_id and r.organisation_id=a.resulting_organisation_id and r.auth_user_id=a.accepted_by_auth_user_id and not r.is_active and r.archived_at is not null)),
    ('membership_cardinality','identity','1',(select count(*)::text from public.memberships r where r.organisation_id=a.resulting_organisation_id),(select count(*)=1 from public.memberships r where r.organisation_id=a.resulting_organisation_id)),
    ('membership_final_state','identity','1',(select count(*)::text from public.memberships r where r.id=a.resulting_membership_id and r.organisation_id=a.resulting_organisation_id and r.internal_user_id=a.resulting_internal_user_id and not r.is_active and r.archived_at is not null),(select count(*)=1 from public.memberships r where r.id=a.resulting_membership_id and r.organisation_id=a.resulting_organisation_id and r.internal_user_id=a.resulting_internal_user_id and not r.is_active and r.archived_at is not null)),
    ('location_cardinality','identity','1',(select count(*)::text from public.operating_locations r where r.organisation_id=a.resulting_organisation_id),(select count(*)=1 from public.operating_locations r where r.organisation_id=a.resulting_organisation_id)),
    ('location_final_state','identity','1',(select count(*)::text from public.operating_locations r where r.id=a.resulting_operating_location_id and r.organisation_id=a.resulting_organisation_id and r.archived_at is not null),(select count(*)=1 from public.operating_locations r where r.id=a.resulting_operating_location_id and r.organisation_id=a.resulting_organisation_id and r.archived_at is not null)),
    ('seat_allocation_final_state','identity','1',(select count(*)::text from public.organisation_seat_allocations r where r.organisation_id=a.resulting_organisation_id and r.archived_at is not null),(select count(*)=1 from public.organisation_seat_allocations r where r.organisation_id=a.resulting_organisation_id and r.archived_at is not null)),
    ('seat_assignment_cardinality','identity','1',(select count(*)::text from public.internal_user_seat_assignments r where r.organisation_id=a.resulting_organisation_id),(select count(*)=1 from public.internal_user_seat_assignments r where r.organisation_id=a.resulting_organisation_id)),
    ('seat_assignment_final_state','identity','1',(select count(*)::text from public.internal_user_seat_assignments r where r.organisation_id=a.resulting_organisation_id and r.internal_user_id=a.resulting_internal_user_id and r.membership_id=a.resulting_membership_id and r.organisation_seat_allocation_id=(select allocation.id from public.organisation_seat_allocations allocation where allocation.organisation_id=a.resulting_organisation_id) and r.status='revoked' and r.archived_at is not null),(select count(*)=1 from public.internal_user_seat_assignments r where r.organisation_id=a.resulting_organisation_id and r.internal_user_id=a.resulting_internal_user_id and r.membership_id=a.resulting_membership_id and r.organisation_seat_allocation_id=(select allocation.id from public.organisation_seat_allocations allocation where allocation.organisation_id=a.resulting_organisation_id) and r.status='revoked' and r.archived_at is not null)),
    ('base_assignment_cardinality','identity','1',(select count(*)::text from public.membership_operating_location_assignments r where r.organisation_id=a.resulting_organisation_id),(select count(*)=1 from public.membership_operating_location_assignments r where r.organisation_id=a.resulting_organisation_id)),
    ('base_assignment_final_state','identity','1',(select count(*)::text from public.membership_operating_location_assignments r where r.organisation_id=a.resulting_organisation_id and r.membership_id=a.resulting_membership_id and r.operating_location_id=a.resulting_operating_location_id and not r.is_active and r.archived_at is not null),(select count(*)=1 from public.membership_operating_location_assignments r where r.organisation_id=a.resulting_organisation_id and r.membership_id=a.resulting_membership_id and r.operating_location_id=a.resulting_operating_location_id and not r.is_active and r.archived_at is not null)),
    ('active_identity_residue','identity','0',((select count(*) from public.internal_users r where r.organisation_id=a.resulting_organisation_id and (r.is_active or r.archived_at is null))+(select count(*) from public.memberships r where r.organisation_id=a.resulting_organisation_id and (r.is_active or r.archived_at is null))+(select count(*) from public.operating_locations r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null)+(select count(*) from public.organisation_seat_allocations r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null)+(select count(*) from public.internal_user_seat_assignments r where r.organisation_id=a.resulting_organisation_id and (r.status<>'revoked' or r.archived_at is null))+(select count(*) from public.membership_operating_location_assignments r where r.organisation_id=a.resulting_organisation_id and (r.is_active or r.archived_at is null)))::text,not exists(select 1 from public.internal_users r where r.organisation_id=a.resulting_organisation_id and (r.is_active or r.archived_at is null)) and not exists(select 1 from public.memberships r where r.organisation_id=a.resulting_organisation_id and (r.is_active or r.archived_at is null)) and not exists(select 1 from public.operating_locations r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null) and not exists(select 1 from public.organisation_seat_allocations r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null) and not exists(select 1 from public.internal_user_seat_assignments r where r.organisation_id=a.resulting_organisation_id and (r.status<>'revoked' or r.archived_at is null)) and not exists(select 1 from public.membership_operating_location_assignments r where r.organisation_id=a.resulting_organisation_id and (r.is_active or r.archived_at is null))),
    ('platform_user_residue','identity','0',(select count(*)::text from public.platform_users r where r.auth_user_id=a.accepted_by_auth_user_id),(select count(*)=0 from public.platform_users r where r.auth_user_id=a.accepted_by_auth_user_id)),
    ('personnel_residue','Personnel','0',(select count(*)::text from public.personnel r where r.organisation_id=a.resulting_organisation_id),(select count(*)=0 from public.personnel r where r.organisation_id=a.resulting_organisation_id)),
    ('profile_residue','operational state','0',(select count(*)::text from public.ftf_profiles r where r.tenant_id=a.resulting_organisation_id),(select count(*)=0 from public.ftf_profiles r where r.tenant_id=a.resulting_organisation_id)),
    ('store_residue','store residue','0',(select count(*)::text from public.ftf_store r where r.tenant_id=a.resulting_organisation_id),(select count(*)=0 from public.ftf_store r where r.tenant_id=a.resulting_organisation_id)),
    ('client_residue','operational state','0',(select count(*)::text from public.clients r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null),(select count(*)=0 from public.clients r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null)),
    ('property_residue','operational state','0',(select count(*)::text from public.properties r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null),(select count(*)=0 from public.properties r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null)),
    ('field_residue','operational state','0',(select count(*)::text from public.fields r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null),(select count(*)=0 from public.fields r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null)),
    ('job_residue','operational state','0',(select count(*)::text from public.jobs r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null),(select count(*)=0 from public.jobs r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null)),
    ('mission_residue','operational state','0',(select count(*)::text from public.missions r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null),(select count(*)=0 from public.missions r where r.organisation_id=a.resulting_organisation_id and r.archived_at is null)),
    ('archive_audit_cardinality','archive evidence','1',(select count(*)::text from public.audit_events audit where audit.organisation_id=a.resulting_organisation_id and audit.event_type='commercial_onboarding.acceptance_archived' and audit.entity_type='organisation' and audit.entity_id=a.resulting_organisation_id and audit.event_payload->>'applicationId'=a.application_id::text and audit.event_payload->>'invitationId'=a.id::text),(select count(*)=1 from public.audit_events audit where audit.organisation_id=a.resulting_organisation_id and audit.event_type='commercial_onboarding.acceptance_archived' and audit.entity_type='organisation' and audit.entity_id=a.resulting_organisation_id and audit.event_payload->>'applicationId'=a.application_id::text and audit.event_payload->>'invitationId'=a.id::text)),
    ('archive_outbox_cardinality','archive evidence','1',(select count(*)::text from public.transactional_outbox outbox where outbox.organisation_id=a.resulting_organisation_id and outbox.topic='commercial_onboarding.acceptance_archived' and outbox.aggregate_type='organisation' and outbox.aggregate_id=a.resulting_organisation_id and outbox.payload->>'organisationId'=a.resulting_organisation_id::text and outbox.payload->>'applicationId'=a.application_id::text and outbox.payload->>'invitationId'=a.id::text),(select count(*)=1 from public.transactional_outbox outbox where outbox.organisation_id=a.resulting_organisation_id and outbox.topic='commercial_onboarding.acceptance_archived' and outbox.aggregate_type='organisation' and outbox.aggregate_id=a.resulting_organisation_id and outbox.payload->>'organisationId'=a.resulting_organisation_id::text and outbox.payload->>'applicationId'=a.application_id::text and outbox.payload->>'invitationId'=a.id::text))
  ) v(predicate,category,expected,actual,passed)
  union all select predicate,p.id::text,'Personnel','0',actual,actual='0' from public.personnel p join accepted a on a.resulting_organisation_id=p.organisation_id cross join lateral (values
    ('personnel_base_link_count',(select count(*)::text from public.personnel_operating_locations r where r.organisation_id=p.organisation_id and r.personnel_id=p.id)),
    ('personnel_role_link_count',(select count(*)::text from public.personnel_operational_roles r where r.organisation_id=p.organisation_id and r.personnel_id=p.id)),
    ('personnel_credential_count',(select count(*)::text from public.personnel_credentials r where r.organisation_id=p.organisation_id and r.personnel_id=p.id)),
    ('personnel_evidence_count',(select count(*)::text from public.personnel_evidence r where r.organisation_id=p.organisation_id and r.personnel_id=p.id)),
    ('personnel_mission_assignment_count',(select count(*)::text from public.mission_personnel_assignments r where r.organisation_id=p.organisation_id and r.personnel_id=p.id))
  ) v(predicate,actual)
)
select jsonb_build_object(
  'recordType','integrity-predicate','predicate',predicate,'scopeId',scope_id,
  'category',category,'result',case when passed then 'PASS' else 'FAIL' end,
  'expected',expected,'actual',actual
) diagnostic
from rows
order by predicate,scope_id;

commit;
