import { readFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { PGlite } from '@electric-sql/pglite';

const migrationDirectory=resolve(dirname(fileURLToPath(import.meta.url)),'../supabase/migrations');
const ids={org:'30000000-0000-4000-8000-000000000001',otherOrg:'40000000-0000-4000-8000-000000000001',actor:'30000000-0000-4000-8000-000000000101',otherActor:'40000000-0000-4000-8000-000000000101',location:'30000000-0000-4000-8000-000000001001',otherLocation:'40000000-0000-4000-8000-000000001001',membership:'30000000-0000-4000-8000-000000000121'};
const db=new PGlite();
try{
 await db.exec(`create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select null::uuid$$;create role anon;create role authenticated;create role service_role;`);
 for(const name of (await readdir(migrationDirectory)).filter(n=>n.endsWith('.sql')).sort())await db.exec(await readFile(resolve(migrationDirectory,name),'utf8'));
 await db.exec(`insert into auth.users(id)values('30000000-0000-4000-8000-000000000011'),('40000000-0000-4000-8000-000000000011');
 insert into public.organisations(id,organisation_id,name)values('${ids.org}','${ids.org}','Fly The Farm'),('${ids.otherOrg}','${ids.otherOrg}','Other');
 insert into public.internal_users(id,organisation_id,auth_user_id,display_name)values('${ids.actor}','${ids.org}','30000000-0000-4000-8000-000000000011','Admin'),('${ids.otherActor}','${ids.otherOrg}','40000000-0000-4000-8000-000000000011','Other');
 insert into public.roles(id,organisation_id,code,name)values('30000000-0000-4000-8000-000000000111','${ids.org}','admin','Admin'),('40000000-0000-4000-8000-000000000111','${ids.otherOrg}','admin','Admin');
 insert into public.memberships(id,organisation_id,internal_user_id,role_id)values('${ids.membership}','${ids.org}','${ids.actor}','30000000-0000-4000-8000-000000000111'),('40000000-0000-4000-8000-000000000121','${ids.otherOrg}','${ids.otherActor}','40000000-0000-4000-8000-000000000111');
 insert into public.operating_locations(id,organisation_id,name)values('${ids.location}','${ids.org}','FTF Base'),('${ids.otherLocation}','${ids.otherOrg}','Other Base');`);
 await db.query(`select public.ftf_seed_internal_beta_access('${ids.org}','${ids.actor}')`);
 await db.query(`select public.ftf_seed_internal_beta_access('${ids.otherOrg}','${ids.otherActor}')`);
 const job=await db.query(`select public.ftf_write_operational_resource('${ids.org}','${ids.actor}','clients','create',null,null,'{"name":"Personnel Client"}'::jsonb) result`);const clientId=job.rows[0].result.record.id;
 const property=await db.query(`select public.ftf_write_operational_resource('${ids.org}','${ids.actor}','properties','create',null,null,$1::jsonb) result`,[JSON.stringify({client_id:clientId,name:'Personnel Property',address:'Base',state:'QLD'})]);const propertyId=property.rows[0].result.record.id;
 const field=await db.query(`select public.ftf_write_operational_resource('${ids.org}','${ids.actor}','fields','create',null,null,$1::jsonb) result`,[JSON.stringify({property_id:propertyId,name:'Personnel Field',area_hectares:10})]);const fieldId=field.rows[0].result.record.id;
 const jobRecord=await db.query(`select public.ftf_write_operational_resource('${ids.org}','${ids.actor}','jobs','create',null,null,$1::jsonb) result`,[JSON.stringify({client_id:clientId,property_id:propertyId,field_ids:[fieldId],reference:'PER-1',scope:'Personnel Job',status:'draft',scheduled_date:'2026-08-10'})]);const jobId=jobRecord.rows[0].result.record.id;
 const mission=await db.query(`select public.ftf_write_operational_resource('${ids.org}','${ids.actor}','missions','create',null,null,$1::jsonb) result`,[JSON.stringify({job_id:jobId,operating_location_id:ids.location,mission_number:'PER-M1',title:'Personnel Mission',scheduled_start_at:'2026-08-10T09:00:00Z',status:'planning',aircraft_id:null,equipment_kit_id:null})]);const missionId=mission.rows[0].result.record.id;

 const payload={fullName:'Alex Pilot',preferredName:'Alex',email:'alex@example.com',phone:'0400000000',engagementStatus:'contractor',isActive:true,emergencyContact:{name:'Private Contact'},privateNotes:'Restricted',notes:'Operational',startDate:'2026-01-01',endDate:'',operatingLocationIds:[ids.location],operationalRoles:['pilot_in_command','pilot']};
 const created=await db.query(`select public.ftf_write_personnel('${ids.org}','${ids.actor}','create',null,null,$1::jsonb) result`,[JSON.stringify(payload)]);const person=created.rows[0].result.record;if(!person?.id||person.row_version!==1||person.internal_user_id)throw new Error('non-login Personnel create failed');
 const redacted=await db.query(`select * from public.ftf_list_personnel('${ids.org}','${ids.location}',false)`);if(redacted.rows[0].ftf_list_personnel.emergency_contact!==null||redacted.rows[0].ftf_list_personnel.private_notes!==null)throw new Error('private Personnel fields leaked');
 const privateRead=await db.query(`select * from public.ftf_list_personnel('${ids.org}','${ids.location}',true)`);if(privateRead.rows[0].ftf_list_personnel.private_notes!=='Restricted')throw new Error('authorised private Personnel read failed');
 const stale=await db.query(`select public.ftf_write_personnel('${ids.org}','${ids.actor}','update','${person.id}',99,$1::jsonb) result`,[JSON.stringify(payload)]);if(!stale.rows[0].result.conflict)throw new Error('stale Personnel write accepted');
 const otherRead=await db.query(`select * from public.ftf_list_personnel('${ids.otherOrg}',null,false)`);if(otherRead.rows.length)throw new Error('cross-tenant Personnel leaked');
 const linked=await db.query(`select public.ftf_link_personnel_member('${ids.org}','${ids.actor}','${person.id}',1,'${ids.actor}','${ids.membership}') result`);if(linked.rows[0].result.record.id!==person.id||linked.rows[0].result.record.row_version!==2)throw new Error('member link replaced identity');
 const credential=await db.query(`select public.ftf_write_personnel_credential('${ids.org}','${ids.actor}','${person.id}',$1::jsonb) result`,[JSON.stringify({credentialType:'RePL',credentialKind:'licence',identifier:'RePL-001',issuer:'CASA',issueDate:'2026-01-01',expiryDate:'2026-08-09',status:'current',verificationState:'verified',jurisdiction:'AU',notes:''})]);if(!credential.rows[0].result.record.id)throw new Error('credential create failed');
 const blocked=await db.query(`select public.ftf_save_mission_personnel('${ids.org}','${ids.actor}','${missionId}',0,$1::jsonb) result`,[JSON.stringify([{personnelId:person.id,assignmentRole:'pilot_in_command'}])]);if(blocked.rows[0].result.qualification_blockers?.[0]?.code!=='PIC_CREDENTIAL_INVALID')throw new Error('expired PIC credential was accepted');
 await db.query(`update public.personnel_credentials set expiry_date='2027-08-10' where organisation_id='${ids.org}' and id='${credential.rows[0].result.record.id}'`);
 const saved=await db.query(`select public.ftf_save_mission_personnel('${ids.org}','${ids.actor}','${missionId}',0,$1::jsonb) result`,[JSON.stringify([{personnelId:person.id,assignmentRole:'pilot_in_command'}])]);const snapshot=saved.rows[0].result.record.assignments[0].snapshot;if(snapshot.personnelId!==person.id||snapshot.personnelVersion!==2||snapshot.credential.identifier!=='RePL-001')throw new Error('Mission Personnel snapshot failed');
 await db.query(`update public.personnel set full_name='Changed Later' where organisation_id='${ids.org}' and id='${person.id}'`);const history=await db.query(`select * from public.ftf_read_mission_personnel('${ids.org}','${missionId}',true)`);if(history.rows[0].ftf_read_mission_personnel.assignments[0].snapshot.name!=='Alex Pilot')throw new Error('historical Personnel snapshot mutated');
 const conflict=await db.query(`select public.ftf_save_mission_personnel('${ids.org}','${ids.actor}','${missionId}',0,$1::jsonb) result`,[JSON.stringify([{personnelId:person.id,assignmentRole:'pilot_in_command'}])]);if(!conflict.rows[0].result.conflict)throw new Error('stale Mission Personnel save accepted');
 const evidence=await db.query(`select public.ftf_write_personnel_evidence('${ids.org}','${ids.actor}','${person.id}',$1::jsonb) result`,[JSON.stringify({credentialId:credential.rows[0].result.record.id,internalFileId:'30000000-0000-4000-8000-000000009001',fileVersion:1,checksum:'a'.repeat(64),evidenceType:'licence',accessClassification:'restricted',provenance:{source:'upload'},retentionState:'active'})]);if(!evidence.rows[0].result.record.id)throw new Error('internal evidence reference failed');
 const counts=await db.query(`select(select count(*)::int from public.audit_events where organisation_id='${ids.org}' and entity_type in('personnel','personnel_credential','personnel_evidence','mission'))audits,(select count(*)::int from public.transactional_outbox where organisation_id='${ids.org}' and aggregate_type in('personnel','mission'))outbox`);if(counts.rows[0].audits<5||counts.rows[0].outbox<5)throw new Error('Personnel audit/outbox evidence missing');
 await db.exec('set role authenticated');let direct=false;try{await db.exec(`insert into public.personnel(organisation_id,full_name,created_by_internal_user_id,updated_by_internal_user_id)values('${ids.org}','Direct','${ids.actor}','${ids.actor}')`);}catch{direct=true;}if(!direct)throw new Error('browser direct Personnel write accepted');await db.exec('reset role');
}finally{await db.close();}
