import { readFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { PGlite } from '@electric-sql/pglite';
import { createRequire } from 'node:module';

const scriptDirectory=dirname(fileURLToPath(import.meta.url));
const directory=resolve(scriptDirectory,'../supabase/migrations');
const require=createRequire(import.meta.url);
// PGlite 0.5's CommonJS wildcard export appends a duplicate extension, so load
// the bundled extension by its repository-controlled absolute path.
const {pgcrypto}=require(resolve(scriptDirectory,'../node_modules/@electric-sql/pglite/dist/contrib/pgcrypto.cjs'));
const id={org:'51000000-0000-4000-8000-000000000001',otherOrg:'52000000-0000-4000-8000-000000000001',actor:'51000000-0000-4000-8000-000000000101',otherActor:'52000000-0000-4000-8000-000000000101',person:'51000000-0000-4000-8000-000000000201',doc:'51000000-0000-4000-8000-000000000301'};
const db=new PGlite({extensions:{pgcrypto}});
try{
 await db.exec(`create extension if not exists pgcrypto;create schema auth;create table auth.users(id uuid primary key);create function auth.uid()returns uuid language sql stable as $$select null::uuid$$;create role anon;create role authenticated;create role service_role;`);
 for(const name of(await readdir(directory)).filter(name=>name.endsWith('.sql')&&!['20260804162000_production_beta_platform_identity_reconciliation.sql','20260805131000_personnel_compliance_evidence_storage.sql','20260805144000_checklist_evidence_storage.sql'].includes(name)).sort())await db.exec(await readFile(resolve(directory,name),'utf8'));
 await db.exec(`insert into auth.users(id)values('51000000-0000-4000-8000-000000000011'),('52000000-0000-4000-8000-000000000011');
 insert into public.organisations(id,organisation_id,name)values('${id.org}','${id.org}','Fly The Farm'),('${id.otherOrg}','${id.otherOrg}','Other');
 insert into public.internal_users(id,organisation_id,auth_user_id,display_name)values('${id.actor}','${id.org}','51000000-0000-4000-8000-000000000011','Admin'),('${id.otherActor}','${id.otherOrg}','52000000-0000-4000-8000-000000000011','Other');
 insert into public.roles(id,organisation_id,code,name)values('51000000-0000-4000-8000-000000000111','${id.org}','admin','Admin'),('52000000-0000-4000-8000-000000000111','${id.otherOrg}','admin','Admin');
 insert into public.memberships(id,organisation_id,internal_user_id,role_id)values('51000000-0000-4000-8000-000000000121','${id.org}','${id.actor}','51000000-0000-4000-8000-000000000111'),('52000000-0000-4000-8000-000000000121','${id.otherOrg}','${id.otherActor}','52000000-0000-4000-8000-000000000111');
 insert into public.personnel(id,organisation_id,full_name,created_by_internal_user_id,updated_by_internal_user_id)values('${id.person}','${id.org}','Chief Remote Pilot','${id.actor}','${id.actor}');
 insert into public.controlled_documents(id,organisation_id,document_type,title,created_by_internal_user_id,updated_by_internal_user_id)values('${id.doc}','${id.org}','OPERATIONS_MANUAL','RPAS Operations Manual','${id.actor}','${id.actor}');`);
 const created=await db.query(`select public.ftf_write_compliance_instrument('${id.org}','${id.actor}','CREATE',null,0,$1::jsonb) result`,[JSON.stringify({instrumentType:'REOC',instrumentNumber:'CASA.REOC.001',issuer:'CASA',issueDate:'2026-01-01',expiryDate:'2027-01-01',status:'CURRENT',conditions:[],scope:{country:'AU'}})]);
 const instrument=created.rows[0].result.record;if(!instrument?.id||instrument.row_version!==1)throw new Error('ReOC create failed');
 const stale=await db.query(`select public.ftf_write_compliance_instrument('${id.org}','${id.actor}','UPDATE','${instrument.id}',99,$1::jsonb) result`,[JSON.stringify({instrumentNumber:'CASA.REOC.001',status:'CURRENT'})]);if(!stale.rows[0].result.conflict)throw new Error('stale instrument update accepted');
 const replResult=await db.query(`select public.ftf_write_personnel_casa_credential('${id.org}','${id.actor}','${id.person}',$1::jsonb) result`,[JSON.stringify({credentialType:'RePL',identifier:'REPL-001',issueDate:'2026-01-01',expiryDate:'2026-12-01',categories:['MULTIROTOR'],ratings:['UP_TO_150KG'],aircraftTypes:['AGRAS_T100'],maximumWeightKg:150,evidence:{internalFileId:'51000000-0000-4000-8000-000000009101',fileVersion:1,checksum:'b'.repeat(64),provenance:{source:'upload'}}})]);const repl=replResult.rows[0].result;if(repl.record.lifecycle_type!=='NON_EXPIRING'||repl.record.expiry_date!==null||repl.record.expiryDisplay!=='Non-expiring')throw new Error('NON_EXPIRING RePL semantics failed');
 await db.query(`select public.ftf_verify_personnel_credential('${id.org}','${id.actor}','${repl.record.id}',1,'VERIFIED','Evidence checked')`);
 const arocMissing=await db.query(`select public.ftf_evaluate_personnel_mission_eligibility('${id.org}','${id.person}','2026-09-01','MULTIROTOR','UP_TO_150KG','AGRAS_T100',100,true) result`);if(arocMissing.rows[0].result.blockers[0]?.code!=='AROC_REQUIRED')throw new Error('AROC_REQUIRED blocker missing');
 const arocResult=await db.query(`select public.ftf_write_personnel_casa_credential('${id.org}','${id.actor}','${id.person}',$1::jsonb) result`,[JSON.stringify({credentialType:'AROC',identifier:'AROC-001',issueDate:'2026-01-01',evidence:{internalFileId:'51000000-0000-4000-8000-000000009102',fileVersion:1,checksum:'c'.repeat(64),provenance:{source:'upload'}}})]);const aroc=arocResult.rows[0].result;if(aroc.record.expiry_date!==null||aroc.record.expiryDisplay!=='No expiry recorded')throw new Error('No expiry recorded AROC semantics failed');
 await db.query(`select public.ftf_verify_personnel_credential('${id.org}','${id.actor}','${aroc.record.id}',1,'VERIFIED','Evidence checked')`);const eligible=await db.query(`select public.ftf_evaluate_personnel_mission_eligibility('${id.org}','${id.person}','2026-09-01','MULTIROTOR','UP_TO_150KG','AGRAS_T100',100,true) result`);if(!eligible.rows[0].result.eligible)throw new Error('verified credential eligibility failed');
 const published=await db.query(`select public.ftf_publish_controlled_document_version('${id.org}','${id.actor}','${id.doc}',1,$1::jsonb) result`,[JSON.stringify({effectiveDate:'2026-08-05',reviewDueDate:'2027-08-05',internalFileId:'51000000-0000-4000-8000-000000009001',fileVersion:1,originalFilename:'operations-manual.pdf',checksum:'a'.repeat(64),provenance:{source:'upload'},approvedByPersonnelId:id.person,approverSnapshot:{name:'Chief Remote Pilot'}})]);if(published.rows[0].result.record.version_number!==1)throw new Error('manual publication failed');
 const overview=await db.query(`select public.ftf_read_casa_compliance_overview('${id.org}','2026-08-05T00:00:00Z') result`);if(overview.rows[0].result.reoc.instrument_number!=='CASA.REOC.001'||overview.rows[0].result.operationsManual.version_number!==1)throw new Error('overview did not use authoritative records');
 const projection=overview.rows[0].result;if(projection.healthScore?.modelVersion!=='AU-CASA-HEALTH-1'||projection.healthScore.status!=='CRITICAL')throw new Error('versioned health score or critical override missing');
 const blocker=projection.healthScore.criticalBlockers.find(item=>item.criticalRuleCode==='REOC_EVIDENCE_MISSING');if(!blocker?.reason||blocker.organisationId!==id.org||!blocker.evaluationTimestamp)throw new Error('critical blocker provenance missing');
 const credentialEvents=projection.calendar.events.filter(event=>event.sourceEntityType==='personnel_credential');if(credentialEvents.some(event=>event.sourceEntityId===repl.record.id||event.sourceEntityId===aroc.record.id))throw new Error('RePL or expiry-free AROC incorrectly created calendar expiry');
 const due30=projection.healthScore.categories.flatMap(category=>category.sources).filter(item=>item.state==='DUE_30');const due90=projection.healthScore.categories.flatMap(category=>category.sources).filter(item=>item.state==='DUE_90');if(due30.some(item=>due90.some(other=>other.sourceEntityId===item.sourceEntityId)))throw new Error('state precedence double-counted an item');
 const other=await db.query(`select public.ftf_read_casa_compliance_overview('${id.otherOrg}',now()) result`);if(other.rows[0].result.reoc!==null)throw new Error('cross-tenant overview leaked');
 let immutable=false;try{await db.exec(`update public.controlled_document_versions set original_filename='changed.pdf'where organisation_id='${id.org}'`);}catch{immutable=true;}if(!immutable)throw new Error('published manual version mutated');
 const evidence=await db.query(`select(select count(*)::int from public.audit_events where organisation_id='${id.org}'and event_type like'compliance.%')audits,(select count(*)::int from public.transactional_outbox where organisation_id='${id.org}'and topic like'compliance.%')outbox`);if(evidence.rows[0].audits<2||evidence.rows[0].outbox<2)throw new Error('compliance audit/outbox missing');
 await db.exec('set role authenticated');let direct=false;try{await db.exec(`insert into public.organisation_compliance_instruments(organisation_id,instrument_type,issuer,status,created_by_internal_user_id,updated_by_internal_user_id)values('${id.org}','REOC','CASA','CURRENT','${id.actor}','${id.actor}')`);}catch{direct=true;}if(!direct)throw new Error('direct browser compliance write accepted');await db.exec('reset role');
}finally{await db.close();}
