-- NEW-CMP-022 / NEW-CMP-023 / SC-011: derived CASA compliance health and calendar.
create or replace function public.ftf_read_casa_compliance_overview(p_organisation_id uuid,p_evaluated_at timestamptz default now())returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
with
clock as(select p_evaluated_at evaluation_timestamp,(p_evaluated_at at time zone 'Australia/Brisbane')::date evaluation_date),
reoc as(select*from public.organisation_compliance_instruments where organisation_id=p_organisation_id and instrument_type='REOC'and archived_at is null order by created_at desc limit 1),
manual as(select v.*,d.row_version document_row_version,d.title from public.controlled_document_versions v join public.controlled_documents d on d.organisation_id=v.organisation_id and d.id=v.document_id where v.organisation_id=p_organisation_id and d.document_type='OPERATIONS_MANUAL'and v.status='PUBLISHED'order by v.version_number desc limit 1),
active_people as(select*from public.personnel where organisation_id=p_organisation_id and is_active and archived_at is null),
active_aircraft as(select*from public.aircraft where organisation_id=p_organisation_id and archived_at is null),
raw_items as(
 select 'REOC'::text category,'ReOC and organisation certificates'::text category_label,20::numeric weight,
  coalesce(r.status='EXPIRED',false) operationally_blocking,coalesce(r.expiry_date<c.evaluation_date,false) expired_or_overdue,r.id is null or not exists(select 1 from public.compliance_instrument_evidence e where e.organisation_id=p_organisation_id and e.instrument_id=r.id) missing,coalesce(r.status='UNDER_REVIEW',false) under_review,(r.expiry_date-c.evaluation_date)::integer days_remaining,
  case when r.id is null then 'Required ReOC record is missing.' when not exists(select 1 from public.compliance_instrument_evidence e where e.organisation_id=p_organisation_id and e.instrument_id=r.id)then'ReOC evidence is missing.'when r.expiry_date<c.evaluation_date then'ReOC has expired.'else'ReOC is current.'end reason,
  'organisation_compliance_instrument'::text source_entity_type,r.id source_entity_id,r.row_version source_row_version,null::uuid operating_location_id,'ReOC'::text affected_area,'/compliance'::text route,
  case when r.id is null then'REOC_MISSING'when not exists(select 1 from public.compliance_instrument_evidence e where e.organisation_id=p_organisation_id and e.instrument_id=r.id)then'REOC_EVIDENCE_MISSING'when r.expiry_date<c.evaluation_date then'REOC_EXPIRED'end critical_rule_code,r.expiry_date due_date,r.instrument_number title
 from clock c left join reoc r on true
 union all
 select 'DOCUMENTS','Operations Manual and controlled documents',12,false,false,m.id is null,false,(m.review_due_date-c.evaluation_date)::integer,
  case when m.id is null then'Published Operations Manual is missing.'else'Operations Manual review date.'end,'controlled_document_version',m.id,m.version_number,null,'Controlled documents','/compliance',null,m.review_due_date,coalesce(m.title,'Operations Manual')from clock c left join manual m on true
 union all
 select 'PERSONNEL','Personnel licences and qualifications',15,
  pc.status in('suspended','revoked')or(pc.credential_type<>'RePL'and pc.status='expired'),coalesce(pc.credential_type<>'RePL'and pc.expiry_date<c.evaluation_date,false),false,pc.verification_state in('unverified','requires_review'),case when pc.credential_type='RePL'then null else(pc.expiry_date-c.evaluation_date)::integer end,
  case when pc.status in('suspended','revoked')then pc.credential_type||' is not valid.'when pc.expiry_date<c.evaluation_date then pc.credential_type||' has expired.'when pc.verification_state<>'verified'then pc.credential_type||' requires verification.'else pc.credential_type||' is current.'end,
  'personnel_credential',pc.id,pc.row_version,null,'Personnel credentials','/personnel',case when pc.status in('suspended','revoked')or(pc.credential_type<>'RePL'and pc.status='expired')then'REQUIRED_PERSONNEL_CREDENTIAL_INVALID'end,case when pc.credential_type='RePL'then null else pc.expiry_date end,pc.credential_type
 from public.personnel_credentials pc join active_people p on p.id=pc.personnel_id cross join clock c where pc.organisation_id=p_organisation_id and pc.archived_at is null and pc.status<>'superseded'and(pc.credential_type<>'AROC'or pc.expiry_date is not null)
 union all
 select 'AIRCRAFT','Aircraft registration and technical compliance',15,
  not a.mission_ready or a.serviceability_state<>'serviceable',coalesce(least(a.next_inspection_due,a.next_major_service_due,a.insurance_expiry_date)<c.evaluation_date,false),jsonb_array_length(a.documentation->'certificates')=0,false,(least(a.next_inspection_due,a.next_major_service_due,a.insurance_expiry_date)-c.evaluation_date)::integer,
  case when not a.mission_ready or a.serviceability_state<>'serviceable'then a.registration||' is not mission ready.'when least(a.next_inspection_due,a.next_major_service_due,a.insurance_expiry_date)<c.evaluation_date then a.registration||' has overdue technical compliance.'else a.registration||' technical compliance is current.'end,
  'aircraft',a.id,a.row_version,a.operating_location_id,'Aircraft compliance','/aircraft',case when not a.mission_ready or a.serviceability_state<>'serviceable'then'AIRCRAFT_NOT_SERVICEABLE'when least(a.next_inspection_due,a.next_major_service_due,a.insurance_expiry_date)<c.evaluation_date then'AIRCRAFT_TECHNICAL_OVERDUE'end,least(a.next_inspection_due,a.next_major_service_due,a.insurance_expiry_date),a.registration
 from active_aircraft a cross join clock c
 union all
 select 'CHECKLISTS','Checklist governance',8,false,coalesce(v.review_due_date<c.evaluation_date,false),false,false,(v.review_due_date-c.evaluation_date)::integer,
  'Checklist review for '||t.name,'checklist_template_version',v.id,v.version_number,null,'Checklist governance','/compliance/checklists',null,v.review_due_date,t.name
 from public.checklist_template_versions v join public.checklist_templates t on t.organisation_id=v.organisation_id and t.id=v.template_id cross join clock c where v.organisation_id=p_organisation_id and v.status='PUBLISHED'and t.archived_at is null
 union all
 select 'RENEWALS','Renewals and corrective actions',7,coalesce(a.status in('OPEN','IN_PROGRESS')and a.due_date<c.evaluation_date,false),coalesce(a.due_date<c.evaluation_date,false),false,false,(a.due_date-c.evaluation_date)::integer,
  'Corrective action: '||a.title,'checklist_corrective_action',a.id,a.row_version,null,'Corrective actions','/compliance/checklists',case when a.status in('OPEN','IN_PROGRESS')and a.due_date<c.evaluation_date then'CRITICAL_CORRECTIVE_ACTION_OVERDUE'end,a.due_date,a.title
 from public.checklist_corrective_actions a cross join clock c where a.organisation_id=p_organisation_id and a.status not in('RESOLVED','CANCELLED')
 union all
 select 'RENEWALS','Renewals and corrective actions',7,false,coalesce(a.due_date<c.evaluation_date and a.status<>'COMPLETED',false),false,a.status in('ACKNOWLEDGED','IN_PROGRESS'),(a.due_date-c.evaluation_date)::integer,
  'Renewal action for '||a.source_entity_type,'compliance_renewal_action',a.id,a.row_version,null,'Renewals','/compliance',null,a.due_date,a.source_entity_type
 from public.compliance_renewal_actions a cross join clock c where a.organisation_id=p_organisation_id and a.status<>'CANCELLED'
),
resolved_items as(select r.*,
 case when operationally_blocking then 'OPERATIONALLY_BLOCKING' when expired_or_overdue then 'EXPIRED_OVERDUE' when missing then 'MISSING' when under_review then 'UNDER_REVIEW' when days_remaining <= 30 then 'DUE_30' when days_remaining <= 90 then 'DUE_90' else 'CURRENT' end state,
 case when operationally_blocking or expired_or_overdue or missing then 0::numeric when under_review then .5 when days_remaining<=30 then .6 when days_remaining<=90 then .8 else 1 end factor
 from raw_items r),
category_scores as(select category,category_label,max(weight)weight,round(max(weight)*avg(factor),2)earned_points,count(*)assessed,
 count(*)filter(where state='CURRENT')current_count,count(*)filter(where state='DUE_30')due_30_count,count(*)filter(where state='DUE_90')due_90_count,count(*)filter(where state='MISSING')missing_count,count(*)filter(where state='EXPIRED_OVERDUE')expired_count,count(*)filter(where state='OPERATIONALLY_BLOCKING')blocking_count,
 jsonb_agg(jsonb_build_object('state',state,'factor',factor,'reason',reason,'sourceEntityType',source_entity_type,'sourceEntityId',source_entity_id,'sourceRowVersion',source_row_version,'route',route)order by factor,reason) sources
 from resolved_items group by category,category_label),
score as(select round(100*sum(earned_points)/nullif(sum(weight),0),0)::integer percentage from category_scores),
critical_blockers as(select jsonb_agg(jsonb_build_object('criticalRuleCode',critical_rule_code,'criticalRuleVersion',1,'reason',reason,'sourceEntityType',source_entity_type,'sourceEntityId',source_entity_id,'sourceRowVersion',source_row_version,'organisationId',p_organisation_id,'operatingLocationId',operating_location_id,'affectedArea',affected_area,'route',route,'evaluationTimestamp',(select evaluation_timestamp from clock))order by critical_rule_code) value from resolved_items where critical_rule_code is not null and(state='OPERATIONALLY_BLOCKING'or state='EXPIRED_OVERDUE'or state='MISSING')),
calendar_events as(select jsonb_agg(jsonb_build_object('eventKey',source_entity_type||':'||coalesce(source_entity_id::text,'missing')||':'||coalesce(due_date::text,'missing'),'title',coalesce(title,affected_area),'recordType',upper(source_entity_type),'dueDate',due_date,'daysRemaining',days_remaining,'state',state,'responsiblePersonnel',null,'requiredAction',reason,'sourceEntityType',source_entity_type,'sourceEntityId',source_entity_id,'sourceRowVersion',source_row_version,'operatingLocationId',operating_location_id,'operationalBlocking',operationally_blocking,'route',route)order by due_date nulls first,title)filter(where due_date is not null) value from resolved_items),
base as(select jsonb_build_object('evaluatedAt',p_evaluated_at,'reoc',(select to_jsonb(x)||jsonb_build_object('daysRemaining',x.expiry_date-(select evaluation_date from clock))from reoc x),'operationsManual',(select to_jsonb(x)from manual x),'personnel',jsonb_build_object('missingCertificates',(select count(*)from active_people p where exists(select 1 from public.personnel_operational_roles r where r.organisation_id=p_organisation_id and r.personnel_id=p.id and r.role_code in('pilot','pilot_in_command'))and not exists(select 1 from public.personnel_credentials c where c.organisation_id=p_organisation_id and c.personnel_id=p.id and c.credential_type='RePL'and c.status='current')),'unverifiedCertificates',(select count(*)from public.personnel_credentials c join active_people p on p.id=c.personnel_id where c.organisation_id=p_organisation_id and c.verification_state<>'verified')),'aircraft',jsonb_build_object('missingEvidence',(select count(*)from active_aircraft where jsonb_array_length(documentation->'certificates')=0)),'training',jsonb_build_object('outstanding',(select count(*)from public.compliance_training_records where organisation_id=p_organisation_id and outcome not in('COMPETENT','COMPLETED','PASSED'))),'checklists',jsonb_build_object('missing',(select count(*)from public.checklist_templates t where t.organisation_id=p_organisation_id and t.archived_at is null and not exists(select 1 from public.checklist_template_versions v where v.organisation_id=t.organisation_id and v.template_id=t.id and v.status='PUBLISHED'))),'warnings',jsonb_build_object('renewalsOverdue',(select count(*)from public.compliance_renewal_actions where organisation_id=p_organisation_id and status in('OPEN','IN_PROGRESS')and due_date<(select evaluation_date from clock)),'legalHolds',(select count(*)from public.compliance_legal_holds where organisation_id=p_organisation_id and released_at is null),'missingEvidence',(select count(*)from public.organisation_compliance_instruments i where i.organisation_id=p_organisation_id and i.archived_at is null and not exists(select 1 from public.compliance_instrument_evidence e where e.organisation_id=i.organisation_id and e.instrument_id=i.id)))) value)
select base.value||jsonb_build_object('healthScore',jsonb_build_object('modelVersion','AU-CASA-HEALTH-1','countryPackVersion','AU_PART_101:1','evaluationTimestamp',p_evaluated_at,'percentage',coalesce(score.percentage,0),'status',case when coalesce(jsonb_array_length(critical_blockers.value),0)>0 then'CRITICAL'when score.percentage>=90 then'STRONG'when score.percentage>=75 then'ATTENTION_REQUIRED'when score.percentage>=50 then'AT_RISK'else'CRITICAL'end,'criticalBlockers',coalesce(critical_blockers.value,'[]'::jsonb),'categories',(select coalesce(jsonb_agg(jsonb_build_object('code',category,'label',category_label,'weight',weight,'earnedPoints',earned_points,'counts',jsonb_build_object('assessed',assessed,'current',current_count,'due30',due_30_count,'due90',due_90_count,'missing',missing_count,'expired',expired_count,'blocking',blocking_count),'sources',sources)order by category),'[]'::jsonb)from category_scores)),'calendar',jsonb_build_object('events',coalesce(calendar_events.value,'[]'::jsonb),'facets',jsonb_build_object('recordTypes',(select coalesce(jsonb_agg(distinct upper(source_entity_type)),'[]'::jsonb)from resolved_items))))from base cross join score cross join critical_blockers cross join calendar_events
$$;

-- Explicit evidence-driven expiry semantics: standard RePL is non-expiring; AROC is timed only when evidence supplies expiry_date.
comment on function public.ftf_read_casa_compliance_overview(uuid,timestamptz)is 'AU-CASA-HEALTH-1 derived projection. credential_type=''RePL'' never creates expiry without authoritative expiry evidence; credential_type=''AROC'' creates an event only when expiry_date is present.';
revoke all on function public.ftf_read_casa_compliance_overview(uuid,timestamptz)from public,anon,authenticated;
grant execute on function public.ftf_read_casa_compliance_overview(uuid,timestamptz)to service_role;
