-- NEW-CHK-001 / IMP-CMP-008: controlled, versioned organisation checklists.
create table public.checklist_templates(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),stable_code text not null,name text not null,description text,category text not null,owner_personnel_id uuid references public.personnel(id),status text not null default'DRAFT'check(status in('DRAFT','PUBLISHED','SUPERSEDED','ARCHIVED')),operating_location_ids uuid[]not null default'{}',applicable_operation_types text[]not null default'{}',applicable_aircraft_types text[]not null default'{}',applicable_equipment_ids uuid[]not null default'{}',applicable_lifecycle_stages text[]not null default'{}',row_version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,unique(organisation_id,stable_code)
);
create table public.checklist_template_versions(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),template_id uuid not null references public.checklist_templates(id),version_number integer not null,revision_number integer not null default 1,status text not null check(status in('DRAFT','PUBLISHED','SUPERSEDED','ARCHIVED')),effective_at timestamptz,review_due_date date,owner_personnel_id uuid references public.personnel(id),approver_personnel_id uuid references public.personnel(id),change_summary text,sections jsonb not null default'[]',visibility_rules jsonb not null default'[]',signoff_policy jsonb not null default'{}',supersedes_version_id uuid references public.checklist_template_versions(id),published_at timestamptz,published_by_internal_user_id uuid references public.internal_users(id),created_at timestamptz not null default now(),created_by_internal_user_id uuid not null references public.internal_users(id),unique(organisation_id,template_id,version_number),check(jsonb_typeof(sections)='array'),check(jsonb_typeof(visibility_rules)='array')
);
comment on column public.checklist_template_versions.sections is 'Configuration supports YES_NO, PASS_FAIL, COMPLETE_INCOMPLETE, NUMERIC, TEXT, DATETIME, PERSONNEL, AIRCRAFT, EQUIPMENT, PHOTO, FILE, SIGNATURE, ACKNOWLEDGEMENT and CUSTOM_OPTIONS item types; mandatory, help text, options, jurisdiction and procedure references; required_comment_on_failure, required_photo_on_failure, required_file_on_failure, create_corrective_action_on_failure, requires_signoff_on_failure, repeat_required_on_failure and triggered risk controls.';
create table public.checklist_executions(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),operating_location_id uuid not null references public.operating_locations(id),mission_id uuid references public.missions(id),template_id uuid not null references public.checklist_templates(id),template_version_id uuid not null references public.checklist_template_versions(id),lifecycle_stage text not null,completing_personnel_id uuid not null references public.personnel(id),completing_personnel_snapshot jsonb not null,status text not null default'DRAFT'check(status in('DRAFT','SUBMITTED','SUPERSEDED')),started_at timestamptz not null default now(),completed_at timestamptz,responses jsonb not null default'{}',failure_summary jsonb not null default'[]',signoff_snapshot jsonb,correction_reason text,supersedes_execution_id uuid references public.checklist_executions(id),row_version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by_internal_user_id uuid not null references public.internal_users(id),unique(organisation_id,id)
);
create table public.checklist_execution_evidence(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),execution_id uuid not null references public.checklist_executions(id),item_id text not null,evidence_kind text not null check(evidence_kind in('PHOTO','FILE','SIGNATURE')),internal_file_id uuid not null,file_version integer not null,original_filename text not null,content_type text not null,byte_size bigint not null,sha256_checksum text not null,provenance jsonb not null,created_at timestamptz not null default now(),created_by_internal_user_id uuid not null references public.internal_users(id),unique(organisation_id,internal_file_id,file_version)
);
create table public.checklist_corrective_actions(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),execution_id uuid not null references public.checklist_executions(id),item_id text not null,title text not null,description text,responsible_personnel_id uuid references public.personnel(id),due_date date,status text not null default'OPEN'check(status in('OPEN','IN_PROGRESS','RESOLVED','CANCELLED')),resolution_notes text,resolved_at timestamptz,resolved_by_personnel_id uuid references public.personnel(id),reviewed_at timestamptz,reviewed_by_personnel_id uuid references public.personnel(id),row_version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by_internal_user_id uuid not null references public.internal_users(id),updated_by_internal_user_id uuid not null references public.internal_users(id)
);

do $$declare t text;begin foreach t in array array['checklist_templates','checklist_template_versions','checklist_executions','checklist_execution_evidence','checklist_corrective_actions']loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('create policy %I on public.%I for all to service_role using(true) with check(true)',t||'_trusted',t);end loop;end$$;
create trigger checklist_versions_immutable before update or delete on public.checklist_template_versions for each row when(old.status in('PUBLISHED','SUPERSEDED','ARCHIVED'))execute function public.reject_append_only_mutation();
create trigger checklist_executions_immutable before update or delete on public.checklist_executions for each row when(old.status in('SUBMITTED','SUPERSEDED'))execute function public.reject_append_only_mutation();
create trigger checklist_execution_evidence_immutable before update or delete on public.checklist_execution_evidence for each row execute function public.reject_append_only_mutation();

create or replace function public.ftf_write_checklist_template(p_organisation_id uuid,p_actor_internal_user_id uuid,p_operation text,p_template_id uuid,p_expected_version integer,p_payload jsonb)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v public.checklist_templates%rowtype;begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'compliance.manage')then return jsonb_build_object('forbidden',true);end if;
 if p_operation='CREATE'then insert into public.checklist_templates(organisation_id,stable_code,name,description,category,owner_personnel_id,operating_location_ids,applicable_operation_types,applicable_aircraft_types,applicable_equipment_ids,applicable_lifecycle_stages)values(p_organisation_id,p_payload->>'stableCode',p_payload->>'name',nullif(p_payload->>'description',''),p_payload->>'category',nullif(p_payload->>'ownerPersonnelId','')::uuid,coalesce((select array_agg(x::uuid)from jsonb_array_elements_text(coalesce(p_payload->'operatingLocationIds','[]'))x),'{}'),coalesce((select array_agg(x)from jsonb_array_elements_text(coalesce(p_payload->'applicableOperationTypes','[]'))x),'{}'),coalesce((select array_agg(x)from jsonb_array_elements_text(coalesce(p_payload->'applicableAircraftTypes','[]'))x),'{}'),coalesce((select array_agg(x::uuid)from jsonb_array_elements_text(coalesce(p_payload->'applicableEquipmentIds','[]'))x),'{}'),coalesce((select array_agg(x)from jsonb_array_elements_text(coalesce(p_payload->'applicableLifecycleStages','[]'))x),'{}'))returning*into v;
 elsif p_operation='UPDATE'then update public.checklist_templates set name=p_payload->>'name',description=nullif(p_payload->>'description',''),category=p_payload->>'category',row_version=row_version+1,updated_at=now()where organisation_id=p_organisation_id and id=p_template_id and row_version=p_expected_version and status='DRAFT'returning*into v;if not found then return jsonb_build_object('conflict',true);end if;else return jsonb_build_object('unsupported_operation',true);end if;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'checklist.template.'||lower(p_operation),'checklist_template',v.id,jsonb_build_object('version',v.row_version));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'checklist.template.'||lower(p_operation),'checklist_template',v.id,jsonb_build_object('version',v.row_version));return jsonb_build_object('record',to_jsonb(v));end$$;

create or replace function public.ftf_publish_checklist_template(p_organisation_id uuid,p_actor_internal_user_id uuid,p_template_id uuid,p_expected_version integer,p_payload jsonb)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare t public.checklist_templates%rowtype;v public.checklist_template_versions%rowtype;n integer;previous uuid;begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'compliance.publish')then return jsonb_build_object('forbidden',true);end if;select*into t from public.checklist_templates where organisation_id=p_organisation_id and id=p_template_id and row_version=p_expected_version for update;if not found then return jsonb_build_object('conflict',true);end if;select id into previous from public.checklist_template_versions where organisation_id=p_organisation_id and template_id=p_template_id and status='PUBLISHED'order by version_number desc limit 1;select coalesce(max(version_number),0)+1 into n from public.checklist_template_versions where organisation_id=p_organisation_id and template_id=p_template_id;
 if previous is not null then update public.checklist_template_versions set status='SUPERSEDED'where id=previous;end if;insert into public.checklist_template_versions(organisation_id,template_id,version_number,status,effective_at,review_due_date,owner_personnel_id,approver_personnel_id,change_summary,sections,visibility_rules,signoff_policy,supersedes_version_id,published_at,published_by_internal_user_id,created_by_internal_user_id)values(p_organisation_id,p_template_id,n,'PUBLISHED',coalesce(nullif(p_payload->>'effectiveAt','')::timestamptz,now()),nullif(p_payload->>'reviewDueDate','')::date,t.owner_personnel_id,nullif(p_payload->>'approverPersonnelId','')::uuid,p_payload->>'changeSummary',p_payload->'sections',coalesce(p_payload->'visibilityRules','[]'),coalesce(p_payload->'signoffPolicy','{}'),previous,now(),p_actor_internal_user_id,p_actor_internal_user_id)returning*into v;update public.checklist_templates set status='PUBLISHED',row_version=row_version+1,updated_at=now()where id=t.id;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'checklist.template.published','checklist_template_version',v.id,jsonb_build_object('version',n));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'checklist.template.published','checklist_template',p_template_id,jsonb_build_object('versionId',v.id,'version',n));return jsonb_build_object('record',to_jsonb(v));end$$;

create or replace function public.ftf_write_checklist_execution(p_organisation_id uuid,p_actor_internal_user_id uuid,p_operation text,p_execution_id uuid,p_expected_version integer,p_payload jsonb)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v public.checklist_executions%rowtype;tv public.checklist_template_versions%rowtype;p public.personnel%rowtype;begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'compliance.manage')then return jsonb_build_object('forbidden',true);end if;
 if p_operation='CREATE'then select*into tv from public.checklist_template_versions where organisation_id=p_organisation_id and id=(p_payload->>'templateVersionId')::uuid and status='PUBLISHED';if not found then return jsonb_build_object('superseded_checklist_selected',true);end if;select*into p from public.personnel where organisation_id=p_organisation_id and id=(p_payload->>'completingPersonnelId')::uuid and is_active;if not found then return jsonb_build_object('ineligible_completing_personnel',true);end if;insert into public.checklist_executions(organisation_id,operating_location_id,mission_id,template_id,template_version_id,lifecycle_stage,completing_personnel_id,completing_personnel_snapshot,created_by_internal_user_id)values(p_organisation_id,(p_payload->>'operatingLocationId')::uuid,nullif(p_payload->>'missionId','')::uuid,tv.template_id,tv.id,p_payload->>'lifecycleStage',p.id,jsonb_build_object('id',p.id,'fullName',p.full_name,'roles',coalesce((select jsonb_agg(r.role_code)from public.personnel_operational_roles r where r.organisation_id=p_organisation_id and r.personnel_id=p.id),'[]'::jsonb)),p_actor_internal_user_id)returning*into v;
 elsif p_operation='SAVE_DRAFT'then update public.checklist_executions set responses=p_payload->'responses',failure_summary=coalesce(p_payload->'failureSummary','[]'),row_version=row_version+1,updated_at=now()where organisation_id=p_organisation_id and id=p_execution_id and row_version=p_expected_version and status='DRAFT'returning*into v;if not found then return jsonb_build_object('conflict',true);end if;
 elsif p_operation='SUBMIT'then update public.checklist_executions set responses=p_payload->'responses',failure_summary=coalesce(p_payload->'failureSummary','[]'),signoff_snapshot=p_payload->'signoffSnapshot',status='SUBMITTED',completed_at=now(),row_version=row_version+1,updated_at=now()where organisation_id=p_organisation_id and id=p_execution_id and row_version=p_expected_version and status='DRAFT'returning*into v;if not found then return jsonb_build_object('conflict',true);end if;
 else return jsonb_build_object('unsupported_operation',true);end if;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,case when p_operation='SUBMIT'then'checklist.execution.submitted'else'checklist.execution.'||lower(p_operation)end,'checklist_execution',v.id,jsonb_build_object('version',v.row_version));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,case when p_operation='SUBMIT'then'checklist.execution.submitted'else'checklist.execution.'||lower(p_operation)end,'checklist_execution',v.id,jsonb_build_object('version',v.row_version));return jsonb_build_object('record',to_jsonb(v),'allClear',case when p_operation='SUBMIT'and v.failure_summary='[]'::jsonb then'ALL_CHECKS_PASSED'else null end);end$$;

create or replace function public.ftf_write_checklist_corrective_action(p_organisation_id uuid,p_actor_internal_user_id uuid,p_operation text,p_action_id uuid,p_expected_version integer,p_payload jsonb)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v public.checklist_corrective_actions%rowtype;begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'compliance.manage')then return jsonb_build_object('forbidden',true);end if;if p_operation='CREATE'then insert into public.checklist_corrective_actions(organisation_id,execution_id,item_id,title,description,responsible_personnel_id,due_date,created_by_internal_user_id,updated_by_internal_user_id)values(p_organisation_id,(p_payload->>'executionId')::uuid,p_payload->>'itemId',p_payload->>'title',nullif(p_payload->>'description',''),nullif(p_payload->>'responsiblePersonnelId','')::uuid,nullif(p_payload->>'dueDate','')::date,p_actor_internal_user_id,p_actor_internal_user_id)returning*into v;else update public.checklist_corrective_actions set status=p_payload->>'status',resolution_notes=nullif(p_payload->>'resolutionNotes',''),resolved_at=case when p_payload->>'status'='RESOLVED'then now()else resolved_at end,resolved_by_personnel_id=nullif(p_payload->>'resolvedByPersonnelId','')::uuid,row_version=row_version+1,updated_at=now(),updated_by_internal_user_id=p_actor_internal_user_id where organisation_id=p_organisation_id and id=p_action_id and row_version=p_expected_version returning*into v;if not found then return jsonb_build_object('conflict',true);end if;end if;insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'checklist.corrective_action.'||lower(p_operation),'checklist_corrective_action',v.id,jsonb_build_object('version',v.row_version));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'checklist.corrective_action.'||lower(p_operation),'checklist_corrective_action',v.id,jsonb_build_object('version',v.row_version));return jsonb_build_object('record',to_jsonb(v));end$$;

create or replace function public.ftf_evaluate_mission_checklist_readiness(p_organisation_id uuid,p_mission_id uuid,p_lifecycle_stage text)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$with required as(select v.id version_id,t.id template_id from public.checklist_templates t join public.checklist_template_versions v on v.organisation_id=t.organisation_id and v.template_id=t.id and v.status='PUBLISHED'where t.organisation_id=p_organisation_id and p_lifecycle_stage=any(t.applicable_lifecycle_stages)and t.archived_at is null),latest as(select distinct on(e.template_id)e.*from public.checklist_executions e where e.organisation_id=p_organisation_id and e.mission_id=p_mission_id and e.lifecycle_stage=p_lifecycle_stage order by e.template_id,e.created_at desc),blockers as(
 select jsonb_build_object('code','MANDATORY_CHECKLIST_INCOMPLETE','templateId',r.template_id) b from required r left join latest e on e.template_id=r.template_id where e.id is null or e.status<>'SUBMITTED'
 union all select jsonb_build_object('code','FAILED_ITEM_UNRESOLVED','executionId',e.id)from latest e where e.status='SUBMITTED'and e.failure_summary<>'[]'
 union all select jsonb_build_object('code','REQUIRED_COMMENT_MISSING','executionId',e.id)from latest e where e.failure_summary@>'[{"requiredCommentMissing":true}]'
 union all select jsonb_build_object('code','REQUIRED_EVIDENCE_MISSING','executionId',e.id)from latest e where e.failure_summary@>'[{"requiredEvidenceMissing":true}]'
 union all select jsonb_build_object('code','CORRECTIVE_ACTION_OPEN','executionId',e.id)from latest e where exists(select 1 from public.checklist_corrective_actions a where a.organisation_id=e.organisation_id and a.execution_id=e.id and a.status in('OPEN','IN_PROGRESS'))
 union all select jsonb_build_object('code','REQUIRED_SIGNOFF_MISSING','executionId',e.id)from latest e where e.status='SUBMITTED'and e.signoff_snapshot is null and e.failure_summary@>'[{"signoffRequired":true}]'
 union all select jsonb_build_object('code','INELIGIBLE_COMPLETING_PERSONNEL','executionId',e.id)from latest e left join public.personnel p on p.organisation_id=e.organisation_id and p.id=e.completing_personnel_id where p.id is null or not p.is_active
 union all select jsonb_build_object('code','SUPERSEDED_CHECKLIST_SELECTED','executionId',e.id)from latest e join public.checklist_template_versions v on v.id=e.template_version_id where e.status='DRAFT'and v.status<>'PUBLISHED')select jsonb_build_object('ready',count(*)=0,'blockers',coalesce(jsonb_agg(b),'[]'::jsonb))from blockers$$;

revoke all on function public.ftf_write_checklist_template(uuid,uuid,text,uuid,integer,jsonb),public.ftf_publish_checklist_template(uuid,uuid,uuid,integer,jsonb),public.ftf_write_checklist_execution(uuid,uuid,text,uuid,integer,jsonb),public.ftf_write_checklist_corrective_action(uuid,uuid,text,uuid,integer,jsonb),public.ftf_evaluate_mission_checklist_readiness(uuid,uuid,text)from public,anon,authenticated;
grant execute on function public.ftf_write_checklist_template(uuid,uuid,text,uuid,integer,jsonb),public.ftf_publish_checklist_template(uuid,uuid,uuid,integer,jsonb),public.ftf_write_checklist_execution(uuid,uuid,text,uuid,integer,jsonb),public.ftf_write_checklist_corrective_action(uuid,uuid,text,uuid,integer,jsonb),public.ftf_evaluate_mission_checklist_readiness(uuid,uuid,text)to service_role;
