-- Immutable Pre-flight Mission Authorisation and Mission Pack evidence.
create table public.mission_authorisation_revisions(
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null, operating_location_id uuid not null, mission_id uuid not null,
 version_number integer not null check(version_number>0), evidence_manifest jsonb not null check(jsonb_typeof(evidence_manifest)='object'),
 readiness_snapshot jsonb not null check(jsonb_typeof(readiness_snapshot)='object'), declaration text not null,
 authorised_personnel_id uuid not null, authorised_personnel_snapshot jsonb not null, authorised_at timestamptz not null default now(), authorised_by_internal_user_id uuid not null,
 unique(organisation_id,id),unique(organisation_id,mission_id,version_number),
 foreign key(organisation_id,mission_id)references public.missions(organisation_id,id),foreign key(organisation_id,operating_location_id)references public.operating_locations(organisation_id,id),
 foreign key(organisation_id,authorised_personnel_id)references public.personnel(organisation_id,id),foreign key(organisation_id,authorised_by_internal_user_id)references public.internal_users(organisation_id,id)
);
create table public.mission_pack_revisions(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null,operating_location_id uuid not null,mission_id uuid not null,
 version_number integer not null check(version_number>0),authorisation_revision_id uuid not null,authorisation_version integer not null,
 pack_snapshot jsonb not null check(jsonb_typeof(pack_snapshot)='object'),generated_at timestamptz not null default now(),generated_by_internal_user_id uuid not null,
 unique(organisation_id,id),unique(organisation_id,mission_id,version_number),
 foreign key(organisation_id,mission_id)references public.missions(organisation_id,id),foreign key(organisation_id,operating_location_id)references public.operating_locations(organisation_id,id),
 foreign key(organisation_id,authorisation_revision_id)references public.mission_authorisation_revisions(organisation_id,id),foreign key(organisation_id,generated_by_internal_user_id)references public.internal_users(organisation_id,id)
);
create index mission_authorisation_history_idx on public.mission_authorisation_revisions(organisation_id,mission_id,version_number desc);
create index mission_pack_history_idx on public.mission_pack_revisions(organisation_id,mission_id,version_number desc);
do $$declare t text;begin foreach t in array array['mission_authorisation_revisions','mission_pack_revisions']loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('create policy %I on public.%I for select to authenticated using(public.current_user_has_organisation_access(organisation_id))',t||'_tenant_read',t);execute format('revoke all on table public.%I from public,anon,authenticated',t);execute format('grant select,insert on table public.%I to service_role',t);end loop;end$$;

insert into public.permissions(organisation_id,code,description)select o.id,v.code,v.description from public.organisations o cross join(values
 ('mission.authorisation.read','View Mission readiness and immutable authorisations'),('mission.authorisation.authorise','Authorise an exact immutable Mission evidence set'),
 ('mission.pack.read','View immutable Mission Packs'),('mission.pack.generate','Generate a Mission Pack from authorised evidence'))v(code,description)on conflict(organisation_id,code)do update set description=excluded.description;
insert into public.role_permissions(organisation_id,role_id,permission_id)select r.organisation_id,r.id,p.id from public.roles r join public.permissions p on p.organisation_id=r.organisation_id where r.code='admin'and p.code in('mission.authorisation.read','mission.authorisation.authorise','mission.pack.read','mission.pack.generate')on conflict do nothing;
create function public.ftf_provision_mission_authorisation_permissions()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin
 insert into public.permissions(organisation_id,code,description)select new.organisation_id,v.code,v.description from(values('mission.authorisation.read','View Mission readiness and immutable authorisations'),('mission.authorisation.authorise','Authorise an exact immutable Mission evidence set'),('mission.pack.read','View immutable Mission Packs'),('mission.pack.generate','Generate a Mission Pack from authorised evidence'))v(code,description)on conflict(organisation_id,code)do nothing;
 if new.code='admin'then insert into public.role_permissions(organisation_id,role_id,permission_id)select new.organisation_id,new.id,p.id from public.permissions p where p.organisation_id=new.organisation_id and p.code in('mission.authorisation.read','mission.authorisation.authorise','mission.pack.read','mission.pack.generate')on conflict do nothing;end if;return new;end$$;
create trigger provision_mission_authorisation_permissions after insert on public.roles for each row execute function public.ftf_provision_mission_authorisation_permissions();

create function public.ftf_build_mission_evidence_manifest(p_organisation_id uuid,p_mission_id uuid,p_evaluated_at timestamptz default now())returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare m public.missions%rowtype;map jsonb;forecast jsonb;weather jsonb;personnel jsonb;jsa jsonb;chemicals jsonb;aircraft jsonb;kits jsonb;documents jsonb;
begin select * into m from public.missions where organisation_id=p_organisation_id and id=p_mission_id and archived_at is null;if not found then return null;end if;
 select x into map from public.ftf_read_mission_map(p_organisation_id,p_mission_id,false)x limit 1;
 select x into forecast from public.ftf_read_mission_weather_forecasts(p_organisation_id,p_mission_id)x where(x->>'selected')::boolean limit 1;
 select x into weather from public.ftf_read_mission_weather(p_organisation_id,p_mission_id,p_evaluated_at)x where(x->>'selected')::boolean limit 1;
 select x into personnel from public.ftf_read_mission_personnel(p_organisation_id,p_mission_id,false)x limit 1;
 select x into jsa from public.ftf_read_mission_jsa(p_organisation_id,p_mission_id,false)x limit 1;
 select x into chemicals from public.ftf_read_mission_chemical_plan(p_organisation_id,p_mission_id,false)x limit 1;
 select coalesce(jsonb_agg(jsonb_build_object('assignmentId',ma.id,'aircraftId',a.id,'rowVersion',a.row_version,'snapshot',to_jsonb(a)-'organisation_id')order by ma.assigned_at),'[]')into aircraft from public.mission_aircraft_assignments ma join public.aircraft a on a.organisation_id=ma.organisation_id and a.id=ma.aircraft_id where ma.organisation_id=p_organisation_id and ma.mission_id=p_mission_id and ma.unassigned_at is null;
 select coalesce(jsonb_agg(jsonb_build_object('assignmentId',mk.id,'equipmentKitId',k.id,'rowVersion',k.row_version,'snapshot',to_jsonb(k)-'organisation_id')order by mk.assigned_at),'[]')into kits from public.mission_equipment_kit_assignments mk join public.equipment_kits k on k.organisation_id=mk.organisation_id and k.id=mk.equipment_kit_id where mk.organisation_id=p_organisation_id and mk.mission_id=p_mission_id and mk.unassigned_at is null;
 select coalesce(jsonb_agg(jsonb_build_object('attachmentId',a.id,'internalFileId',a.internal_file_id,'fileVersion',a.file_version,'checksum',a.sha256_checksum,'evidenceType',a.evidence_type)order by a.attached_at),'[]')into documents from public.mission_jsa_attachments a where a.organisation_id=p_organisation_id and a.mission_id=p_mission_id and a.revision_id=nullif(jsa->>'id','')::uuid;
 return jsonb_build_object('schemaVersion',1,'capturedAt',p_evaluated_at,'mission',jsonb_build_object('id',m.id,'rowVersion',m.row_version,'snapshot',to_jsonb(m)-'organisation_id'),'planning',jsonb_build_object('map',map,'forecastWeather',forecast,'chemicals',chemicals,'aircraft',aircraft,'equipmentKits',kits,'personnel',personnel),'preflight',jsonb_build_object('observedWeather',weather,'jsa',jsa,'requiredDocuments',documents));end$$;

create function public.ftf_evaluate_mission_readiness(p_organisation_id uuid,p_mission_id uuid,p_evaluated_at timestamptz default now())returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare e jsonb;w jsonb;j jsonb;blockers jsonb='[]';warnings jsonb='[]';categories jsonb='{}';outstanding jsonb='[]';completed jsonb='[]';
begin e=public.ftf_build_mission_evidence_manifest(p_organisation_id,p_mission_id,p_evaluated_at);if e is null then return jsonb_build_object('notFound',true,'ready',false);end if;w=public.ftf_evaluate_mission_weather_readiness(p_organisation_id,p_mission_id,p_evaluated_at);j=public.ftf_evaluate_mission_jsa_readiness(p_organisation_id,p_mission_id);
 if coalesce(e#>'{planning,map}','null'::jsonb)='null'::jsonb then blockers=blockers||jsonb_build_array(jsonb_build_object('code','MAP_REQUIRED','category','Mission Map','message','Save an authoritative Mission map.'));outstanding=outstanding||'"Mission Map"';else completed=completed||'"Mission Map"';end if;
 if jsonb_array_length(e#>'{planning,aircraft}')=0 then blockers=blockers||jsonb_build_array(jsonb_build_object('code','AIRCRAFT_REQUIRED','category','Aircraft','message','Assign a mission-ready Aircraft.'));outstanding=outstanding||'"Aircraft"';else completed=completed||'"Aircraft"';end if;
 if jsonb_array_length(e#>'{planning,equipmentKits}')=0 then blockers=blockers||jsonb_build_array(jsonb_build_object('code','EQUIPMENT_REQUIRED','category','Equipment','message','Assign a compatible Equipment Kit.'));outstanding=outstanding||'"Equipment"';else completed=completed||'"Equipment"';end if;
 if coalesce(e#>'{planning,personnel}','null'::jsonb)='null'::jsonb then blockers=blockers||jsonb_build_array(jsonb_build_object('code','PERSONNEL_REQUIRED','category','Personnel','message','Save authoritative Mission Personnel including a PIC.'));outstanding=outstanding||'"Personnel"';else completed=completed||'"Personnel"';end if;
 if coalesce(e#>'{planning,chemicals}','null'::jsonb)='null'::jsonb then blockers=blockers||jsonb_build_array(jsonb_build_object('code','CHEMICAL_PLAN_REQUIRED','category','Chemical Plan','message','Save an authoritative Chemical plan.'));outstanding=outstanding||'"Chemical Plan"';else completed=completed||'"Chemical Plan"';end if;
 blockers=blockers||coalesce(w->'blockers','[]');warnings=warnings||coalesce(w->'warnings','[]');if(w->>'ready')::boolean then completed=completed||'"Pre-flight Weather"';else outstanding=outstanding||'"Pre-flight Weather"';end if;
 blockers=blockers||coalesce(j->'blockers','[]');warnings=warnings||coalesce(j->'warnings','[]');if(j->>'ready')::boolean then completed=completed||'"JSA"';else outstanding=outstanding||'"JSA"';end if;
 categories=jsonb_build_object('Planning Evidence',case when coalesce(e#>'{planning,map}','null')<>'null'::jsonb and jsonb_array_length(e#>'{planning,aircraft}')>0 and jsonb_array_length(e#>'{planning,equipmentKits}')>0 and coalesce(e#>'{planning,personnel}','null')<>'null'::jsonb and coalesce(e#>'{planning,chemicals}','null')<>'null'::jsonb then'COMPLETE'else'OUTSTANDING'end,'Pre-flight Weather',case when(w->>'ready')::boolean then'COMPLETE'else'OUTSTANDING'end,'JSA and Risk Controls',case when(j->>'ready')::boolean then'COMPLETE'else'OUTSTANDING'end,'Required Documents','COMPLETE');
 return jsonb_build_object('overallState',case when jsonb_array_length(blockers)=0 then case when jsonb_array_length(warnings)>0 then'WARNING'else'READY'end else'BLOCKED'end,'ready',jsonb_array_length(blockers)=0,'blockers',blockers,'warnings',warnings,'categories',categories,'outstandingSections',outstanding,'completedSections',completed,'evidenceManifest',e);end$$;

create function public.ftf_read_mission_authorisation(p_organisation_id uuid,p_mission_id uuid,p_history boolean default false)returns setof jsonb language sql security definer set search_path=public,pg_temp as $$select to_jsonb(a)from public.mission_authorisation_revisions a where a.organisation_id=p_organisation_id and a.mission_id=p_mission_id order by a.version_number desc limit case when p_history then 2147483647 else 1 end$$;
create function public.ftf_authorise_mission(p_organisation_id uuid,p_actor_internal_user_id uuid,p_mission_id uuid,p_expected_version integer,p_declaration text)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare m public.missions%rowtype;current integer;rdy jsonb;e jsonb;pic jsonb;person public.personnel%rowtype;a public.mission_authorisation_revisions%rowtype;
begin select * into m from public.missions where organisation_id=p_organisation_id and id=p_mission_id and archived_at is null for update;if not found then return jsonb_build_object('not_found',true);end if;
 if not exists(select 1 from public.memberships mm join public.membership_operating_location_assignments x on x.organisation_id=mm.organisation_id and x.membership_id=mm.id where mm.organisation_id=p_organisation_id and mm.internal_user_id=p_actor_internal_user_id and mm.is_active and mm.archived_at is null and x.operating_location_id=m.operating_location_id and x.is_active and x.archived_at is null)then return jsonb_build_object('location_forbidden',true);end if;
 select coalesce(max(version_number),0)into current from public.mission_authorisation_revisions where organisation_id=p_organisation_id and mission_id=p_mission_id;if current<>p_expected_version then return jsonb_build_object('conflict',true,'current_version',current);end if;
 rdy=public.ftf_evaluate_mission_readiness(p_organisation_id,p_mission_id,now());if not(rdy->>'ready')::boolean then return jsonb_build_object('readiness_blocked',true,'readiness',rdy);end if;e=rdy->'evidenceManifest';
 select x into pic from jsonb_array_elements(coalesce(e#>'{planning,personnel,assignments}','[]'))x where x->>'assignmentRole'='pilot_in_command'limit 1;if pic is null then select x into pic from jsonb_array_elements(coalesce(e#>'{planning,personnel,assignments}','[]'))x where x->>'assignment_role'='pilot_in_command'limit 1;end if;
 select * into person from public.personnel where organisation_id=p_organisation_id and id=coalesce(nullif(pic->>'personnelId',''),nullif(pic->>'personnel_id',''))::uuid and internal_user_id=p_actor_internal_user_id and archived_at is null;if not found then return jsonb_build_object('pic_forbidden',true);end if;
 insert into public.mission_authorisation_revisions(organisation_id,operating_location_id,mission_id,version_number,evidence_manifest,readiness_snapshot,declaration,authorised_personnel_id,authorised_personnel_snapshot,authorised_by_internal_user_id)values(p_organisation_id,m.operating_location_id,p_mission_id,current+1,e,rdy,p_declaration,person.id,coalesce(pic->'snapshot',to_jsonb(person)-'organisation_id'),p_actor_internal_user_id)returning * into a;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'mission.authorised','mission',p_mission_id,jsonb_build_object('authorisation_revision_id',a.id,'version',a.version_number,'evidence_schema_version',1));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'preflight.mission.authorised','mission',p_mission_id,jsonb_build_object('authorisation_revision_id',a.id,'version',a.version_number));return jsonb_build_object('record',to_jsonb(a));end$$;

create function public.ftf_read_mission_pack(p_organisation_id uuid,p_mission_id uuid,p_history boolean default false)returns setof jsonb language sql security definer set search_path=public,pg_temp as $$select to_jsonb(p)from public.mission_pack_revisions p where p.organisation_id=p_organisation_id and p.mission_id=p_mission_id order by p.version_number desc limit case when p_history then 2147483647 else 1 end$$;
create function public.ftf_generate_mission_pack(p_organisation_id uuid,p_actor_internal_user_id uuid,p_mission_id uuid,p_authorisation_revision_id uuid,p_expected_version integer)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare a public.mission_authorisation_revisions%rowtype;current integer;p public.mission_pack_revisions%rowtype;
begin select * into a from public.mission_authorisation_revisions where organisation_id=p_organisation_id and mission_id=p_mission_id and id=p_authorisation_revision_id;if not found then return jsonb_build_object('not_found',true);end if;
 if not exists(select 1 from public.memberships m join public.membership_operating_location_assignments x on x.organisation_id=m.organisation_id and x.membership_id=m.id where m.organisation_id=p_organisation_id and m.internal_user_id=p_actor_internal_user_id and m.is_active and m.archived_at is null and x.operating_location_id=a.operating_location_id and x.is_active and x.archived_at is null)then return jsonb_build_object('location_forbidden',true);end if;
 select coalesce(max(version_number),0)into current from public.mission_pack_revisions where organisation_id=p_organisation_id and mission_id=p_mission_id;if current<>p_expected_version then return jsonb_build_object('conflict',true,'current_version',current);end if;
 insert into public.mission_pack_revisions(organisation_id,operating_location_id,mission_id,version_number,authorisation_revision_id,authorisation_version,pack_snapshot,generated_by_internal_user_id)values(p_organisation_id,a.operating_location_id,p_mission_id,current+1,a.id,a.version_number,jsonb_build_object('schemaVersion',1,'title','Spray Command Mission Pack','authorisation',to_jsonb(a),'evidence',a.evidence_manifest,'readiness',a.readiness_snapshot),p_actor_internal_user_id)returning * into p;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'mission.pack_generated','mission',p_mission_id,jsonb_build_object('pack_revision_id',p.id,'authorisation_revision_id',a.id,'version',p.version_number));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'completion.mission.pack_generated','mission',p_mission_id,jsonb_build_object('pack_revision_id',p.id,'authorisation_revision_id',a.id,'version',p.version_number));return jsonb_build_object('record',to_jsonb(p));end$$;

revoke all on function public.ftf_provision_mission_authorisation_permissions(),public.ftf_build_mission_evidence_manifest(uuid,uuid,timestamptz),public.ftf_evaluate_mission_readiness(uuid,uuid,timestamptz),public.ftf_read_mission_authorisation(uuid,uuid,boolean),public.ftf_authorise_mission(uuid,uuid,uuid,integer,text),public.ftf_read_mission_pack(uuid,uuid,boolean),public.ftf_generate_mission_pack(uuid,uuid,uuid,uuid,integer)from public,anon,authenticated;
grant execute on function public.ftf_build_mission_evidence_manifest(uuid,uuid,timestamptz),public.ftf_evaluate_mission_readiness(uuid,uuid,timestamptz),public.ftf_read_mission_authorisation(uuid,uuid,boolean),public.ftf_authorise_mission(uuid,uuid,uuid,integer,text),public.ftf_read_mission_pack(uuid,uuid,boolean),public.ftf_generate_mission_pack(uuid,uuid,uuid,uuid,integer)to service_role;
