-- Immutable, versioned Weather evidence used by Mission planning and authorisation.
create function public.ftf_calculate_delta_t(p_temperature_c numeric,p_relative_humidity numeric)
returns numeric language plpgsql immutable strict as $$
declare v_wet_bulb numeric;
begin
 if p_relative_humidity<0 or p_relative_humidity>100 then raise exception 'relative humidity must be between 0 and 100';end if;
 v_wet_bulb=p_temperature_c*atan(0.151977*sqrt(p_relative_humidity+8.313659))+atan(p_temperature_c+p_relative_humidity)-atan(p_relative_humidity-1.676331)+0.00391838*power(p_relative_humidity,1.5)*atan(0.023101*p_relative_humidity)-4.686035;
 return round(p_temperature_c-v_wet_bulb,1);
end $$;

create function public.ftf_weather_freshness(p_observed_at timestamptz,p_evaluated_at timestamptz,p_freshness_minutes integer,p_approaching_minutes integer)
returns text language plpgsql immutable strict as $$
declare v_age interval;
begin
 if p_freshness_minutes<=0 or p_approaching_minutes<0 or p_approaching_minutes>p_freshness_minutes then raise exception 'invalid weather freshness policy';end if;
 v_age=p_evaluated_at-p_observed_at;
 if v_age<interval '0 seconds' then return 'CURRENT';end if;
 if v_age>make_interval(mins=>p_freshness_minutes) then return 'EXPIRED';end if;
 if v_age>=make_interval(mins=>p_freshness_minutes-p_approaching_minutes) then return 'APPROACHING_EXPIRY';end if;
 return 'CURRENT';
end $$;

create table public.organisation_weather_policies(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null,manual_freshness_minutes integer not null default 60 check(manual_freshness_minutes>0),provider_freshness_minutes integer not null default 120 check(provider_freshness_minutes>0),approaching_expiry_minutes integer not null default 15 check(approaching_expiry_minutes>=0),require_mission_assignment boolean not null default true,require_second_person_verification boolean not null default false,row_version integer not null default 1 check(row_version>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organisation_id),foreign key(organisation_id) references public.organisations(id)
);
create table public.mission_weather_observations(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null,operating_location_id uuid not null,mission_id uuid not null,version_number integer not null check(version_number>0),source text not null check(source in('MANUAL','OPEN_METEO')),provider_identifier text,observer_personnel_id uuid,observation_location text not null,latitude numeric(9,6) not null check(latitude between -90 and 90),longitude numeric(9,6) not null check(longitude between -180 and 180),observed_at timestamptz not null,retrieved_at timestamptz,temperature_c numeric(5,2) not null,relative_humidity numeric(5,2) not null check(relative_humidity between 0 and 100),delta_t_c numeric(5,1) not null,wind_speed_kmh numeric(6,2) not null check(wind_speed_kmh>=0),wind_direction_degrees numeric(5,1) not null check(wind_direction_degrees>=0 and wind_direction_degrees<360),precipitation_mm numeric(7,2) not null default 0 check(precipitation_mm>=0),cloud_description text,inversion_assessment text not null check(inversion_assessment in('NOT_ASSESSED','UNLIKELY','POSSIBLE','LIKELY','CONFIRMED','UNABLE_TO_DETERMINE')),inversion_assessment_source text not null,inversion_assessor_personnel_id uuid,inversion_assessed_at timestamptz not null,inversion_notes text,manual_reason text,notes text,provider_snapshot jsonb,transformation_metadata jsonb not null default '{}'::jsonb,record_version integer not null default 1,created_at timestamptz not null default now(),created_by_internal_user_id uuid not null,
 unique(organisation_id,id),unique(organisation_id,mission_id,version_number),foreign key(organisation_id,mission_id) references public.missions(organisation_id,id),foreign key(organisation_id,operating_location_id) references public.operating_locations(organisation_id,id),foreign key(organisation_id,observer_personnel_id) references public.personnel(organisation_id,id),foreign key(organisation_id,inversion_assessor_personnel_id) references public.personnel(organisation_id,id),foreign key(organisation_id,created_by_internal_user_id) references public.internal_users(organisation_id,id),check((source='MANUAL' and observer_personnel_id is not null and length(trim(manual_reason))>0) or source='OPEN_METEO')
);
create table public.mission_weather_selections(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null,operating_location_id uuid not null,mission_id uuid not null,observation_id uuid not null,observation_version integer not null,selection_version integer not null check(selection_version>0),selected_at timestamptz not null default now(),selected_by_internal_user_id uuid not null,unique(organisation_id,mission_id,selection_version),foreign key(organisation_id,mission_id) references public.missions(organisation_id,id),foreign key(organisation_id,observation_id) references public.mission_weather_observations(organisation_id,id),foreign key(organisation_id,operating_location_id) references public.operating_locations(organisation_id,id),foreign key(organisation_id,selected_by_internal_user_id) references public.internal_users(organisation_id,id)
);
create index mission_weather_history_idx on public.mission_weather_observations(organisation_id,mission_id,version_number desc);
do $$declare t text;begin foreach t in array array['organisation_weather_policies','mission_weather_observations','mission_weather_selections'] loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('create policy %I on public.%I for select to authenticated using(public.current_user_has_organisation_access(organisation_id))',t||'_tenant_read',t);execute format('revoke all on table public.%I from public,anon,authenticated',t);execute format('grant select,insert,update,delete on table public.%I to service_role',t);end loop;end$$;
insert into public.organisation_weather_policies(organisation_id)select id from public.organisations on conflict(organisation_id)do nothing;
create function public.ftf_provision_weather_policy()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin insert into public.organisation_weather_policies(organisation_id)values(new.id)on conflict(organisation_id)do nothing;return new;end$$;
create trigger organisations_provision_weather_policy after insert on public.organisations for each row execute function public.ftf_provision_weather_policy();
create or replace function public.ftf_provision_weather_permissions()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin
 insert into public.permissions(organisation_id,code,description)select new.organisation_id,v.code,v.description from(values
 ('weather.read','View authoritative Mission Weather'),('weather.observe.manual','Record manual Mission Weather'),('weather.observe.provider','Retrieve provider Mission Weather'),('weather.select','Select Mission Weather evidence'))v(code,description)on conflict(organisation_id,code)do nothing;
 if new.code='admin'then insert into public.role_permissions(organisation_id,role_id,permission_id)select new.organisation_id,new.id,p.id from public.permissions p where p.organisation_id=new.organisation_id and p.code like 'weather.%'on conflict do nothing;end if;return new;
end$$;
create trigger roles_provision_weather_permissions after insert on public.roles for each row execute function public.ftf_provision_weather_permissions();
insert into public.permissions(organisation_id,code,description)select o.id,v.code,v.description from public.organisations o cross join(values
 ('weather.read','View authoritative Mission Weather'),('weather.observe.manual','Record manual Mission Weather'),('weather.observe.provider','Retrieve provider Mission Weather'),('weather.select','Select Mission Weather evidence'))v(code,description)on conflict(organisation_id,code)do nothing;
insert into public.role_permissions(organisation_id,role_id,permission_id)select r.organisation_id,r.id,p.id from public.roles r join public.permissions p on p.organisation_id=r.organisation_id and p.code like 'weather.%'where r.code='admin'on conflict do nothing;
revoke all on function public.ftf_calculate_delta_t(numeric,numeric),public.ftf_weather_freshness(timestamptz,timestamptz,integer,integer) from public,anon,authenticated;
grant execute on function public.ftf_calculate_delta_t(numeric,numeric),public.ftf_weather_freshness(timestamptz,timestamptz,integer,integer) to service_role;

create function public.ftf_create_mission_weather_observation(p_organisation_id uuid,p_actor_internal_user_id uuid,p_mission_id uuid,p_expected_version integer,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_mission public.missions%rowtype;v_policy public.organisation_weather_policies%rowtype;v_observer public.personnel%rowtype;v_current integer;v_delta numeric;v_submitted numeric;v_record public.mission_weather_observations%rowtype;v_source text;begin
 select * into v_mission from public.missions where organisation_id=p_organisation_id and id=p_mission_id and archived_at is null for update;
 if not found then return jsonb_build_object('not_found',true);end if;
 if not exists(select 1 from public.memberships m join public.membership_operating_location_assignments a on a.organisation_id=m.organisation_id and a.membership_id=m.id where m.organisation_id=p_organisation_id and m.internal_user_id=p_actor_internal_user_id and m.is_active and m.archived_at is null and a.operating_location_id=v_mission.operating_location_id and a.is_active and a.archived_at is null)then return jsonb_build_object('location_forbidden',true);end if;
 select * into v_policy from public.organisation_weather_policies where organisation_id=p_organisation_id;
 select coalesce(max(version_number),0)into v_current from public.mission_weather_observations where organisation_id=p_organisation_id and mission_id=p_mission_id;
 if v_current<>p_expected_version then return jsonb_build_object('conflict',true,'current_version',v_current);end if;
 v_source=upper(coalesce(p_payload->>'source',''));
 if v_source not in('MANUAL','OPEN_METEO')then raise exception 'weather source is invalid';end if;
 if v_source='MANUAL' then
  select * into v_observer from public.personnel where organisation_id=p_organisation_id and id=(p_payload->>'observerPersonnelId')::uuid and archived_at is null and is_active;
  if not found then return jsonb_build_object('observer_invalid',true);end if;
  if not exists(select 1 from public.personnel_operating_locations where organisation_id=p_organisation_id and personnel_id=v_observer.id and operating_location_id=v_mission.operating_location_id)then return jsonb_build_object('observer_invalid',true);end if;
  if v_policy.require_mission_assignment and not exists(select 1 from public.mission_personnel_assignments a join public.mission_personnel_revisions r on r.organisation_id=a.organisation_id and r.id=a.revision_id where a.organisation_id=p_organisation_id and a.mission_id=p_mission_id and a.personnel_id=v_observer.id and r.version_number=(select max(version_number)from public.mission_personnel_revisions where organisation_id=p_organisation_id and mission_id=p_mission_id))then return jsonb_build_object('observer_unassigned',true);end if;
 end if;
 if nullif(trim(p_payload->>'observationLocation'),'') is null or nullif(p_payload->>'observedAt','') is null or (p_payload->>'temperatureC') is null or (p_payload->>'relativeHumidity') is null or (p_payload->>'windSpeedKmh') is null or (p_payload->>'windDirectionDegrees') is null or nullif(p_payload->>'inversionAssessment','') is null then raise exception 'required weather fields are missing';end if;
 v_delta=public.ftf_calculate_delta_t((p_payload->>'temperatureC')::numeric,(p_payload->>'relativeHumidity')::numeric);v_submitted=nullif(p_payload->>'deltaTC','')::numeric;
 if v_submitted is not null and abs(v_submitted-v_delta)>0.3 then return jsonb_build_object('delta_t_mismatch',true,'calculated_delta_t',v_delta);end if;
 insert into public.mission_weather_observations(organisation_id,operating_location_id,mission_id,version_number,source,provider_identifier,observer_personnel_id,observation_location,latitude,longitude,observed_at,retrieved_at,temperature_c,relative_humidity,delta_t_c,wind_speed_kmh,wind_direction_degrees,precipitation_mm,cloud_description,inversion_assessment,inversion_assessment_source,inversion_assessor_personnel_id,inversion_assessed_at,inversion_notes,manual_reason,notes,provider_snapshot,transformation_metadata,created_by_internal_user_id)
 values(p_organisation_id,v_mission.operating_location_id,p_mission_id,v_current+1,v_source,nullif(p_payload->>'providerIdentifier',''),case when v_source='MANUAL'then v_observer.id else null end,p_payload->>'observationLocation',(p_payload->>'latitude')::numeric,(p_payload->>'longitude')::numeric,(p_payload->>'observedAt')::timestamptz,nullif(p_payload->>'retrievedAt','')::timestamptz,(p_payload->>'temperatureC')::numeric,(p_payload->>'relativeHumidity')::numeric,v_delta,(p_payload->>'windSpeedKmh')::numeric,(p_payload->>'windDirectionDegrees')::numeric,coalesce((p_payload->>'precipitationMm')::numeric,0),nullif(p_payload->>'cloudDescription',''),p_payload->>'inversionAssessment',coalesce(nullif(p_payload->>'inversionAssessmentSource',''),v_source),coalesce(nullif(p_payload->>'inversionAssessorPersonnelId','')::uuid,case when v_source='MANUAL'then v_observer.id else null end),coalesce(nullif(p_payload->>'inversionAssessedAt','')::timestamptz,(p_payload->>'observedAt')::timestamptz),nullif(p_payload->>'inversionNotes',''),nullif(p_payload->>'manualReason',''),nullif(p_payload->>'notes',''),p_payload->'providerSnapshot',coalesce(p_payload->'transformationMetadata','{}'::jsonb),p_actor_internal_user_id)returning * into v_record;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'mission.weather_observed','mission_weather_observation',v_record.id,jsonb_build_object('mission_id',p_mission_id,'version',v_record.version_number,'source',v_source));
 insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'operational.mission.weather_observed','mission',p_mission_id,jsonb_build_object('observation_id',v_record.id,'version',v_record.version_number,'source',v_source));
 return jsonb_build_object('record',to_jsonb(v_record));
end$$;

create function public.ftf_read_mission_weather(p_organisation_id uuid,p_mission_id uuid,p_evaluated_at timestamptz default now())returns setof jsonb language sql security definer set search_path=public,pg_temp as $$
 select to_jsonb(o)||jsonb_build_object('freshness_state',public.ftf_weather_freshness(o.observed_at,p_evaluated_at,case when o.source='MANUAL'then p.manual_freshness_minutes else p.provider_freshness_minutes end,p.approaching_expiry_minutes),'selection_version',coalesce((select max(selection_version)from public.mission_weather_selections where organisation_id=o.organisation_id and mission_id=o.mission_id),0),'selected',exists(select 1 from public.mission_weather_selections s where s.organisation_id=o.organisation_id and s.mission_id=o.mission_id and s.observation_id=o.id and s.selection_version=(select max(selection_version)from public.mission_weather_selections where organisation_id=o.organisation_id and mission_id=o.mission_id)))from public.mission_weather_observations o join public.organisation_weather_policies p using(organisation_id)where o.organisation_id=p_organisation_id and o.mission_id=p_mission_id order by o.version_number desc;$$;

create function public.ftf_select_mission_weather_observation(p_organisation_id uuid,p_actor_internal_user_id uuid,p_mission_id uuid,p_observation_id uuid,p_expected_selection_version integer)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v_o public.mission_weather_observations%rowtype;v_current integer;v_s public.mission_weather_selections%rowtype;begin select * into v_o from public.mission_weather_observations where organisation_id=p_organisation_id and mission_id=p_mission_id and id=p_observation_id;if not found then return jsonb_build_object('not_found',true);end if;if not exists(select 1 from public.memberships m join public.membership_operating_location_assignments a on a.organisation_id=m.organisation_id and a.membership_id=m.id where m.organisation_id=p_organisation_id and m.internal_user_id=p_actor_internal_user_id and m.is_active and m.archived_at is null and a.operating_location_id=v_o.operating_location_id and a.is_active and a.archived_at is null)then return jsonb_build_object('location_forbidden',true);end if;select coalesce(max(selection_version),0)into v_current from public.mission_weather_selections where organisation_id=p_organisation_id and mission_id=p_mission_id;if v_current<>p_expected_selection_version then return jsonb_build_object('conflict',true,'current_version',v_current);end if;insert into public.mission_weather_selections(organisation_id,operating_location_id,mission_id,observation_id,observation_version,selection_version,selected_by_internal_user_id)values(p_organisation_id,v_o.operating_location_id,p_mission_id,v_o.id,v_o.version_number,v_current+1,p_actor_internal_user_id)returning * into v_s;insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'mission.weather_selected','mission',p_mission_id,jsonb_build_object('observation_id',v_o.id,'observation_version',v_o.version_number,'selection_version',v_s.selection_version));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'operational.mission.weather_selected','mission',p_mission_id,jsonb_build_object('observation_id',v_o.id,'observation_version',v_o.version_number,'selection_version',v_s.selection_version));return jsonb_build_object('record',to_jsonb(v_s));end$$;

create function public.ftf_evaluate_mission_weather_readiness(p_organisation_id uuid,p_mission_id uuid,p_evaluated_at timestamptz default now())returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v_w jsonb;v_blockers jsonb='[]';v_warnings jsonb='[]';begin select x into v_w from public.ftf_read_mission_weather(p_organisation_id,p_mission_id,p_evaluated_at)x where (x->>'selected')::boolean limit 1;if v_w is null then return jsonb_build_object('ready',false,'blockers',jsonb_build_array(jsonb_build_object('code','WEATHER_NOT_SELECTED','message','Select authoritative Weather evidence for this Mission.')),'warnings',v_warnings,'freshnessState',null);end if;if v_w->>'freshness_state'='EXPIRED'then v_blockers=v_blockers||jsonb_build_array(jsonb_build_object('code','WEATHER_EXPIRED','message','Selected Weather evidence has expired.'));elsif v_w->>'freshness_state'='APPROACHING_EXPIRY'then v_warnings=v_warnings||jsonb_build_array(jsonb_build_object('code','WEATHER_APPROACHING_EXPIRY','message','Selected Weather evidence is approaching expiry.'));end if;if (v_w->>'inversion_assessment') in('LIKELY','CONFIRMED')then v_blockers=v_blockers||jsonb_build_array(jsonb_build_object('code','INVERSION_BLOCK','message','The inversion assessment blocks Mission readiness.'));elsif (v_w->>'inversion_assessment') in('POSSIBLE','NOT_ASSESSED','UNABLE_TO_DETERMINE')then v_warnings=v_warnings||jsonb_build_array(jsonb_build_object('code','INVERSION_REVIEW','message','The inversion assessment requires review.'));end if;return jsonb_build_object('ready',jsonb_array_length(v_blockers)=0,'blockers',v_blockers,'warnings',v_warnings,'freshnessState',v_w->>'freshness_state','observation',v_w);end$$;

revoke all on function public.ftf_create_mission_weather_observation(uuid,uuid,uuid,integer,jsonb),public.ftf_read_mission_weather(uuid,uuid,timestamptz),public.ftf_select_mission_weather_observation(uuid,uuid,uuid,uuid,integer),public.ftf_evaluate_mission_weather_readiness(uuid,uuid,timestamptz)from public,anon,authenticated;
grant execute on function public.ftf_create_mission_weather_observation(uuid,uuid,uuid,integer,jsonb),public.ftf_read_mission_weather(uuid,uuid,timestamptz),public.ftf_select_mission_weather_observation(uuid,uuid,uuid,uuid,integer),public.ftf_evaluate_mission_weather_readiness(uuid,uuid,timestamptz)to service_role;
revoke all on function public.ftf_provision_weather_policy(),public.ftf_provision_weather_permissions()from public,anon,authenticated;
