-- NEW-CMP-015: protected organisation compliance files and controlled document commands.

create function public.ftf_record_compliance_instrument_evidence(p_organisation_id uuid,p_actor_internal_user_id uuid,p_instrument_id uuid,p_payload jsonb)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v public.compliance_instrument_evidence%rowtype;begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'compliance.manage')then return jsonb_build_object('forbidden',true);end if;
 if not exists(select 1 from public.organisation_compliance_instruments where organisation_id=p_organisation_id and id=p_instrument_id)then return jsonb_build_object('not_found',true);end if;
 insert into public.compliance_instrument_evidence(organisation_id,instrument_id,internal_file_id,file_version,original_filename,content_type,byte_size,sha256_checksum,provenance,access_classification,created_by_internal_user_id)values(p_organisation_id,p_instrument_id,(p_payload->>'internalFileId')::uuid,(p_payload->>'fileVersion')::integer,p_payload->>'originalFilename',p_payload->>'contentType',(p_payload->>'sizeBytes')::bigint,p_payload->>'checksumSha256',p_payload->'provenance',coalesce(p_payload->>'accessClassification','RESTRICTED'),p_actor_internal_user_id)returning*into v;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'compliance.instrument.evidence_recorded','compliance_instrument_evidence',v.id,jsonb_build_object('instrumentId',p_instrument_id,'internalFileId',v.internal_file_id,'fileVersion',v.file_version,'checksum',v.sha256_checksum));
 insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'compliance.instrument.evidence_recorded','compliance_instrument',p_instrument_id,jsonb_build_object('evidenceId',v.id,'internalFileId',v.internal_file_id,'fileVersion',v.file_version));return jsonb_build_object('record',to_jsonb(v));end$$;

create function public.ftf_create_controlled_document(p_organisation_id uuid,p_actor_internal_user_id uuid,p_payload jsonb)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v public.controlled_documents%rowtype;begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'compliance.publish')then return jsonb_build_object('forbidden',true);end if;
 insert into public.controlled_documents(organisation_id,document_type,title,status,created_by_internal_user_id,updated_by_internal_user_id)values(p_organisation_id,p_payload->>'documentType',p_payload->>'title','DRAFT',p_actor_internal_user_id,p_actor_internal_user_id)returning*into v;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'compliance.document.created','controlled_document',v.id,jsonb_build_object('documentType',v.document_type));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'compliance.document.created','controlled_document',v.id,jsonb_build_object('documentType',v.document_type));return jsonb_build_object('record',to_jsonb(v));end$$;

revoke all on function public.ftf_record_compliance_instrument_evidence(uuid,uuid,uuid,jsonb),public.ftf_create_controlled_document(uuid,uuid,jsonb)from public,anon,authenticated;
grant execute on function public.ftf_record_compliance_instrument_evidence(uuid,uuid,uuid,jsonb),public.ftf_create_controlled_document(uuid,uuid,jsonb)to service_role;
