-- Separate immutable Planning forecast evidence from observed Pre-flight Weather.
create table public.mission_weather_forecast_revisions(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null,operating_location_id uuid not null,mission_id uuid not null,
 version_number integer not null check(version_number>0),evidence_stage text not null default 'PLANNING' check(evidence_stage='PLANNING'),
 provider text not null check(provider in('OPEN_METEO')),provider_model text,issued_at timestamptz not null,valid_from timestamptz not null,valid_to timestamptz not null,
 latitude numeric(9,6) not null check(latitude between -90 and 90),longitude numeric(9,6) not null check(longitude between -180 and 180),
 provider_snapshot jsonb not null,transformation_metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),created_by_internal_user_id uuid not null,
 unique(organisation_id,id),unique(organisation_id,mission_id,version_number),check(valid_to>valid_from),
 foreign key(organisation_id,mission_id)references public.missions(organisation_id,id),foreign key(organisation_id,operating_location_id)references public.operating_locations(organisation_id,id),foreign key(organisation_id,created_by_internal_user_id)references public.internal_users(organisation_id,id)
);
create table public.mission_weather_forecast_selections(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null,operating_location_id uuid not null,mission_id uuid not null,forecast_revision_id uuid not null,forecast_version integer not null,
 selection_version integer not null check(selection_version>0),selected_at timestamptz not null default now(),selected_by_internal_user_id uuid not null,
 unique(organisation_id,mission_id,selection_version),foreign key(organisation_id,mission_id)references public.missions(organisation_id,id),foreign key(organisation_id,forecast_revision_id)references public.mission_weather_forecast_revisions(organisation_id,id),foreign key(organisation_id,operating_location_id)references public.operating_locations(organisation_id,id),foreign key(organisation_id,selected_by_internal_user_id)references public.internal_users(organisation_id,id)
);
create index mission_weather_forecast_history_idx on public.mission_weather_forecast_revisions(organisation_id,mission_id,version_number desc);
do $$declare t text;begin foreach t in array array['mission_weather_forecast_revisions','mission_weather_forecast_selections']loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('create policy %I on public.%I for select to authenticated using(public.current_user_has_organisation_access(organisation_id))',t||'_tenant_read',t);execute format('revoke all on table public.%I from public,anon,authenticated',t);execute format('grant select,insert,update,delete on table public.%I to service_role',t);end loop;end$$;

insert into public.permissions(organisation_id,code,description)select o.id,v.code,v.description from public.organisations o cross join(values('weather.forecast.create','Create immutable Planning forecast evidence'),('weather.forecast.select','Select Planning forecast evidence'))v(code,description)on conflict(organisation_id,code)do nothing;
insert into public.role_permissions(organisation_id,role_id,permission_id)select r.organisation_id,r.id,p.id from public.roles r join public.permissions p on p.organisation_id=r.organisation_id and p.code in('weather.forecast.create','weather.forecast.select')where r.code='admin'on conflict do nothing;
create or replace function public.ftf_provision_weather_permissions()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin
 insert into public.permissions(organisation_id,code,description)select new.organisation_id,v.code,v.description from(values('weather.read','View authoritative Mission Weather'),('weather.observe.manual','Record manual Mission Weather'),('weather.observe.provider','Retrieve provider Mission Weather'),('weather.select','Select Mission Weather evidence'),('weather.forecast.create','Create immutable Planning forecast evidence'),('weather.forecast.select','Select Planning forecast evidence'))v(code,description)on conflict(organisation_id,code)do nothing;
 if new.code='admin'then insert into public.role_permissions(organisation_id,role_id,permission_id)select new.organisation_id,new.id,p.id from public.permissions p where p.organisation_id=new.organisation_id and p.code like 'weather.%'on conflict do nothing;end if;return new;end$$;

create function public.ftf_create_mission_weather_forecast(p_organisation_id uuid,p_actor_internal_user_id uuid,p_mission_id uuid,p_expected_version integer,p_payload jsonb)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_m public.missions%rowtype;v_current integer;v_r public.mission_weather_forecast_revisions%rowtype;begin
 select * into v_m from public.missions where organisation_id=p_organisation_id and id=p_mission_id and archived_at is null for update;if not found then return jsonb_build_object('not_found',true);end if;
 if not exists(select 1 from public.memberships m join public.membership_operating_location_assignments a on a.organisation_id=m.organisation_id and a.membership_id=m.id where m.organisation_id=p_organisation_id and m.internal_user_id=p_actor_internal_user_id and m.is_active and m.archived_at is null and a.operating_location_id=v_m.operating_location_id and a.is_active and a.archived_at is null)then return jsonb_build_object('location_forbidden',true);end if;
 select coalesce(max(version_number),0)into v_current from public.mission_weather_forecast_revisions where organisation_id=p_organisation_id and mission_id=p_mission_id;if v_current<>p_expected_version then return jsonb_build_object('conflict',true,'current_version',v_current);end if;
 insert into public.mission_weather_forecast_revisions(organisation_id,operating_location_id,mission_id,version_number,provider,provider_model,issued_at,valid_from,valid_to,latitude,longitude,provider_snapshot,transformation_metadata,created_by_internal_user_id)
 values(p_organisation_id,v_m.operating_location_id,p_mission_id,v_current+1,p_payload->>'provider',nullif(p_payload->>'providerModel',''),(p_payload->>'issuedAt')::timestamptz,(p_payload->>'validFrom')::timestamptz,(p_payload->>'validTo')::timestamptz,(p_payload->>'latitude')::numeric,(p_payload->>'longitude')::numeric,p_payload->'snapshot',coalesce(p_payload->'transformationMetadata','{}'::jsonb),p_actor_internal_user_id)returning * into v_r;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'mission.weather_forecast_created','mission_weather_forecast_revision',v_r.id,jsonb_build_object('mission_id',p_mission_id,'version',v_r.version_number,'stage','PLANNING'));
 insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'planning.mission.weather_forecast_created','mission',p_mission_id,jsonb_build_object('forecast_revision_id',v_r.id,'version',v_r.version_number,'stage','PLANNING'));
 return jsonb_build_object('record',to_jsonb(v_r));end$$;

create function public.ftf_read_mission_weather_forecasts(p_organisation_id uuid,p_mission_id uuid)returns setof jsonb language sql security definer set search_path=public,pg_temp as $$
 select to_jsonb(f)||jsonb_build_object('selected',exists(select 1 from public.mission_weather_forecast_selections s where s.organisation_id=f.organisation_id and s.mission_id=f.mission_id and s.forecast_revision_id=f.id and s.selection_version=(select max(selection_version)from public.mission_weather_forecast_selections where organisation_id=f.organisation_id and mission_id=f.mission_id)),'selection_version',coalesce((select max(selection_version)from public.mission_weather_forecast_selections where organisation_id=f.organisation_id and mission_id=f.mission_id),0))from public.mission_weather_forecast_revisions f where f.organisation_id=p_organisation_id and f.mission_id=p_mission_id order by f.version_number desc;$$;

create function public.ftf_select_mission_weather_forecast(p_organisation_id uuid,p_actor_internal_user_id uuid,p_mission_id uuid,p_forecast_revision_id uuid,p_expected_selection_version integer)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_f public.mission_weather_forecast_revisions%rowtype;v_current integer;v_s public.mission_weather_forecast_selections%rowtype;begin
 select * into v_f from public.mission_weather_forecast_revisions where organisation_id=p_organisation_id and mission_id=p_mission_id and id=p_forecast_revision_id;if not found then return jsonb_build_object('not_found',true);end if;
 if not exists(select 1 from public.memberships m join public.membership_operating_location_assignments a on a.organisation_id=m.organisation_id and a.membership_id=m.id where m.organisation_id=p_organisation_id and m.internal_user_id=p_actor_internal_user_id and m.is_active and m.archived_at is null and a.operating_location_id=v_f.operating_location_id and a.is_active and a.archived_at is null)then return jsonb_build_object('location_forbidden',true);end if;
 select coalesce(max(selection_version),0)into v_current from public.mission_weather_forecast_selections where organisation_id=p_organisation_id and mission_id=p_mission_id;if v_current<>p_expected_selection_version then return jsonb_build_object('conflict',true,'current_version',v_current);end if;
 insert into public.mission_weather_forecast_selections(organisation_id,operating_location_id,mission_id,forecast_revision_id,forecast_version,selection_version,selected_by_internal_user_id)values(p_organisation_id,v_f.operating_location_id,p_mission_id,v_f.id,v_f.version_number,v_current+1,p_actor_internal_user_id)returning * into v_s;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'mission.weather_forecast_selected','mission',p_mission_id,jsonb_build_object('forecast_revision_id',v_f.id,'forecast_version',v_f.version_number,'selection_version',v_s.selection_version));
 insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'planning.mission.weather_forecast_selected','mission',p_mission_id,jsonb_build_object('forecast_revision_id',v_f.id,'forecast_version',v_f.version_number,'selection_version',v_s.selection_version));return jsonb_build_object('record',to_jsonb(v_s));end$$;

create or replace function public.ftf_evaluate_mission_weather_readiness(p_organisation_id uuid,p_mission_id uuid,p_evaluated_at timestamptz default now())returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v_w jsonb;v_f jsonb;v_blockers jsonb='[]';v_warnings jsonb='[]';begin
 select x into v_f from public.ftf_read_mission_weather_forecasts(p_organisation_id,p_mission_id)x where (x->>'selected')::boolean limit 1;
 select x into v_w from public.ftf_read_mission_weather(p_organisation_id,p_mission_id,p_evaluated_at)x where (x->>'selected')::boolean limit 1;
 if v_w is null then v_blockers=v_blockers||jsonb_build_array(jsonb_build_object('code','OBSERVED_WEATHER_NOT_SELECTED','category','Pre-flight Weather','message','Select observed pre-flight Weather before Mission Authorisation.'));else
  if v_w->>'freshness_state'='EXPIRED'then v_blockers=v_blockers||jsonb_build_array(jsonb_build_object('code','WEATHER_EXPIRED','category','Pre-flight Weather','message','Selected observed Weather has expired.'));elsif v_w->>'freshness_state'='APPROACHING_EXPIRY'then v_warnings=v_warnings||jsonb_build_array(jsonb_build_object('code','WEATHER_APPROACHING_EXPIRY','category','Pre-flight Weather','message','Selected observed Weather is approaching expiry.'));end if;
  if (v_w->>'inversion_assessment')in('LIKELY','CONFIRMED')then v_blockers=v_blockers||jsonb_build_array(jsonb_build_object('code','INVERSION_BLOCK','category','Pre-flight Weather','message','The inversion assessment blocks Mission readiness.'));elsif (v_w->>'inversion_assessment')in('POSSIBLE','NOT_ASSESSED','UNABLE_TO_DETERMINE')then v_warnings=v_warnings||jsonb_build_array(jsonb_build_object('code','INVERSION_REVIEW','category','Pre-flight Weather','message','The inversion assessment requires review.'));end if;end if;
 if v_f is null then v_warnings=v_warnings||jsonb_build_array(jsonb_build_object('code','PLANNING_FORECAST_NOT_SELECTED','category','Planning Weather','message','No Planning forecast has been selected. Mission planning may continue.'));end if;
 return jsonb_build_object('overallState',case when jsonb_array_length(v_blockers)=0 then 'READY' else 'BLOCKED'end,'ready',jsonb_array_length(v_blockers)=0,'planning',jsonb_build_object('ready',v_f is not null,'selectedForecastRevisionId',v_f->>'id','forecast',v_f),'preflight',jsonb_build_object('ready',v_w is not null and jsonb_array_length(v_blockers)=0,'selectedObservationRevisionId',v_w->>'id','observation',v_w),'blockers',v_blockers,'warnings',v_warnings,'freshnessState',v_w->>'freshness_state');end$$;

revoke all on function public.ftf_create_mission_weather_forecast(uuid,uuid,uuid,integer,jsonb),public.ftf_read_mission_weather_forecasts(uuid,uuid),public.ftf_select_mission_weather_forecast(uuid,uuid,uuid,uuid,integer)from public,anon,authenticated;
grant execute on function public.ftf_create_mission_weather_forecast(uuid,uuid,uuid,integer,jsonb),public.ftf_read_mission_weather_forecasts(uuid,uuid),public.ftf_select_mission_weather_forecast(uuid,uuid,uuid,uuid,integer)to service_role;
