-- Preserve the authoritative parent chain in every future Authorisation manifest.
create or replace function public.ftf_build_mission_evidence_manifest(p_organisation_id uuid,p_mission_id uuid,p_evaluated_at timestamptz default now())returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare m public.missions%rowtype;map jsonb;forecast jsonb;weather jsonb;personnel jsonb;jsa jsonb;chemicals jsonb;aircraft jsonb;kits jsonb;documents jsonb;business_context jsonb;
begin select * into m from public.missions where organisation_id=p_organisation_id and id=p_mission_id and archived_at is null;if not found then return null;end if;
 select jsonb_build_object('job',to_jsonb(j)-'organisation_id','client',to_jsonb(c)-'organisation_id','property',to_jsonb(p)-'organisation_id','fields',coalesce((select jsonb_agg(to_jsonb(f)-'organisation_id'order by f.name,f.id)from public.job_fields jf join public.fields f on f.organisation_id=jf.organisation_id and f.id=jf.field_id where jf.organisation_id=j.organisation_id and jf.job_id=j.id and jf.archived_at is null and f.archived_at is null),'[]'))into business_context from public.jobs j join public.clients c on c.organisation_id=j.organisation_id and c.id=j.client_id join public.properties p on p.organisation_id=j.organisation_id and p.id=j.property_id where j.organisation_id=p_organisation_id and j.id=m.job_id and j.archived_at is null and c.archived_at is null and p.archived_at is null;
 select x into map from public.ftf_read_mission_map(p_organisation_id,p_mission_id,false)x limit 1;
 select x into forecast from public.ftf_read_mission_weather_forecasts(p_organisation_id,p_mission_id)x where(x->>'selected')::boolean limit 1;
 select x into weather from public.ftf_read_mission_weather(p_organisation_id,p_mission_id,p_evaluated_at)x where(x->>'selected')::boolean limit 1;
 select x into personnel from public.ftf_read_mission_personnel(p_organisation_id,p_mission_id,false)x limit 1;
 select x into jsa from public.ftf_read_mission_jsa(p_organisation_id,p_mission_id,false)x limit 1;
 select x into chemicals from public.ftf_read_mission_chemical_plan(p_organisation_id,p_mission_id,false)x limit 1;
 select coalesce(jsonb_agg(jsonb_build_object('assignmentId',ma.id,'aircraftId',a.id,'rowVersion',a.row_version,'snapshot',to_jsonb(a)-'organisation_id')order by ma.assigned_at),'[]')into aircraft from public.mission_aircraft_assignments ma join public.aircraft a on a.organisation_id=ma.organisation_id and a.id=ma.aircraft_id where ma.organisation_id=p_organisation_id and ma.mission_id=p_mission_id and ma.unassigned_at is null;
 select coalesce(jsonb_agg(jsonb_build_object('assignmentId',mk.id,'equipmentKitId',k.id,'rowVersion',k.row_version,'snapshot',to_jsonb(k)-'organisation_id')order by mk.assigned_at),'[]')into kits from public.mission_equipment_kit_assignments mk join public.equipment_kits k on k.organisation_id=mk.organisation_id and k.id=mk.equipment_kit_id where mk.organisation_id=p_organisation_id and mk.mission_id=p_mission_id and mk.unassigned_at is null;
 select coalesce(jsonb_agg(jsonb_build_object('attachmentId',a.id,'internalFileId',a.internal_file_id,'fileVersion',a.file_version,'checksum',a.sha256_checksum,'evidenceType',a.evidence_type,'accessClassification',a.access_classification,'provenance',a.provenance)order by a.attached_at),'[]')into documents from public.mission_jsa_attachments a where a.organisation_id=p_organisation_id and a.mission_id=p_mission_id and a.revision_id=nullif(jsa->>'id','')::uuid;
 return jsonb_build_object('schemaVersion',2,'capturedAt',p_evaluated_at,'mission',jsonb_build_object('id',m.id,'rowVersion',m.row_version,'snapshot',to_jsonb(m)-'organisation_id'),'businessContext',business_context,'planning',jsonb_build_object('map',map,'forecastWeather',forecast,'chemicals',chemicals,'aircraft',aircraft,'equipmentKits',kits,'personnel',personnel),'preflight',jsonb_build_object('observedWeather',weather,'jsa',jsa,'requiredDocuments',documents));end$$;
revoke all on function public.ftf_build_mission_evidence_manifest(uuid,uuid,timestamptz)from public,anon,authenticated;
grant execute on function public.ftf_build_mission_evidence_manifest(uuid,uuid,timestamptz)to service_role;
