-- Cross-tenant/location resource guards and current lifecycle projection.
create function public.ftf_guard_mission_actual_resources()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare value text;m public.missions%rowtype;begin select*into m from public.missions where organisation_id=new.organisation_id and id=new.mission_id;if not found or m.operating_location_id<>new.operating_location_id then raise exception using errcode='P0001',message='RESOURCE_SCOPE_INVALID';end if;
 for value in select jsonb_array_elements_text(coalesce(new.actual_resources->'aircraftIds','[]'))loop if not exists(select 1 from public.aircraft a where a.organisation_id=new.organisation_id and a.id=value::uuid and a.operating_location_id=m.operating_location_id and a.archived_at is null)then raise exception using errcode='P0001',message='RESOURCE_SCOPE_INVALID';end if;end loop;
 for value in select jsonb_array_elements_text(coalesce(new.actual_resources->'equipmentKitIds','[]'))loop if not exists(select 1 from public.equipment_kits k where k.organisation_id=new.organisation_id and k.id=value::uuid and k.operating_location_id=m.operating_location_id and k.archived_at is null)then raise exception using errcode='P0001',message='RESOURCE_SCOPE_INVALID';end if;end loop;
 for value in select jsonb_array_elements_text(coalesce(new.actual_resources->'personnelIds','[]'))loop if not exists(select 1 from public.personnel p join public.personnel_operating_locations x on x.organisation_id=p.organisation_id and x.personnel_id=p.id where p.organisation_id=new.organisation_id and p.id=value::uuid and x.operating_location_id=m.operating_location_id and p.archived_at is null)then raise exception using errcode='P0001',message='RESOURCE_SCOPE_INVALID';end if;end loop;return new;end$$;
create trigger guard_mission_actual_resources before insert on public.mission_operational_resource_revisions for each row execute function public.ftf_guard_mission_actual_resources();

create function public.ftf_project_completed_mission_lifecycle()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin update public.missions set status='completed',row_version=row_version+1,updated_at=now()where organisation_id=new.organisation_id and id=new.mission_id and operating_location_id=new.operating_location_id;return new;end$$;
create trigger project_completed_mission_lifecycle after insert on public.mission_completion_revisions for each row execute function public.ftf_project_completed_mission_lifecycle();

revoke all on function public.ftf_guard_mission_actual_resources(),public.ftf_project_completed_mission_lifecycle()from public,anon,authenticated;
