-- NEW-ADM-001 / NEW-REP-001: authoritative organisation branding and shared
-- report identity foundation. Existing organisation and report records remain intact.

alter table public.organisations
 add column legal_business_name text,
 add column trading_name text,
 add column report_display_name text,
 add column business_identifier_type text,
 add column business_identifier_value text,
 add column registered_address jsonb,
 add column postal_address jsonb,
 add column primary_phone text,
 add column primary_email text,
 add column website text,
 add column report_contact_details jsonb,
 add column licence_accreditation_details jsonb,
 add column branding_status text not null default 'NOT_CONFIGURED'
  check(branding_status in('NOT_CONFIGURED','ACTIVE','DISABLED')),
 add column active_logo_file_id uuid,
 add column active_logo_file_version integer,
 add column report_attribution_text text not null default 'Generated by Spray Command'
  check(report_attribution_text='Generated by Spray Command'),
 add column full_white_label_enabled boolean not null default false
  check(full_white_label_enabled=false),
 add constraint organisations_active_logo_pair check(
  (active_logo_file_id is null and active_logo_file_version is null)or
  (active_logo_file_id is not null and active_logo_file_version is not null and active_logo_file_version>0)
 ),
 add constraint organisations_registered_address_object check(registered_address is null or jsonb_typeof(registered_address)='object'),
 add constraint organisations_postal_address_object check(postal_address is null or jsonb_typeof(postal_address)='object'),
 add constraint organisations_report_contact_object check(report_contact_details is null or jsonb_typeof(report_contact_details)='object'),
 add constraint organisations_accreditation_object check(licence_accreditation_details is null or jsonb_typeof(licence_accreditation_details)='object');

create table public.branding_entitlement_capabilities(
 code text primary key,
 display_name text not null,
 description text not null,
 display_order integer not null,
 full_white_label_enabled boolean not null default false
);
insert into public.branding_entitlement_capabilities(code,display_name,description,display_order,full_white_label_enabled)values
 ('BRANDING_UNAVAILABLE','Branding unavailable','Organisation logo branding is not included.',10,false),
 ('ORGANISATION_BRANDING','Organisation branding','Organisation logo and report identity are enabled with Spray Command attribution.',20,false),
 ('ADVANCED_BRANDING','Advanced branding','Reserved for future advanced report branding.',30,false),
 ('FULL_WHITE_LABEL','Full white label','Reserved for future full white-label capability.',40,false);

create table public.organisation_capability_entitlements(
 id uuid primary key default gen_random_uuid(),
 organisation_id uuid not null references public.organisations(id),
 capability_code text not null references public.branding_entitlement_capabilities(code),
 source text not null,
 effective_at timestamptz not null default now(),
 expires_at timestamptz,
 granted_by_internal_user_id uuid,
 row_version integer not null default 1 check(row_version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(organisation_id),
 unique(organisation_id,id),
 foreign key(organisation_id,granted_by_internal_user_id)references public.internal_users(organisation_id,id),
 check(expires_at is null or expires_at>effective_at)
);
insert into public.organisation_capability_entitlements(organisation_id,capability_code,source)
select id,'BRANDING_UNAVAILABLE','repository_migration_default'from public.organisations
on conflict(organisation_id)do nothing;

create trigger organisation_capability_entitlements_set_update_metadata before update on public.organisation_capability_entitlements for each row execute function public.set_tenant_row_update_metadata();
alter table public.organisation_capability_entitlements enable row level security;
alter table public.organisation_capability_entitlements force row level security;
create policy organisation_capability_entitlements_tenant_read on public.organisation_capability_entitlements for select to authenticated using(public.current_user_has_organisation_access(organisation_id));
revoke all on table public.branding_entitlement_capabilities,public.organisation_capability_entitlements from public,anon,authenticated;
grant select on table public.branding_entitlement_capabilities to service_role;
grant select,insert,update on table public.organisation_capability_entitlements to service_role;

insert into public.permissions(organisation_id,code,description)
select o.id,v.code,v.description from public.organisations o cross join(values
 ('organisation.branding.read','View organisation business profile and report branding'),
 ('organisation.branding.manage','Manage organisation business profile and report branding'),
 ('reports.read','View generated report artefacts'),
 ('reports.generate','Request generated report artefacts'),
 ('mission.pack.generate','Generate operational Mission Packs'),
 ('mission.record.generate','Generate post-completion Mission Records')
)v(code,description)on conflict(organisation_id,code)do update set description=excluded.description;

insert into public.role_permissions(organisation_id,role_id,permission_id)
select r.organisation_id,r.id,p.id from public.roles r join public.permissions p on p.organisation_id=r.organisation_id
where r.code='admin'and r.archived_at is null and p.code in('organisation.branding.read','organisation.branding.manage','reports.read','reports.generate','mission.pack.generate','mission.record.generate')
on conflict(organisation_id,role_id,permission_id)do nothing;

create function public.ftf_provision_branding_report_permissions()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
 insert into public.permissions(organisation_id,code,description)select new.organisation_id,v.code,v.description from(values
  ('organisation.branding.read','View organisation business profile and report branding'),
  ('organisation.branding.manage','Manage organisation business profile and report branding'),
  ('reports.read','View generated report artefacts'),
  ('reports.generate','Request generated report artefacts'),
  ('mission.pack.generate','Generate operational Mission Packs'),
  ('mission.record.generate','Generate post-completion Mission Records')
 )v(code,description)on conflict(organisation_id,code)do nothing;
 if new.code='admin'then
  insert into public.role_permissions(organisation_id,role_id,permission_id)
  select new.organisation_id,new.id,p.id from public.permissions p where p.organisation_id=new.organisation_id and p.code in('organisation.branding.read','organisation.branding.manage','reports.read','reports.generate','mission.pack.generate','mission.record.generate')
  on conflict(organisation_id,role_id,permission_id)do nothing;
 end if;
 return new;
end$$;
create trigger provision_branding_report_permissions after insert on public.roles for each row execute function public.ftf_provision_branding_report_permissions();

create function public.ftf_read_organisation_branding(p_organisation_id uuid)
returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
 select jsonb_build_object(
  'profile',to_jsonb(o)-'archived_by_internal_user_id',
  'entitlement',jsonb_build_object('capabilityCode',e.capability_code,'effectiveAt',e.effective_at,'expiresAt',e.expires_at),
  'attributionText','Generated by Spray Command'
 )
 from public.organisations o
 left join public.organisation_capability_entitlements e on e.organisation_id=o.id
 where o.id=p_organisation_id and o.archived_at is null
$$;

create function public.ftf_update_organisation_branding(p_organisation_id uuid,p_actor_internal_user_id uuid,p_expected_version integer,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare current public.organisations%rowtype;updated public.organisations%rowtype;previous jsonb;
begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'organisation.branding.manage')then return jsonb_build_object('forbidden',true);end if;
 select*into current from public.organisations where id=p_organisation_id and archived_at is null for update;
 if not found then return jsonb_build_object('not_found',true);end if;
 if current.row_version<>p_expected_version then return jsonb_build_object('conflict',true,'current_version',current.row_version);end if;
 previous=to_jsonb(current)-'archived_by_internal_user_id';
 update public.organisations set
  legal_business_name=nullif(trim(p_payload->>'legalBusinessName'),''),
  trading_name=nullif(trim(p_payload->>'tradingName'),''),
  report_display_name=nullif(trim(p_payload->>'reportDisplayName'),''),
  business_identifier_type=nullif(trim(p_payload->>'businessIdentifierType'),''),
  business_identifier_value=nullif(trim(p_payload->>'businessIdentifierValue'),''),
  registered_address=case when jsonb_typeof(p_payload->'registeredAddress')='object'then p_payload->'registeredAddress'else null end,
  postal_address=case when jsonb_typeof(p_payload->'postalAddress')='object'then p_payload->'postalAddress'else null end,
  primary_phone=nullif(trim(p_payload->>'primaryPhone'),''),
  primary_email=nullif(trim(p_payload->>'primaryEmail'),''),
  website=nullif(trim(p_payload->>'website'),''),
  report_contact_details=case when jsonb_typeof(p_payload->'reportContactDetails')='object'then p_payload->'reportContactDetails'else null end,
  licence_accreditation_details=case when jsonb_typeof(p_payload->'licenceAccreditationDetails')='object'then p_payload->'licenceAccreditationDetails'else null end
 where id=p_organisation_id and row_version=p_expected_version returning*into updated;
 if not found then return jsonb_build_object('conflict',true);end if;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'organisation.branding.updated','organisation',p_organisation_id,jsonb_build_object('previous_state',previous,'new_state',to_jsonb(updated)-'archived_by_internal_user_id'));
 insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'platform.organisation.branding_updated','organisation',p_organisation_id,jsonb_build_object('row_version',updated.row_version));
 return jsonb_build_object('record',public.ftf_read_organisation_branding(p_organisation_id));
end$$;

revoke all on function public.ftf_provision_branding_report_permissions(),public.ftf_read_organisation_branding(uuid),public.ftf_update_organisation_branding(uuid,uuid,integer,jsonb)from public,anon,authenticated;
grant execute on function public.ftf_read_organisation_branding(uuid),public.ftf_update_organisation_branding(uuid,uuid,integer,jsonb)to service_role;

-- Organisation row_version remains trigger-controlled by set_tenant_row_update_metadata.

create table public.organisation_logo_files(
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),internal_file_id uuid not null,file_version integer not null check(file_version>0),original_filename text not null,
 content_type text not null check(content_type in('image/png','image/jpeg','image/webp')),byte_size bigint not null check(byte_size between 1 and 5242880),sha256_checksum text not null check(sha256_checksum~'^[a-f0-9]{64}$'),width integer not null check(width between 1 and 6000),height integer not null check(height between 1 and 6000),
 storage_provider text not null,storage_bucket text not null,provider_key text not null,provenance jsonb not null default'{}',uploaded_by_internal_user_id uuid not null references public.internal_users(id),uploaded_at timestamptz not null default now(),unique(organisation_id,internal_file_id,file_version),unique(storage_provider,storage_bucket,provider_key)
);
alter table public.organisation_logo_files enable row level security;
create policy organisation_logo_files_tenant_select on public.organisation_logo_files for select using(public.current_user_has_organisation_access(organisation_id));
create trigger organisation_logo_files_immutable before update or delete on public.organisation_logo_files for each row execute function public.reject_append_only_mutation();
revoke all on public.organisation_logo_files from anon,authenticated;grant select,insert on public.organisation_logo_files to service_role;

create function public.ftf_record_organisation_logo(p_organisation_id uuid,p_actor_internal_user_id uuid,p_payload jsonb)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v public.organisation_logo_files%rowtype;begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'organisation.branding.manage')then return jsonb_build_object('forbidden',true);end if;
 insert into public.organisation_logo_files(organisation_id,internal_file_id,file_version,original_filename,content_type,byte_size,sha256_checksum,width,height,storage_provider,storage_bucket,provider_key,provenance,uploaded_by_internal_user_id)values(p_organisation_id,(p_payload->>'internalFileId')::uuid,coalesce((p_payload->>'fileVersion')::integer,1),p_payload->>'originalFilename',p_payload->>'contentType',(p_payload->>'byteSize')::bigint,p_payload->>'checksum',(p_payload->>'width')::integer,(p_payload->>'height')::integer,p_payload->>'storageProvider',p_payload->>'storageBucket',p_payload->>'providerKey',coalesce(p_payload->'provenance','{}'),p_actor_internal_user_id)returning*into v;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'organisation.logo.uploaded','organisation_logo_file',v.id,to_jsonb(v)-'provider_key');
 insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'platform.organisation.logo_uploaded','organisation_logo_file',v.id,jsonb_build_object('internal_file_id',v.internal_file_id,'file_version',v.file_version));
 return jsonb_build_object('record',to_jsonb(v));end$$;

create function public.ftf_activate_organisation_logo(p_organisation_id uuid,p_actor_internal_user_id uuid,p_expected_version integer,p_internal_file_id uuid,p_file_version integer)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare l public.organisation_logo_files%rowtype;o public.organisations%rowtype;previous jsonb;begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'organisation.branding.manage')then return jsonb_build_object('forbidden',true);end if;
 select*into l from public.organisation_logo_files where organisation_id=p_organisation_id and internal_file_id=p_internal_file_id and file_version=p_file_version;if not found then return jsonb_build_object('not_found',true);end if;
 select to_jsonb(x)into previous from public.organisations x where id=p_organisation_id;update public.organisations set active_logo_file_id=p_internal_file_id,active_logo_file_version=p_file_version,branding_status='ACTIVE'where id=p_organisation_id and row_version=p_expected_version returning*into o;
 if not found then return jsonb_build_object('conflict',true,'current_version',(select row_version from public.organisations where id=p_organisation_id));end if;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'organisation.logo.activated','organisation',p_organisation_id,jsonb_build_object('previous_state',previous,'new_state',to_jsonb(o)));
 insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'platform.organisation.logo_activated','organisation',p_organisation_id,jsonb_build_object('internal_file_id',p_internal_file_id,'file_version',p_file_version,'row_version',o.row_version));return jsonb_build_object('record',to_jsonb(o));end$$;

create function public.ftf_remove_organisation_logo(p_organisation_id uuid,p_actor_internal_user_id uuid,p_expected_version integer)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare o public.organisations%rowtype;previous jsonb;begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'organisation.branding.manage')then return jsonb_build_object('forbidden',true);end if;select to_jsonb(x)into previous from public.organisations x where id=p_organisation_id;
 update public.organisations set active_logo_file_id=null,active_logo_file_version=null,branding_status='UNBRANDED'where id=p_organisation_id and row_version=p_expected_version returning*into o;if not found then return jsonb_build_object('conflict',true,'current_version',(select row_version from public.organisations where id=p_organisation_id));end if;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'organisation.logo.removed','organisation',p_organisation_id,jsonb_build_object('previous_state',previous,'new_state',to_jsonb(o)));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'platform.organisation.logo_removed','organisation',p_organisation_id,jsonb_build_object('row_version',o.row_version));return jsonb_build_object('record',to_jsonb(o));end$$;
revoke all on function public.ftf_record_organisation_logo(uuid,uuid,jsonb),public.ftf_activate_organisation_logo(uuid,uuid,integer,uuid,integer),public.ftf_remove_organisation_logo(uuid,uuid,integer)from public,anon,authenticated;
grant execute on function public.ftf_record_organisation_logo(uuid,uuid,jsonb),public.ftf_activate_organisation_logo(uuid,uuid,integer,uuid,integer),public.ftf_remove_organisation_logo(uuid,uuid,integer)to service_role;

create table public.report_artefacts(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),operating_location_id uuid not null references public.operating_locations(id),mission_id uuid not null references public.missions(id),report_type text not null check(report_type in('MISSION_PACK','MISSION_RECORD')),version_number integer not null check(version_number>0),template_version integer not null default 1,status text not null default'QUEUED'check(status in('QUEUED','GENERATING','READY','FAILED')),idempotency_key text not null,branding_snapshot jsonb not null,evidence_manifest jsonb not null,requested_by_internal_user_id uuid not null references public.internal_users(id),created_at timestamptz not null default now(),completed_at timestamptz,error_code text,error_message text,unique(organisation_id,mission_id,report_type,version_number),unique(organisation_id,idempotency_key));
create table public.report_generation_jobs(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),artefact_id uuid not null unique references public.report_artefacts(id),status text not null default'QUEUED'check(status in('QUEUED','GENERATING','READY','FAILED')),attempt_count integer not null default 0,max_attempts integer not null default 3,available_at timestamptz not null default now(),lease_owner text,lease_expires_at timestamptz,last_error_code text,last_error_message text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.report_output_files(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),artefact_id uuid not null unique references public.report_artefacts(id),internal_file_id uuid not null,file_version integer not null default 1,original_filename text not null,content_type text not null default'application/pdf',byte_size bigint not null,sha256_checksum text not null,storage_provider text not null,storage_bucket text not null,provider_key text not null,created_at timestamptz not null default now(),unique(organisation_id,internal_file_id,file_version));
do $$declare t text;begin foreach t in array array['report_artefacts','report_generation_jobs','report_output_files']loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('create policy %I on public.%I for select to authenticated using(public.current_user_has_organisation_access(organisation_id))',t||'_tenant_read',t);execute format('revoke all on table public.%I from public,anon,authenticated',t);execute format('grant select,insert,update on table public.%I to service_role',t);end loop;end$$;
create trigger report_artefacts_immutable before update or delete on public.report_artefacts for each row execute function public.reject_append_only_mutation();create trigger report_output_files_immutable before update or delete on public.report_output_files for each row execute function public.reject_append_only_mutation();

create function public.ftf_request_report_artefact(p_organisation_id uuid,p_actor_internal_user_id uuid,p_mission_id uuid,p_report_type text,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare m public.missions%rowtype;existing public.report_artefacts%rowtype;c public.mission_completion_revisions%rowtype;n integer;a public.report_artefacts%rowtype;branding jsonb;evidence jsonb;begin
 select*into existing from public.report_artefacts where organisation_id=p_organisation_id and idempotency_key=p_idempotency_key;if found then return jsonb_build_object('artefact',to_jsonb(existing),'reused',true);end if;select*into m from public.missions where organisation_id=p_organisation_id and id=p_mission_id and archived_at is null;if not found then return jsonb_build_object('not_found',true);end if;if not public.ftf_operational_location_allowed(p_organisation_id,p_actor_internal_user_id,m.operating_location_id)then return jsonb_build_object('location_forbidden',true);end if;
 if p_report_type='MISSION_RECORD'then select*into c from public.mission_completion_revisions where organisation_id=p_organisation_id and mission_id=p_mission_id order by version_number desc limit 1;if not found then return jsonb_build_object('completion_required',true);end if;evidence=jsonb_build_object('schemaVersion',1,'missionId',m.id,'completionRevision',to_jsonb(c),'missionOutcomes',coalesce((select jsonb_agg(to_jsonb(x)order by x.sequence_number)from public.mission_outcome_observations x where x.organisation_id=p_organisation_id and x.mission_id=m.id),'[]'),'customerOutcomes',coalesce((select jsonb_agg(to_jsonb(x)order by x.sequence_number)from public.customer_acceptance_records x where x.organisation_id=p_organisation_id and x.mission_id=m.id),'[]'));else evidence=jsonb_build_object('schemaVersion',1,'missionId',m.id,'missionPackRevision',(select to_jsonb(x)from public.mission_pack_revisions x where x.organisation_id=p_organisation_id and x.mission_id=m.id order by x.version_number desc limit 1));end if;
 branding=public.ftf_read_organisation_branding(p_organisation_id)||jsonb_build_object('attribution','Generated by Spray Command');select coalesce(max(version_number),0)+1 into n from public.report_artefacts where organisation_id=p_organisation_id and mission_id=m.id and report_type=p_report_type;insert into public.report_artefacts(organisation_id,operating_location_id,mission_id,report_type,version_number,idempotency_key,branding_snapshot,evidence_manifest,requested_by_internal_user_id)values(p_organisation_id,m.operating_location_id,m.id,p_report_type,n,p_idempotency_key,branding,evidence,p_actor_internal_user_id)returning*into a;insert into public.report_generation_jobs(organisation_id,artefact_id)values(p_organisation_id,a.id);insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'report.requested','report_artefact',a.id,jsonb_build_object('report_type',p_report_type,'version',n));insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'reports.generation.requested','report_artefact',a.id,jsonb_build_object('report_type',p_report_type,'version',n));return jsonb_build_object('artefact',to_jsonb(a),'reused',false);end$$;
revoke all on function public.ftf_request_report_artefact(uuid,uuid,uuid,text,text)from public,anon,authenticated;grant execute on function public.ftf_request_report_artefact(uuid,uuid,uuid,text,text)to service_role;

drop trigger report_artefacts_immutable on public.report_artefacts;
create function public.protect_report_artefact_mutation()returns trigger language plpgsql as $$begin if tg_op='DELETE'then raise exception'append-only record';end if;if current_setting('app.report_worker_transition',true)<>'allowed'or new.id<>old.id or new.organisation_id<>old.organisation_id or new.mission_id<>old.mission_id or new.report_type<>old.report_type or new.version_number<>old.version_number or new.template_version<>old.template_version or new.idempotency_key<>old.idempotency_key or new.branding_snapshot<>old.branding_snapshot or new.evidence_manifest<>old.evidence_manifest or new.requested_by_internal_user_id<>old.requested_by_internal_user_id or new.created_at<>old.created_at then raise exception'append-only record';end if;return new;end$$;
create trigger report_artefacts_immutable before update or delete on public.report_artefacts for each row execute function public.protect_report_artefact_mutation();

create function public.ftf_claim_report_generation_job(p_worker_id text,p_lease_seconds integer default 120)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare j public.report_generation_jobs%rowtype;a public.report_artefacts%rowtype;begin select*into j from public.report_generation_jobs where(status='QUEUED'and available_at<=now())or(status='GENERATING'and lease_expires_at<now())order by created_at for update skip locked limit 1;if not found then return null;end if;update public.report_generation_jobs set status='GENERATING',attempt_count=attempt_count+1,lease_owner=p_worker_id,lease_expires_at=now()+make_interval(secs=>least(greatest(p_lease_seconds,30),900)),updated_at=now()where id=j.id returning*into j;perform set_config('app.report_worker_transition','allowed',true);update public.report_artefacts set status='GENERATING'where id=j.artefact_id;select*into a from public.report_artefacts where id=j.artefact_id;return to_jsonb(j)||jsonb_build_object('artefact',to_jsonb(a));end$$;
create function public.ftf_complete_report_generation_job(p_job_id uuid,p_artefact_id uuid,p_file jsonb)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare f public.report_output_files%rowtype;begin insert into public.report_output_files(organisation_id,artefact_id,internal_file_id,file_version,original_filename,content_type,byte_size,sha256_checksum,storage_provider,storage_bucket,provider_key)select organisation_id,id,(p_file->>'internalFileId')::uuid,(p_file->>'fileVersion')::integer,p_file->>'originalFilename',p_file->>'contentType',(p_file->>'byteSize')::bigint,p_file->>'checksum',p_file->>'storageProvider',p_file->>'storageBucket',p_file->>'providerKey'from public.report_artefacts where id=p_artefact_id returning*into f;update public.report_generation_jobs set status='READY',lease_owner=null,lease_expires_at=null,updated_at=now()where id=p_job_id and artefact_id=p_artefact_id;perform set_config('app.report_worker_transition','allowed',true);update public.report_artefacts set status='READY',completed_at=now()where id=p_artefact_id;return jsonb_build_object('record',to_jsonb(f));end$$;
create function public.ftf_fail_report_generation_job(p_job_id uuid,p_artefact_id uuid,p_error_code text,p_error_message text)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare j public.report_generation_jobs%rowtype;begin update public.report_generation_jobs set status=case when attempt_count>=max_attempts then'FAILED'else'QUEUED'end,available_at=now()+make_interval(secs=>least(300,attempt_count*30)),lease_owner=null,lease_expires_at=null,last_error_code=p_error_code,last_error_message=p_error_message,updated_at=now()where id=p_job_id and artefact_id=p_artefact_id returning*into j;perform set_config('app.report_worker_transition','allowed',true);update public.report_artefacts set status=case when j.status='FAILED'then'FAILED'else'QUEUED'end,error_code=p_error_code,error_message=p_error_message where id=p_artefact_id;return to_jsonb(j);end$$;
revoke all on function public.ftf_claim_report_generation_job(text,integer),public.ftf_complete_report_generation_job(uuid,uuid,jsonb),public.ftf_fail_report_generation_job(uuid,uuid,text,text)from public,anon,authenticated;grant execute on function public.ftf_claim_report_generation_job(text,integer),public.ftf_complete_report_generation_job(uuid,uuid,jsonb),public.ftf_fail_report_generation_job(uuid,uuid,text,text)to service_role;
