-- NEW-ADM-001 / NEW-REP-001: authoritative organisation branding and shared
-- report identity foundation. Existing organisation and report records remain intact.

alter table public.organisations
 add column legal_business_name text,
 add column trading_name text,
 add column report_display_name text,
 add column business_identifier_type text,
 add column business_identifier_value text,
 add column registered_address jsonb,
 add column postal_address jsonb,
 add column primary_phone text,
 add column primary_email text,
 add column website text,
 add column report_contact_details jsonb,
 add column licence_accreditation_details jsonb,
 add column branding_status text not null default 'NOT_CONFIGURED'
  check(branding_status in('NOT_CONFIGURED','ACTIVE','DISABLED')),
 add column active_logo_file_id uuid,
 add column active_logo_file_version integer,
 add column report_attribution_text text not null default 'Generated by Spray Command'
  check(report_attribution_text='Generated by Spray Command'),
 add column full_white_label_enabled boolean not null default false
  check(full_white_label_enabled=false),
 add constraint organisations_active_logo_pair check(
  (active_logo_file_id is null and active_logo_file_version is null)or
  (active_logo_file_id is not null and active_logo_file_version is not null and active_logo_file_version>0)
 ),
 add constraint organisations_registered_address_object check(registered_address is null or jsonb_typeof(registered_address)='object'),
 add constraint organisations_postal_address_object check(postal_address is null or jsonb_typeof(postal_address)='object'),
 add constraint organisations_report_contact_object check(report_contact_details is null or jsonb_typeof(report_contact_details)='object'),
 add constraint organisations_accreditation_object check(licence_accreditation_details is null or jsonb_typeof(licence_accreditation_details)='object');

create table public.branding_entitlement_capabilities(
 code text primary key,
 display_name text not null,
 description text not null,
 display_order integer not null,
 full_white_label_enabled boolean not null default false
);
insert into public.branding_entitlement_capabilities(code,display_name,description,display_order,full_white_label_enabled)values
 ('BRANDING_UNAVAILABLE','Branding unavailable','Organisation logo branding is not included.',10,false),
 ('ORGANISATION_BRANDING','Organisation branding','Organisation logo and report identity are enabled with Spray Command attribution.',20,false),
 ('ADVANCED_BRANDING','Advanced branding','Reserved for future advanced report branding.',30,false),
 ('FULL_WHITE_LABEL','Full white label','Reserved for future full white-label capability.',40,false);

create table public.organisation_capability_entitlements(
 id uuid primary key default gen_random_uuid(),
 organisation_id uuid not null references public.organisations(id),
 capability_code text not null references public.branding_entitlement_capabilities(code),
 source text not null,
 effective_at timestamptz not null default now(),
 expires_at timestamptz,
 granted_by_internal_user_id uuid,
 row_version integer not null default 1 check(row_version>0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(organisation_id),
 unique(organisation_id,id),
 foreign key(organisation_id,granted_by_internal_user_id)references public.internal_users(organisation_id,id),
 check(expires_at is null or expires_at>effective_at)
);
insert into public.organisation_capability_entitlements(organisation_id,capability_code,source)
select id,'BRANDING_UNAVAILABLE','repository_migration_default'from public.organisations
on conflict(organisation_id)do nothing;

create trigger organisation_capability_entitlements_set_update_metadata before update on public.organisation_capability_entitlements for each row execute function public.set_tenant_row_update_metadata();
alter table public.organisation_capability_entitlements enable row level security;
alter table public.organisation_capability_entitlements force row level security;
create policy organisation_capability_entitlements_tenant_read on public.organisation_capability_entitlements for select to authenticated using(public.current_user_has_organisation_access(organisation_id));
revoke all on table public.branding_entitlement_capabilities,public.organisation_capability_entitlements from public,anon,authenticated;
grant select on table public.branding_entitlement_capabilities to service_role;
grant select,insert,update on table public.organisation_capability_entitlements to service_role;

insert into public.permissions(organisation_id,code,description)
select o.id,v.code,v.description from public.organisations o cross join(values
 ('organisation.branding.read','View organisation business profile and report branding'),
 ('organisation.branding.manage','Manage organisation business profile and report branding'),
 ('reports.read','View generated report artefacts'),
 ('reports.generate','Request generated report artefacts'),
 ('mission.pack.generate','Generate operational Mission Packs'),
 ('mission.record.generate','Generate post-completion Mission Records')
)v(code,description)on conflict(organisation_id,code)do update set description=excluded.description;

insert into public.role_permissions(organisation_id,role_id,permission_id)
select r.organisation_id,r.id,p.id from public.roles r join public.permissions p on p.organisation_id=r.organisation_id
where r.code='admin'and r.archived_at is null and p.code in('organisation.branding.read','organisation.branding.manage','reports.read','reports.generate','mission.pack.generate','mission.record.generate')
on conflict(organisation_id,role_id,permission_id)do nothing;

create function public.ftf_provision_branding_report_permissions()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
 insert into public.permissions(organisation_id,code,description)select new.organisation_id,v.code,v.description from(values
  ('organisation.branding.read','View organisation business profile and report branding'),
  ('organisation.branding.manage','Manage organisation business profile and report branding'),
  ('reports.read','View generated report artefacts'),
  ('reports.generate','Request generated report artefacts'),
  ('mission.pack.generate','Generate operational Mission Packs'),
  ('mission.record.generate','Generate post-completion Mission Records')
 )v(code,description)on conflict(organisation_id,code)do nothing;
 if new.code='admin'then
  insert into public.role_permissions(organisation_id,role_id,permission_id)
  select new.organisation_id,new.id,p.id from public.permissions p where p.organisation_id=new.organisation_id and p.code in('organisation.branding.read','organisation.branding.manage','reports.read','reports.generate','mission.pack.generate','mission.record.generate')
  on conflict(organisation_id,role_id,permission_id)do nothing;
 end if;
 return new;
end$$;
create trigger provision_branding_report_permissions after insert on public.roles for each row execute function public.ftf_provision_branding_report_permissions();

create function public.ftf_read_organisation_branding(p_organisation_id uuid)
returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
 select jsonb_build_object(
  'profile',to_jsonb(o)-'archived_by_internal_user_id',
  'entitlement',jsonb_build_object('capabilityCode',e.capability_code,'effectiveAt',e.effective_at,'expiresAt',e.expires_at),
  'attributionText','Generated by Spray Command'
 )
 from public.organisations o
 left join public.organisation_capability_entitlements e on e.organisation_id=o.id
 where o.id=p_organisation_id and o.archived_at is null
$$;

create function public.ftf_update_organisation_branding(p_organisation_id uuid,p_actor_internal_user_id uuid,p_expected_version integer,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare current public.organisations%rowtype;updated public.organisations%rowtype;previous jsonb;
begin
 if not public.ftf_actor_has_permission(p_organisation_id,p_actor_internal_user_id,'organisation.branding.manage')then return jsonb_build_object('forbidden',true);end if;
 select*into current from public.organisations where id=p_organisation_id and archived_at is null for update;
 if not found then return jsonb_build_object('not_found',true);end if;
 if current.row_version<>p_expected_version then return jsonb_build_object('conflict',true,'current_version',current.row_version);end if;
 previous=to_jsonb(current)-'archived_by_internal_user_id';
 update public.organisations set
  legal_business_name=nullif(trim(p_payload->>'legalBusinessName'),''),
  trading_name=nullif(trim(p_payload->>'tradingName'),''),
  report_display_name=nullif(trim(p_payload->>'reportDisplayName'),''),
  business_identifier_type=nullif(trim(p_payload->>'businessIdentifierType'),''),
  business_identifier_value=nullif(trim(p_payload->>'businessIdentifierValue'),''),
  registered_address=case when jsonb_typeof(p_payload->'registeredAddress')='object'then p_payload->'registeredAddress'else null end,
  postal_address=case when jsonb_typeof(p_payload->'postalAddress')='object'then p_payload->'postalAddress'else null end,
  primary_phone=nullif(trim(p_payload->>'primaryPhone'),''),
  primary_email=nullif(trim(p_payload->>'primaryEmail'),''),
  website=nullif(trim(p_payload->>'website'),''),
  report_contact_details=case when jsonb_typeof(p_payload->'reportContactDetails')='object'then p_payload->'reportContactDetails'else null end,
  licence_accreditation_details=case when jsonb_typeof(p_payload->'licenceAccreditationDetails')='object'then p_payload->'licenceAccreditationDetails'else null end
 where id=p_organisation_id and row_version=p_expected_version returning*into updated;
 if not found then return jsonb_build_object('conflict',true);end if;
 insert into public.audit_events(organisation_id,actor_internal_user_id,event_type,entity_type,entity_id,event_payload)values(p_organisation_id,p_actor_internal_user_id,'organisation.branding.updated','organisation',p_organisation_id,jsonb_build_object('previous_state',previous,'new_state',to_jsonb(updated)-'archived_by_internal_user_id'));
 insert into public.transactional_outbox(organisation_id,topic,aggregate_type,aggregate_id,payload)values(p_organisation_id,'platform.organisation.branding_updated','organisation',p_organisation_id,jsonb_build_object('row_version',updated.row_version));
 return jsonb_build_object('record',public.ftf_read_organisation_branding(p_organisation_id));
end$$;

revoke all on function public.ftf_provision_branding_report_permissions(),public.ftf_read_organisation_branding(uuid),public.ftf_update_organisation_branding(uuid,uuid,integer,jsonb)from public,anon,authenticated;
grant execute on function public.ftf_read_organisation_branding(uuid),public.ftf_update_organisation_branding(uuid,uuid,integer,jsonb)to service_role;

-- Organisation row_version remains trigger-controlled by set_tenant_row_update_metadata.
